-- 177-band-defaults-from-canonical-seed.sql
-- GENERATED by scripts/gen_band_seed_sql.py from verdify_schemas/band_defaults.yaml.
-- DO NOT hand-edit — change band_defaults.yaml and re-run `--write`.
--
-- Purpose: make crop_band_anchors agree with the ONE canonical band declaration.
-- The migration-replay history diverged from live prod via ad-hoc UPDATEs that
-- never had a migration (e.g. migration 168 left orchid vpd_target at
-- 1.05/1.10/1.05/1.05, but live prod is 0.90/1.10/0.90/0.70). This forward
-- reconcile captures those live edits as committed truth.
--
-- Safety: ON CONFLICT DO UPDATE ... WHERE the value/width actually DIFFERS, so on
-- prod (already == canonical) this updates ZERO rows — a verified no-op. On a
-- fresh DB / CI replay it aligns the rows to the canonical live band. Advisory
-- per-crop temp_target rows are intentionally untouched.
--
-- Non-self-transactional (no top-level BEGIN/COMMIT, no CONCURRENTLY): safe to
-- rollback-validate by wrapping in BEGIN; ... ROLLBACK;.

-- House air band (value-only; widths are NULL on house rows).
INSERT INTO public.crop_band_anchors (crop_type, series, anchor, value) VALUES
  ('house','temp_low','sr',62.5), ('house','temp_low','sm',73.79), ('house','temp_low','ss',72), ('house','temp_low','mid',58),
  ('house','temp_target','sr',67.5), ('house','temp_target','sm',78.79), ('house','temp_target','ss',77), ('house','temp_target','mid',62),
  ('house','temp_high','sr',72.5), ('house','temp_high','sm',83.79), ('house','temp_high','ss',82), ('house','temp_high','mid',66),
  ('house','vpd_low','sr',0.755), ('house','vpd_low','sm',0.862), ('house','vpd_low','ss',0.845), ('house','vpd_low','mid',0.738),
  ('house','vpd_target','sr',0.935), ('house','vpd_target','sm',1.042), ('house','vpd_target','ss',1.025), ('house','vpd_target','mid',0.918),
  ('house','vpd_high','sr',1.185), ('house','vpd_high','sm',1.292), ('house','vpd_high','ss',1.275), ('house','vpd_high','mid',1.168)
ON CONFLICT (crop_type, growth_stage, season, series, anchor, greenhouse_id) DO UPDATE SET value = EXCLUDED.value
  WHERE public.crop_band_anchors.value IS DISTINCT FROM EXCLUDED.value;

-- Per-zone VPD-target band (value + half-widths).
INSERT INTO public.crop_band_anchors (crop_type, series, anchor, value, width_below, width_above) VALUES
  ('orchid','vpd_target','sr',0.9,0.2,0.35), ('orchid','vpd_target','sm',1.1,0.2,0.35), ('orchid','vpd_target','ss',0.9,0.2,0.35), ('orchid','vpd_target','mid',0.7,0.2,0.35),
  ('cannabis','vpd_target','sr',0.85,0.18,0.22), ('cannabis','vpd_target','sm',1.18,0.18,0.22), ('cannabis','vpd_target','ss',0.95,0.18,0.22), ('cannabis','vpd_target','mid',0.75,0.18,0.22),
  ('citrus','vpd_target','sr',0.6,0.16,0.22), ('citrus','vpd_target','sm',1.1,0.16,0.22), ('citrus','vpd_target','ss',0.7,0.16,0.22), ('citrus','vpd_target','mid',0.57,0.16,0.22),
  ('pepper','vpd_target','sr',0.8,0.15,0.23), ('pepper','vpd_target','sm',1.22,0.15,0.23), ('pepper','vpd_target','ss',0.9,0.15,0.23), ('pepper','vpd_target','mid',0.74,0.15,0.23)
ON CONFLICT (crop_type, growth_stage, season, series, anchor, greenhouse_id) DO UPDATE SET
    value = EXCLUDED.value,
    width_below = EXCLUDED.width_below,
    width_above = EXCLUDED.width_above
  WHERE public.crop_band_anchors.value IS DISTINCT FROM EXCLUDED.value
     OR public.crop_band_anchors.width_below IS DISTINCT FROM EXCLUDED.width_below
     OR public.crop_band_anchors.width_above IS DISTINCT FROM EXCLUDED.width_above;

-- Post-reconcile assertion: every canonical row now equals the declaration.
DO $assert$
DECLARE
    n_mismatch int;
BEGIN
    SELECT count(*) INTO n_mismatch FROM (VALUES
      ('house','temp_low','sr',62.5::double precision),
      ('house','temp_low','sm',73.79::double precision),
      ('house','temp_low','ss',72::double precision),
      ('house','temp_low','mid',58::double precision),
      ('house','temp_target','sr',67.5::double precision),
      ('house','temp_target','sm',78.79::double precision),
      ('house','temp_target','ss',77::double precision),
      ('house','temp_target','mid',62::double precision),
      ('house','temp_high','sr',72.5::double precision),
      ('house','temp_high','sm',83.79::double precision),
      ('house','temp_high','ss',82::double precision),
      ('house','temp_high','mid',66::double precision),
      ('house','vpd_low','sr',0.755::double precision),
      ('house','vpd_low','sm',0.862::double precision),
      ('house','vpd_low','ss',0.845::double precision),
      ('house','vpd_low','mid',0.738::double precision),
      ('house','vpd_target','sr',0.935::double precision),
      ('house','vpd_target','sm',1.042::double precision),
      ('house','vpd_target','ss',1.025::double precision),
      ('house','vpd_target','mid',0.918::double precision),
      ('house','vpd_high','sr',1.185::double precision),
      ('house','vpd_high','sm',1.292::double precision),
      ('house','vpd_high','ss',1.275::double precision),
      ('house','vpd_high','mid',1.168::double precision),
      ('orchid','vpd_target','sr',0.9::double precision),
      ('orchid','vpd_target','sm',1.1::double precision),
      ('orchid','vpd_target','ss',0.9::double precision),
      ('orchid','vpd_target','mid',0.7::double precision),
      ('cannabis','vpd_target','sr',0.85::double precision),
      ('cannabis','vpd_target','sm',1.18::double precision),
      ('cannabis','vpd_target','ss',0.95::double precision),
      ('cannabis','vpd_target','mid',0.75::double precision),
      ('citrus','vpd_target','sr',0.6::double precision),
      ('citrus','vpd_target','sm',1.1::double precision),
      ('citrus','vpd_target','ss',0.7::double precision),
      ('citrus','vpd_target','mid',0.57::double precision),
      ('pepper','vpd_target','sr',0.8::double precision),
      ('pepper','vpd_target','sm',1.22::double precision),
      ('pepper','vpd_target','ss',0.9::double precision),
      ('pepper','vpd_target','mid',0.74::double precision)
    ) AS want(crop_type, series, anchor, value)
    JOIN public.crop_band_anchors a USING (crop_type, series, anchor)
    WHERE a.greenhouse_id = 'vallery' AND a.value IS DISTINCT FROM want.value;
    IF n_mismatch > 0 THEN
        RAISE EXCEPTION '177: % canonical band row(s) failed to reconcile to band_defaults.yaml', n_mismatch;
    END IF;
    RAISE NOTICE '177: crop_band_anchors reconciled to canonical band_defaults.yaml';
END
$assert$;
