-- 195-dli-availability-provenance.sql
--
-- Issue #435: interior crop DLI is unavailable while the interior light
-- sensor is broken.  Preserve legacy proxy values for forensic inspection,
-- but never promote them to measured crop evidence.
--
-- Non-self-transactional: safe for an outer rollback proof.

CREATE TABLE IF NOT EXISTS public.dli_validity_intervals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    greenhouse_id text NOT NULL DEFAULT 'vallery',
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    availability text NOT NULL,
    unavailable_reason text,
    provenance text NOT NULL,
    validity_revision text NOT NULL,
    operator_validated boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL DEFAULT 'migration_195',
    CONSTRAINT dli_validity_interval_order CHECK (
        valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT dli_validity_availability CHECK (
        availability IN ('available', 'unavailable')
    ),
    CONSTRAINT dli_validity_evidence_shape CHECK (
        (
            availability = 'available'
            AND operator_validated
            AND unavailable_reason IS NULL
        ) OR (
            availability = 'unavailable'
            AND NOT operator_validated
            AND unavailable_reason IS NOT NULL
            AND btrim(unavailable_reason) <> ''
        )
    ),
    CONSTRAINT dli_validity_revision_unique UNIQUE (
        greenhouse_id, validity_revision
    )
);

-- v195 is intentionally fail closed. This is an application/schema invariant,
-- not a privilege boundary: the production application role owns this table.
-- Enabling measured DLI therefore requires a separately reviewed migration
-- that removes/replaces this constraint and updates the product contract.
ALTER TABLE public.dli_validity_intervals
    DROP CONSTRAINT IF EXISTS dli_validity_release_unavailable;
ALTER TABLE public.dli_validity_intervals
    ADD CONSTRAINT dli_validity_release_unavailable CHECK (
        availability = 'unavailable'
        AND NOT operator_validated
    );

COMMENT ON TABLE public.dli_validity_intervals IS
'Fail-closed validity ledger for interior crop DLI. Migration 195 permits unavailable intervals only; ordinary DML cannot activate DLI. Future activation requires a separately reviewed migration/contract change. This is a schema invariant, not DB-role privilege separation.';

CREATE OR REPLACE FUNCTION public.enforce_dli_validity_nonoverlap()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.dli_validity_intervals existing
        WHERE existing.greenhouse_id = NEW.greenhouse_id
          AND existing.id <> COALESCE(NEW.id, -1)
          AND tstzrange(
                existing.valid_from,
                COALESCE(existing.valid_to, 'infinity'::timestamptz),
                '[)'
              ) && tstzrange(
                NEW.valid_from,
                COALESCE(NEW.valid_to, 'infinity'::timestamptz),
                '[)'
              )
    ) THEN
        RAISE EXCEPTION
            'DLI validity interval overlaps an existing interval for greenhouse %',
            NEW.greenhouse_id;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_dli_validity_nonoverlap
    ON public.dli_validity_intervals;
CREATE TRIGGER trg_dli_validity_nonoverlap
BEFORE INSERT OR UPDATE ON public.dli_validity_intervals
FOR EACH ROW EXECUTE FUNCTION public.enforce_dli_validity_nonoverlap();

-- The legacy accumulator has never been backed by an operator-validated
-- interior sensor.  Start before recorded production history so every legacy
-- row is classified without rewriting or deleting its numeric proxy value.
INSERT INTO public.dli_validity_intervals (
    greenhouse_id,
    valid_from,
    valid_to,
    availability,
    unavailable_reason,
    provenance,
    validity_revision,
    operator_validated,
    created_by
) SELECT
    'vallery',
    '2024-01-01 00:00:00+00',
    NULL,
    'unavailable',
    'interior_light_sensor_broken',
    'legacy_invalid_exterior_proxy_plus_fixture_estimate',
    'dli-validity-v1',
    false,
    'migration_195'
WHERE NOT EXISTS (
    SELECT 1
    FROM public.dli_validity_intervals existing
    WHERE existing.greenhouse_id = 'vallery'
      AND existing.validity_revision = 'dli-validity-v1'
);

CREATE OR REPLACE FUNCTION public.fn_dli_validity(
    p_ts timestamptz DEFAULT now(),
    p_greenhouse_id text DEFAULT 'vallery'
)
RETURNS TABLE (
    availability text,
    unavailable_reason text,
    provenance text,
    validity_revision text,
    valid_from timestamptz,
    valid_to timestamptz,
    operator_validated boolean
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        v.availability,
        v.unavailable_reason,
        v.provenance,
        v.validity_revision,
        v.valid_from,
        v.valid_to,
        v.operator_validated
    FROM public.dli_validity_intervals v
    WHERE v.greenhouse_id = p_greenhouse_id
      AND p_ts >= v.valid_from
      AND (v.valid_to IS NULL OR p_ts < v.valid_to)
    ORDER BY v.valid_from DESC
    LIMIT 1
$$;

COMMENT ON FUNCTION public.fn_dli_validity(timestamptz, text) IS
'Returns the one half-open validity interval governing interior crop DLI at a timestamp. Under migration 195 every returned interval is unavailable; no row means no DLI contract exists.';

CREATE OR REPLACE FUNCTION public.fn_dli_source_invalid_reason(
    p_value double precision
)
RETURNS text
LANGUAGE plpgsql
IMMUTABLE
AS $$
BEGIN
    IF p_value IS NULL THEN
        RETURN 'source_reading_missing';
    ELSIF p_value::text IN ('NaN', 'Infinity', '-Infinity') THEN
        RETURN 'source_reading_nonfinite';
    ELSIF p_value < 0 THEN
        RETURN 'source_reading_negative';
    ELSIF p_value > 100 THEN
        RETURN 'source_reading_out_of_range';
    END IF;
    RETURN NULL;
END;
$$;

COMMENT ON FUNCTION public.fn_dli_source_invalid_reason(double precision) IS
'Returns an explicit reason when candidate interior DLI is missing, non-finite, negative, or outside the 0..100 mol/m2/day product range.';

CREATE OR REPLACE FUNCTION public.fn_dli_proxy_lesson_invalid(
    p_condition text,
    p_lesson text
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    WITH normalized AS (
        SELECT lower(
            COALESCE(p_condition, '') || ' ' || COALESCE(p_lesson, '')
        ) AS body
    )
    SELECT
        body ~ '(sensor[_ -]*dli|dli[_ -]*(today|sensor)|interior[^.]{0,40}dli|crop[^.]{0,40}dli)'
        AND (
            body ~ '(×|[*]|[[:space:]]x[[:space:]])[[:space:]]*[0-9]'
            OR body ~ '(correction|corrected|proxy|estimate|estimated|multiply|multiplied|factor)'
            OR body ~ 'grow[_ -]*light[_ -]*(hours|runtime)'
        )
    FROM normalized
$$;

COMMENT ON FUNCTION public.fn_dli_proxy_lesson_invalid(text, text) IS
'Matches operational lessons that infer interior/crop DLI from the invalid sensor, a correction factor, proxy, estimate, or grow-light runtime.';

-- Preserve the complete planner_lessons row for forensics, but retire the
-- invalid live formula and prevent equivalent future text from being active.
UPDATE public.planner_lessons
SET is_active = false
WHERE is_active IS TRUE
  AND public.fn_dli_proxy_lesson_invalid(condition, lesson);

ALTER TABLE public.planner_lessons
    DROP CONSTRAINT IF EXISTS planner_lessons_active_dli_proxy_block;
ALTER TABLE public.planner_lessons
    ADD CONSTRAINT planner_lessons_active_dli_proxy_block CHECK (
        is_active IS NOT TRUE
        OR NOT public.fn_dli_proxy_lesson_invalid(condition, lesson)
    );

CREATE OR REPLACE FUNCTION public.fn_search_embeddings(
    query_embedding vector(3072),
    p_top_k integer DEFAULT 10,
    p_source_types text[] DEFAULT ARRAY[
        'lesson', 'plan', 'site_doc', 'playbook', 'observation'
    ]
)
RETURNS TABLE (
    source_type text,
    source_id text,
    chunk_idx integer,
    content text,
    metadata jsonb,
    distance double precision
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        e.source_type,
        e.source_id,
        e.chunk_idx,
        e.content,
        e.metadata,
        (e.embedding <=> query_embedding)::double precision AS distance
    FROM public.verdify_embeddings e
    LEFT JOIN public.planner_lessons pl
      ON e.source_type = 'lesson'
     AND pl.id::text = e.source_id
    WHERE e.source_type = ANY(p_source_types)
      AND (
          e.source_type <> 'lesson'
          OR (
              pl.is_active IS TRUE
              AND pl.superseded_by IS NULL
              AND NOT public.fn_dli_proxy_lesson_invalid(
                  pl.condition,
                  pl.lesson
              )
          )
      )
    ORDER BY e.embedding <=> query_embedding
    LIMIT p_top_k;
END;
$$;

COMMENT ON FUNCTION public.fn_search_embeddings(vector, integer, text[]) IS
'Top-K semantic retrieval. Active lesson results also pass the DLI proxy/correction invalidation guard.';

-- This is the only view allowed to expose the old numeric proxy.  Its name and
-- evidence_class make the invalidity explicit; product consumers use
-- v_dli_current/v_dli_daily instead.
CREATE OR REPLACE VIEW public.v_dli_forensic_history AS
SELECT
    c.ts,
    COALESCE(c.greenhouse_id, 'vallery') AS greenhouse_id,
    c.dli_today AS forensic_proxy_dli_mol_m2_day,
    'forensic_invalid_proxy'::text AS evidence_class,
    COALESCE(v.availability, 'unavailable') AS availability,
    COALESCE(v.unavailable_reason, 'validity_contract_missing') AS unavailable_reason,
    COALESCE(v.provenance, 'unknown_unvalidated_source') AS provenance,
    COALESCE(v.validity_revision, 'missing') AS validity_revision,
    v.valid_from,
    v.valid_to
FROM public.climate c
LEFT JOIN LATERAL public.fn_dli_validity(
    c.ts,
    COALESCE(c.greenhouse_id, 'vallery')
) v ON true
WHERE c.dli_today IS NOT NULL;

COMMENT ON VIEW public.v_dli_forensic_history IS
'Forensic-only legacy DLI proxy history. Numeric values came from an invalid interior sensor/exterior proxy/fixture estimate and must never be used as measured crop DLI.';

CREATE OR REPLACE VIEW public.v_dli_current AS
WITH latest AS (
    SELECT DISTINCT ON (COALESCE(c.greenhouse_id, 'vallery'))
        c.ts,
        COALESCE(c.greenhouse_id, 'vallery') AS greenhouse_id,
        c.dli_today AS forensic_proxy_dli_mol_m2_day
    FROM public.climate c
    ORDER BY COALESCE(c.greenhouse_id, 'vallery'), c.ts DESC
)
SELECT
    l.ts,
    l.greenhouse_id,
    NULL::double precision AS crop_dli_mol_m2_day,
    'unavailable'::text AS availability,
    CASE
        WHEN public.fn_dli_source_invalid_reason(
            l.forensic_proxy_dli_mol_m2_day
        ) IS NOT NULL
        THEN public.fn_dli_source_invalid_reason(
            l.forensic_proxy_dli_mol_m2_day
        )
        ELSE COALESCE(v.unavailable_reason, 'validity_contract_missing')
    END::text AS unavailable_reason,
    COALESCE(v.provenance, 'unknown_unvalidated_source') AS provenance,
    COALESCE(v.validity_revision, 'missing') AS validity_revision,
    v.valid_from,
    v.valid_to,
    (l.forensic_proxy_dli_mol_m2_day IS NOT NULL) AS forensic_proxy_present
FROM latest l
LEFT JOIN LATERAL public.fn_dli_validity(l.ts, l.greenhouse_id) v ON true;

COMMENT ON VIEW public.v_dli_current IS
'Current interior crop DLI product contract. Migration 195 is categorically unavailable and always emits NULL. Invalid, non-finite, negative, missing, and out-of-range source readings receive explicit reasons; a later reviewed activation migration owns source completeness and calibration.';

CREATE OR REPLACE VIEW public.v_dli_daily AS
WITH day_bounds AS (
    SELECT
        ds.date,
        COALESCE(ds.greenhouse_id, 'vallery') AS greenhouse_id,
        ds.dli_final AS forensic_proxy_dli_mol_m2_day,
        ds.date::timestamp AT TIME ZONE 'America/Denver' AS day_start,
        (ds.date + 1)::timestamp AT TIME ZONE 'America/Denver' AS day_end
    FROM public.daily_summary ds
    WHERE ds.date IS NOT NULL
)
SELECT
    d.date,
    d.greenhouse_id,
    NULL::double precision AS crop_dli_mol_m2_day,
    'unavailable'::text AS availability,
    CASE
        WHEN d.day_end > now() THEN 'source_day_incomplete'
        WHEN public.fn_dli_source_invalid_reason(
            d.forensic_proxy_dli_mol_m2_day
        ) IS NOT NULL
        THEN public.fn_dli_source_invalid_reason(
            d.forensic_proxy_dli_mol_m2_day
        )
        ELSE COALESCE(v.unavailable_reason, 'validity_contract_missing')
    END::text AS unavailable_reason,
    COALESCE(v.provenance, 'unknown_unvalidated_source') AS provenance,
    COALESCE(v.validity_revision, 'missing') AS validity_revision,
    v.valid_from,
    v.valid_to,
    (d.forensic_proxy_dli_mol_m2_day IS NOT NULL) AS forensic_proxy_present
FROM day_bounds d
LEFT JOIN LATERAL public.fn_dli_validity(
    d.day_start + interval '12 hours',
    d.greenhouse_id
) v ON true;

COMMENT ON VIEW public.v_dli_daily IS
'Daily interior crop DLI product contract. Migration 195 is categorically unavailable and never emits a numeric value. A later reviewed sensor-activation migration must define source revision, cadence/completeness, calibration, and validity rules.';

COMMENT ON COLUMN public.climate.dli_today IS
'LEGACY FORENSIC PROXY ONLY while dli-validity-v1 is unavailable. Built from a broken interior sensor/exterior proxy plus fixture estimate; use v_dli_current or v_dli_daily for product truth.';
COMMENT ON COLUMN public.daily_summary.dli_final IS
'LEGACY FORENSIC DAILY PROXY ONLY while dli-validity-v1 is unavailable. Preserved for audit; use v_dli_daily.crop_dli_mol_m2_day for product truth.';

COMMENT ON VIEW public.v_climate_latest IS
'Raw/latest climate transport view. dli_today is the explicitly invalid legacy proxy described by the source-column comment; product consumers must use v_dli_current.';
COMMENT ON MATERIALIZED VIEW public.v_climate_merged IS
'Raw merged climate transport history. dli_today is the explicitly invalid legacy proxy described by the source-column comment; product consumers must use v_dli_daily.';
COMMENT ON VIEW public.v_greenhouse_state IS
'Live rolling 14-day greenhouse time series. One row per sensor reading with equipment, setpoints, compliance, mode, dispatcher-owned targets, and signed target deltas. dli_today is preserved as a forensic legacy proxy only; product consumers must use v_dli_current/v_dli_daily.';

-- The broken interior DLI entity still emits a legacy accumulator, but it is
-- not an active/required physical sensor. Match rows by their table/column
-- mapping rather than one assumed sensor_id so migrated/renamed registries are
-- also corrected. v_sensor_staleness already filters active=true, and required
-- coverage filters is_required=true, so alert-facing consumers stop treating
-- the invalid accumulator as a healthy or stale physical sensor.
UPDATE public.sensor_registry
SET active = false,
    notes = CASE
        WHEN COALESCE(notes, '') LIKE '%migration_195: broken interior DLI sensor unavailable%'
        THEN notes
        ELSE concat_ws(
            '; ',
            NULLIF(notes, ''),
            'migration_195: broken interior DLI sensor unavailable'
        )
    END,
    updated_at = now()
WHERE source_table = 'climate'
  AND source_column = 'dli_today'
  AND (
      active IS DISTINCT FROM false
      OR COALESCE(notes, '') NOT LIKE
          '%migration_195: broken interior DLI sensor unavailable%'
  );

UPDATE public.greenhouse_sensor_config
SET is_required = false,
    description = CASE
        WHEN COALESCE(description, '') LIKE '%migration_195: unavailable until replacement%'
        THEN description
        ELSE concat_ws(
            '; ',
            NULLIF(description, ''),
            'migration_195: unavailable until replacement'
        )
    END
WHERE target_table = 'climate'
  AND target_column = 'dli_today'
  AND (
      is_required IS DISTINCT FROM false
      OR COALESCE(description, '') NOT LIKE
          '%migration_195: unavailable until replacement%'
  );

CREATE OR REPLACE VIEW public.v_estimated_dli AS
WITH readings AS (
    SELECT
        (date_trunc(
            'day',
            c.ts AT TIME ZONE 'America/Denver'
        ))::date AS date,
        COALESCE(
            EXTRACT(epoch FROM (
                lead(c.ts) OVER (
                    PARTITION BY (
                        date_trunc(
                            'day',
                            c.ts AT TIME ZONE 'America/Denver'
                        )
                    )::date
                    ORDER BY c.ts
                ) - c.ts
            )),
            300
        ) AS dt_sec
    FROM public.climate c
    WHERE c.outdoor_lux > 0
      AND c.solar_azimuth_deg IS NOT NULL
      AND c.solar_altitude_deg > 0
)
SELECT
    r.date,
    NULL::numeric AS est_natural_dli,
    count(*) AS readings,
    'unavailable'::text AS availability,
    'interior_light_sensor_broken'::text AS unavailable_reason,
    'outdoor_lux_glazing_model_not_interior_crop_dli'::text AS provenance,
    'dli-validity-v1'::text AS validity_revision,
    '2024-01-01 00:00:00+00'::timestamptz AS valid_from,
    NULL::timestamptz AS valid_to
FROM readings r
WHERE r.dt_sec > 0
  AND r.dt_sec < 900
GROUP BY r.date
ORDER BY r.date;

COMMENT ON VIEW public.v_estimated_dli IS
'Deprecated compatibility view. est_natural_dli is always NULL because outdoor lux and glazing transmission are not measured interior crop DLI; readings remains an outdoor-source diagnostic count.';

-- Neutralize older reporting surfaces that directly aggregate the forensic
-- daily_summary proxy.  Their column names/types remain stable for callers,
-- but no numeric DLI or DLI-derived efficiency claim escapes the validity
-- contract.  Product consumers needing reason/provenance join v_dli_daily.
CREATE OR REPLACE VIEW public.v_weekly_summary AS
SELECT
    date_trunc('week', date)::date AS week_start,
    (date_trunc('week', date) + interval '6 days')::date AS week_end,
    count(*) AS days,
    round(avg(temp_avg)::numeric, 1) AS temp_avg,
    round(min(temp_min)::numeric, 1) AS temp_min,
    round(max(temp_max)::numeric, 1) AS temp_max,
    round(avg(rh_avg)::numeric, 1) AS rh_avg,
    round(min(rh_min)::numeric, 1) AS rh_min,
    round(max(rh_max)::numeric, 1) AS rh_max,
    round(avg(vpd_avg)::numeric, 2) AS vpd_avg,
    round(min(vpd_min)::numeric, 2) AS vpd_min,
    round(max(vpd_max)::numeric, 2) AS vpd_max,
    NULL::numeric AS dli_avg,
    round(avg(co2_avg)::numeric, 0) AS co2_avg,
    round(min(outdoor_temp_min)::numeric, 1) AS outdoor_temp_min,
    round(max(outdoor_temp_max)::numeric, 1) AS outdoor_temp_max,
    round(sum(COALESCE(stress_hours_heat, 0))::numeric, 1) AS stress_hours_heat,
    round(sum(COALESCE(stress_hours_cold, 0))::numeric, 1) AS stress_hours_cold,
    round(sum(COALESCE(stress_hours_vpd_high, 0))::numeric, 1) AS stress_hours_vpd_high,
    round(sum(COALESCE(stress_hours_vpd_low, 0))::numeric, 1) AS stress_hours_vpd_low,
    round(sum(COALESCE(water_used_gal, 0))::numeric, 0) AS total_water_gal,
    round(sum(COALESCE(mister_water_gal, 0))::numeric, 0) AS mister_water_gal,
    round(sum(COALESCE(kwh_total, kwh_estimated, 0))::numeric, 1) AS kwh_total,
    round(sum(COALESCE(therms_estimated, 0))::numeric, 2) AS therms_total,
    round(max(COALESCE(peak_kw, 0))::numeric, 2) AS peak_kw,
    round(sum(COALESCE(cost_electric, 0))::numeric, 2) AS cost_electric,
    round(sum(COALESCE(cost_gas, 0))::numeric, 2) AS cost_gas,
    round(sum(COALESCE(cost_water, 0))::numeric, 2) AS cost_water,
    round(sum(COALESCE(cost_total, 0))::numeric, 2) AS total_cost,
    round(sum(COALESCE(runtime_heat1_min, 0))::numeric / 60, 1) AS runtime_heat1_h,
    round(sum(COALESCE(runtime_heat2_min, 0))::numeric / 60, 1) AS runtime_heat2_h,
    round(sum(COALESCE(runtime_fan1_min + runtime_fan2_min, 0))::numeric / 60, 1) AS runtime_fans_h,
    round(sum(COALESCE(runtime_fog_min, 0))::numeric / 60, 1) AS runtime_fog_h,
    round(sum(COALESCE(runtime_vent_min, 0))::numeric / 60, 1) AS runtime_vent_h,
    round(sum(COALESCE(runtime_grow_light_min, 0))::numeric / 60, 1) AS runtime_grow_light_h,
    round(sum(COALESCE(runtime_mister_south_h + runtime_mister_west_h + runtime_mister_center_h, 0))::numeric, 1) AS runtime_misters_h,
    sum(COALESCE(cycles_heat1, 0) + COALESCE(cycles_heat2, 0)) AS cycles_heat,
    sum(COALESCE(cycles_fan1, 0) + COALESCE(cycles_fan2, 0)) AS cycles_fans,
    sum(COALESCE(cycles_fog, 0)) AS cycles_fog,
    sum(COALESCE(cycles_vent, 0)) AS cycles_vent
FROM public.daily_summary
WHERE temp_avg IS NOT NULL
GROUP BY date_trunc('week', date)
ORDER BY week_start;

COMMENT ON VIEW public.v_weekly_summary IS
'Weekly reporting rollup. dli_avg is intentionally NULL while interior crop DLI is unavailable; use v_dli_daily for validity provenance.';

CREATE OR REPLACE VIEW public.v_monthly_summary AS
SELECT
    date_trunc('month', date)::date AS month_start,
    count(*) AS days,
    round(avg(temp_avg)::numeric, 1) AS temp_avg,
    round(min(temp_min)::numeric, 1) AS temp_min,
    round(max(temp_max)::numeric, 1) AS temp_max,
    round(avg(rh_avg)::numeric, 1) AS rh_avg,
    round(min(rh_min)::numeric, 1) AS rh_min,
    round(max(rh_max)::numeric, 1) AS rh_max,
    round(avg(vpd_avg)::numeric, 2) AS vpd_avg,
    round(min(vpd_min)::numeric, 2) AS vpd_min,
    round(max(vpd_max)::numeric, 2) AS vpd_max,
    NULL::numeric AS dli_avg,
    round(avg(co2_avg)::numeric, 0) AS co2_avg,
    round(min(outdoor_temp_min)::numeric, 1) AS outdoor_temp_min,
    round(max(outdoor_temp_max)::numeric, 1) AS outdoor_temp_max,
    round(sum(COALESCE(stress_hours_heat, 0))::numeric, 1) AS stress_hours_heat,
    round(sum(COALESCE(stress_hours_cold, 0))::numeric, 1) AS stress_hours_cold,
    round(sum(COALESCE(stress_hours_vpd_high, 0))::numeric, 1) AS stress_hours_vpd_high,
    round(sum(COALESCE(stress_hours_vpd_low, 0))::numeric, 1) AS stress_hours_vpd_low,
    round(sum(COALESCE(water_used_gal, 0))::numeric, 0) AS total_water_gal,
    round(sum(COALESCE(mister_water_gal, 0))::numeric, 0) AS mister_water_gal,
    round(sum(COALESCE(kwh_total, kwh_estimated, 0))::numeric, 1) AS kwh_total,
    round(sum(COALESCE(therms_estimated, 0))::numeric, 2) AS therms_total,
    round(sum(COALESCE(cost_electric, 0))::numeric, 2) AS cost_electric,
    round(sum(COALESCE(cost_gas, 0))::numeric, 2) AS cost_gas,
    round(sum(COALESCE(cost_water, 0))::numeric, 2) AS cost_water,
    round(sum(COALESCE(cost_total, 0))::numeric, 2) AS total_cost,
    round(sum(COALESCE(runtime_heat1_min, 0))::numeric / 60, 1) AS runtime_heat1_h,
    round(sum(COALESCE(runtime_heat2_min, 0))::numeric / 60, 1) AS runtime_heat2_h,
    round(sum(COALESCE(runtime_fan1_min + runtime_fan2_min, 0))::numeric / 60, 1) AS runtime_fans_h,
    round(sum(COALESCE(runtime_fog_min, 0))::numeric / 60, 1) AS runtime_fog_h,
    round(sum(COALESCE(runtime_vent_min, 0))::numeric / 60, 1) AS runtime_vent_h,
    round(sum(COALESCE(runtime_grow_light_min, 0))::numeric / 60, 1) AS runtime_grow_light_h,
    round(sum(COALESCE(runtime_mister_south_h + runtime_mister_west_h + runtime_mister_center_h, 0))::numeric, 1) AS runtime_misters_h,
    sum(COALESCE(cycles_heat1, 0) + COALESCE(cycles_heat2, 0)) AS cycles_heat,
    sum(COALESCE(cycles_fan1, 0) + COALESCE(cycles_fan2, 0)) AS cycles_fans,
    sum(COALESCE(cycles_fog, 0)) AS cycles_fog,
    sum(COALESCE(cycles_vent, 0)) AS cycles_vent
FROM public.daily_summary
WHERE temp_avg IS NOT NULL
GROUP BY date_trunc('month', date)
ORDER BY month_start;

COMMENT ON VIEW public.v_monthly_summary IS
'Monthly reporting rollup. dli_avg is intentionally NULL while interior crop DLI is unavailable; use v_dli_daily for validity provenance.';

CREATE OR REPLACE FUNCTION public.fn_period_summary(start_date date, end_date date)
RETURNS TABLE(
    days bigint,
    temp_avg numeric, temp_min numeric, temp_max numeric,
    rh_avg numeric, vpd_avg numeric, vpd_min numeric, vpd_max numeric,
    dli_avg numeric, co2_avg numeric,
    outdoor_temp_min numeric, outdoor_temp_max numeric,
    stress_hours_heat numeric, stress_hours_cold numeric,
    stress_hours_vpd_high numeric, stress_hours_vpd_low numeric,
    total_water_gal numeric, mister_water_gal numeric,
    kwh_total numeric, therms_total numeric,
    cost_electric numeric, cost_gas numeric, cost_water numeric, total_cost numeric,
    runtime_heat1_h numeric, runtime_heat2_h numeric, runtime_fans_h numeric,
    runtime_fog_h numeric, runtime_vent_h numeric, runtime_grow_light_h numeric,
    runtime_misters_h numeric
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        count(*)::bigint,
        round(avg(ds.temp_avg)::numeric, 1),
        round(min(ds.temp_min)::numeric, 1),
        round(max(ds.temp_max)::numeric, 1),
        round(avg(ds.rh_avg)::numeric, 1),
        round(avg(ds.vpd_avg)::numeric, 2),
        round(min(ds.vpd_min)::numeric, 2),
        round(max(ds.vpd_max)::numeric, 2),
        NULL::numeric,
        round(avg(ds.co2_avg)::numeric, 0),
        round(min(ds.outdoor_temp_min)::numeric, 1),
        round(max(ds.outdoor_temp_max)::numeric, 1),
        round(sum(COALESCE(ds.stress_hours_heat, 0))::numeric, 1),
        round(sum(COALESCE(ds.stress_hours_cold, 0))::numeric, 1),
        round(sum(COALESCE(ds.stress_hours_vpd_high, 0))::numeric, 1),
        round(sum(COALESCE(ds.stress_hours_vpd_low, 0))::numeric, 1),
        round(sum(COALESCE(ds.water_used_gal, 0))::numeric, 0),
        round(sum(COALESCE(ds.mister_water_gal, 0))::numeric, 0),
        round(sum(COALESCE(ds.kwh_estimated, 0))::numeric, 1),
        round(sum(COALESCE(ds.therms_estimated, 0))::numeric, 2),
        round(sum(COALESCE(ds.cost_electric, 0))::numeric, 2),
        round(sum(COALESCE(ds.cost_gas, 0))::numeric, 2),
        round(sum(COALESCE(ds.cost_water, 0))::numeric, 2),
        round(sum(COALESCE(ds.cost_total, 0))::numeric, 2),
        round(sum(COALESCE(ds.runtime_heat1_min, 0))::numeric / 60, 1),
        round(sum(COALESCE(ds.runtime_heat2_min, 0))::numeric / 60, 1),
        round(sum(COALESCE(ds.runtime_fan1_min + ds.runtime_fan2_min, 0))::numeric / 60, 1),
        round(sum(COALESCE(ds.runtime_fog_min, 0))::numeric / 60, 1),
        round(sum(COALESCE(ds.runtime_vent_min, 0))::numeric / 60, 1),
        round(sum(COALESCE(ds.runtime_grow_light_min, 0))::numeric / 60, 1),
        round(sum(COALESCE(ds.runtime_mister_south_h + ds.runtime_mister_west_h + ds.runtime_mister_center_h, 0))::numeric, 1)
    FROM public.daily_summary ds
    WHERE ds.date >= start_date
      AND ds.date <= end_date
      AND ds.temp_avg IS NOT NULL
$$;

COMMENT ON FUNCTION public.fn_period_summary(date, date) IS
'Arbitrary-period reporting summary. dli_avg is intentionally NULL while interior crop DLI is unavailable; use v_dli_daily for validity provenance.';

CREATE OR REPLACE VIEW public.v_harvest_story AS
SELECT
    h.id,
    h.ts,
    (h.ts AT TIME ZONE 'America/Denver')::date AS date,
    h.greenhouse_id,
    h.crop_id,
    c.name AS crop_name,
    h.position_id,
    h.zone,
    COALESCE(h.salable_weight_kg, h.weight_kg) AS salable_weight_kg,
    h.cull_weight_kg,
    h.unit_count,
    h.quality_grade,
    h.quality_reason,
    h.destination,
    h.unit_price,
    COALESCE(h.revenue, h.unit_price * h.unit_count) AS revenue,
    NULL::double precision AS dli_final,
    ds.water_used_gal,
    ds.kwh_total,
    NULL::double precision AS kg_per_mol_dli,
    CASE WHEN ds.water_used_gal > 0
      THEN COALESCE(h.salable_weight_kg, h.weight_kg) / ds.water_used_gal
    END AS kg_per_gal,
    CASE WHEN ds.kwh_total > 0
      THEN COALESCE(h.salable_weight_kg, h.weight_kg) / ds.kwh_total
    END AS kg_per_kwh
FROM public.harvests h
LEFT JOIN public.crops c ON c.id = h.crop_id
LEFT JOIN public.daily_summary ds
  ON ds.date = (h.ts AT TIME ZONE 'America/Denver')::date;

COMMENT ON VIEW public.v_harvest_story IS
'Harvest outcome evidence. DLI and kg_per_mol_dli are intentionally NULL while interior crop DLI is unavailable; water and energy evidence remain independent.';

CREATE OR REPLACE VIEW public.v_grower_economics_story AS
WITH harvest_daily AS (
    SELECT
        (ts AT TIME ZONE 'America/Denver')::date AS date,
        sum(COALESCE(salable_weight_kg, weight_kg, 0)) AS salable_kg,
        sum(COALESCE(cull_weight_kg, 0)) AS cull_kg,
        sum(COALESCE(revenue, unit_price * unit_count, 0)) AS revenue
    FROM public.harvests
    GROUP BY 1
)
SELECT
    ds.date,
    hd.salable_kg,
    hd.cull_kg,
    hd.revenue,
    NULL::double precision AS dli_final,
    ds.water_used_gal,
    COALESCE(ds.kwh_total, ds.kwh_estimated) AS kwh,
    ds.therms_estimated,
    ds.cost_total,
    ds.stress_hours_heat + ds.stress_hours_vpd_high
      + ds.stress_hours_cold + ds.stress_hours_vpd_low AS stress_hours,
    NULL::double precision AS kg_per_mol_dli,
    CASE WHEN ds.water_used_gal > 0 THEN hd.salable_kg / ds.water_used_gal END AS kg_per_gal,
    CASE WHEN COALESCE(ds.kwh_total, ds.kwh_estimated) > 0
      THEN hd.salable_kg / COALESCE(ds.kwh_total, ds.kwh_estimated)
    END AS kg_per_kwh,
    CASE WHEN ds.cost_total > 0 THEN hd.revenue / ds.cost_total END AS revenue_per_cost_dollar
FROM public.daily_summary ds
LEFT JOIN harvest_daily hd USING (date)
WHERE ds.date IS NOT NULL
ORDER BY ds.date DESC;

COMMENT ON VIEW public.v_grower_economics_story IS
'Grower economics by local day. DLI and kg_per_mol_dli are intentionally NULL while interior crop DLI is unavailable; resource and cost fields remain independently governed.';

CREATE OR REPLACE FUNCTION public.fn_forecast_dli(
    target_date date DEFAULT CURRENT_DATE + 1
)
RETURNS TABLE(
    predicted_dli numeric,
    gl_hours_needed numeric,
    recommended_gl_start integer,
    recommended_gl_end integer
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        NULL::numeric,
        NULL::numeric,
        NULL::integer,
        NULL::integer
$$;

COMMENT ON FUNCTION public.fn_forecast_dli(date) IS
'Deprecated compatibility function. All values are NULL because outdoor forecast irradiance is not measured interior crop DLI; qualified-light-minute control remains independent.';

CREATE OR REPLACE VIEW public.v_greenhouse_now AS
SELECT
    c.ts,
    round(c.temp_avg::numeric, 1) AS temp_avg,
    round(c.temp_north::numeric, 1) AS temp_north,
    round(c.temp_south::numeric, 1) AS temp_south,
    round(c.temp_east::numeric, 1) AS temp_east,
    round(c.temp_west::numeric, 1) AS temp_west,
    round(c.rh_avg::numeric, 1) AS rh_avg,
    round(c.vpd_avg::numeric, 2) AS vpd_avg,
    round(c.co2_ppm::numeric, 0) AS co2_ppm,
    round(c.lux::numeric, 0) AS lux,
    round(dc.crop_dli_mol_m2_day::numeric, 2) AS dli_today,
    o.outdoor_temp_f,
    o.outdoor_rh_pct,
    o.wind_mph,
    o.pressure_hpa,
    round(c.mister_water_today::numeric, 1) AS mister_water_today,
    h.hydro_ph,
    h.hydro_ec_us_cm,
    h.hydro_tds_ppm,
    h.hydro_water_temp_f,
    d.wifi_rssi,
    round(d.heap_bytes::numeric, 0) AS heap_kb,
    round(d.uptime_s::numeric, 0) AS uptime_s,
    (
        SELECT s.value
        FROM public.system_state s
        WHERE s.entity = 'greenhouse_state'
        ORDER BY s.ts DESC
        LIMIT 1
    ) AS state,
    (
        SELECT s.value
        FROM public.system_state s
        WHERE s.entity = 'lead_fan'
        ORDER BY s.ts DESC
        LIMIT 1
    ) AS lead_fan,
    public.fn_system_health() AS health_score,
    (
        SELECT count(*)
        FROM public.alert_log a
        WHERE a.disposition = 'open'
    ) AS open_alerts,
    cost.cost_electric,
    cost.cost_gas,
    cost.cost_water,
    cost.cost_total,
    dc.availability AS dli_availability,
    dc.unavailable_reason AS dli_unavailable_reason,
    dc.provenance AS dli_provenance,
    dc.validity_revision AS dli_validity_revision,
    dc.valid_from AS dli_valid_from,
    dc.valid_to AS dli_valid_to
FROM public.climate c
LEFT JOIN LATERAL (
    SELECT d0.wifi_rssi, d0.heap_bytes, d0.uptime_s
    FROM public.diagnostics d0
    ORDER BY d0.ts DESC
    LIMIT 1
) d ON true
LEFT JOIN LATERAL (
    SELECT
        round(c0.outdoor_temp_f::numeric, 1) AS outdoor_temp_f,
        round(c0.outdoor_rh_pct::numeric, 0) AS outdoor_rh_pct,
        round(c0.wind_speed_mph::numeric, 1) AS wind_mph,
        round(c0.pressure_hpa::numeric, 1) AS pressure_hpa
    FROM public.climate c0
    WHERE c0.outdoor_temp_f IS NOT NULL
      AND c0.ts > now() - interval '30 minutes'
    ORDER BY c0.ts DESC
    LIMIT 1
) o ON true
LEFT JOIN LATERAL (
    SELECT
        round(c1.hydro_ph::numeric, 1) AS hydro_ph,
        round(c1.hydro_ec_us_cm::numeric, 0) AS hydro_ec_us_cm,
        round(c1.hydro_tds_ppm::numeric, 0) AS hydro_tds_ppm,
        round(c1.hydro_water_temp_f::numeric, 1) AS hydro_water_temp_f
    FROM public.climate c1
    WHERE c1.hydro_ph IS NOT NULL
      AND c1.ts > now() - interval '30 minutes'
    ORDER BY c1.ts DESC
    LIMIT 1
) h ON true
CROSS JOIN public.v_cost_today cost
LEFT JOIN public.v_dli_current dc
  ON dc.greenhouse_id = COALESCE(c.greenhouse_id, 'vallery')
WHERE c.temp_avg IS NOT NULL
ORDER BY c.ts DESC
LIMIT 1;

COMMENT ON VIEW public.v_greenhouse_now IS
'Current greenhouse product view. dli_today is nullable and unavailable metadata is explicit while the interior sensor is invalid.';

CREATE OR REPLACE VIEW public.v_estimated_plant_dli AS
SELECT
    ds.date,
    NULL::numeric AS sensor_dli,
    NULL::numeric AS corrected_solar_dli,
    round((COALESCE(ds.runtime_grow_light_min, 0) / 60.0)::numeric, 1)
        AS grow_light_hours,
    NULL::numeric AS grow_light_dli,
    NULL::numeric AS estimated_plant_dli,
    'UNAVAILABLE'::text AS dli_status,
    d.availability,
    d.unavailable_reason,
    d.provenance,
    d.validity_revision,
    d.valid_from,
    d.valid_to
FROM public.daily_summary ds
LEFT JOIN public.v_dli_daily d
  ON d.date = ds.date
 AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery')
ORDER BY ds.date DESC;

COMMENT ON VIEW public.v_estimated_plant_dli IS
'Compatibility view for legacy consumers. All DLI scalars are NULL while the interior sensor is invalid; grow-light runtime remains separately observable and availability provenance is explicit.';

CREATE OR REPLACE VIEW public.v_lighting_daily AS
WITH runtime AS (
    SELECT day, equipment, on_minutes, cycles
    FROM public.v_equipment_runtime_daily
    WHERE equipment IN ('grow_light_main', 'grow_light_grow')
)
SELECT
    ds.date,
    (ds.date + time '12:00')::timestamptz AS ts,
    d.crop_dli_mol_m2_day AS sensor_dli,
    ds.runtime_grow_light_min / 60.0 AS grow_light_hours,
    COALESCE(main_rt.on_minutes, 0.0) / 60.0 AS main_light_hours,
    COALESCE(grow_rt.on_minutes, 0.0) / 60.0 AS grow_light_circuit_hours,
    COALESCE(main_rt.cycles, 0) AS main_light_cycles,
    COALESCE(grow_rt.cycles, 0) AS grow_light_circuit_cycles,
    p.target_dli,
    p.target_light_hours,
    p.sunrise_hour,
    p.natural_sunset_hour,
    p.cutoff_hour,
    p.max_crop_name,
    d.availability AS dli_availability,
    d.unavailable_reason AS dli_unavailable_reason,
    d.provenance AS dli_provenance,
    d.validity_revision AS dli_validity_revision,
    d.valid_from AS dli_valid_from,
    d.valid_to AS dli_valid_to
FROM public.daily_summary ds
CROSS JOIN LATERAL public.fn_lighting_policy(
    (ds.date + time '12:00')::timestamptz,
    COALESCE(ds.greenhouse_id, 'vallery')
) p
LEFT JOIN runtime main_rt
  ON main_rt.day = ds.date AND main_rt.equipment = 'grow_light_main'
LEFT JOIN runtime grow_rt
  ON grow_rt.day = ds.date AND grow_rt.equipment = 'grow_light_grow'
LEFT JOIN public.v_dli_daily d
  ON d.date = ds.date
 AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery');

COMMENT ON VIEW public.v_lighting_daily IS
'DLI-independent lighting runtime and crop target context. Measured sensor_dli is NULL with explicit validity metadata while the interior sensor is invalid.';

-- Product KPI retains its established column order and score semantics.  The
-- old dli column remains for compatibility but is NULL; appended fields carry
-- the reason/provenance/valid interval.
CREATE OR REPLACE VIEW public.v_daily_kpi AS
WITH evidence AS (
    SELECT
        d.*,
        w.quality_filtered_meter_gal,
        w.climate_wetting_gal,
        COALESCE(w.available_for_scoring, false) AS water_ok,
        e.modeled_kwh,
        COALESCE(e.available_for_scoring, false) AS energy_ok,
        dl.crop_dli_mol_m2_day,
        dl.availability AS dli_availability,
        dl.unavailable_reason AS dli_unavailable_reason,
        dl.provenance AS dli_provenance,
        dl.validity_revision AS dli_validity_revision,
        dl.valid_from AS dli_valid_from,
        dl.valid_to AS dli_valid_to
    FROM public.daily_summary d
    LEFT JOIN public.v_water_attribution_daily w
      ON w.date = d.date AND w.greenhouse_id = d.greenhouse_id
    LEFT JOIN public.v_runtime_energy_daily e
      ON e.date = d.date AND e.greenhouse_id = d.greenhouse_id
    LEFT JOIN public.v_dli_daily dl
      ON dl.date = d.date
     AND dl.greenhouse_id = COALESCE(d.greenhouse_id, 'vallery')
    WHERE d.date IS NOT NULL
), normalized AS (
    SELECT
        e.*,
        COALESCE(e.compliance_v2_attributable_pct, e.compliance_pct, 0)
            AS score_compliance,
        e.water_ok AND e.energy_ok AND e.cost_total IS NOT NULL AS resource_ok
    FROM evidence e
)
SELECT
    date,
    round(score_compliance::numeric, 1) AS compliance_pct,
    round(COALESCE(graded_temp_compliance_pct, temp_compliance_pct, 0)::numeric, 1)
        AS temp_compliance_pct,
    round(COALESCE(graded_vpd_compliance_pct, vpd_compliance_pct, 0)::numeric, 1)
        AS vpd_compliance_pct,
    round(COALESCE(graded_stress_hours_heat, stress_hours_heat, 0)::numeric, 2)
        AS heat_stress_h,
    round(COALESCE(graded_stress_hours_cold, stress_hours_cold, 0)::numeric, 2)
        AS cold_stress_h,
    round(COALESCE(graded_stress_hours_vpd_high, stress_hours_vpd_high, 0)::numeric, 2)
        AS vpd_high_stress_h,
    round(COALESCE(graded_stress_hours_vpd_low, stress_hours_vpd_low, 0)::numeric, 2)
        AS vpd_low_stress_h,
    round((
        COALESCE(graded_stress_hours_heat, stress_hours_heat, 0)
        + COALESCE(graded_stress_hours_cold, stress_hours_cold, 0)
        + COALESCE(graded_stress_hours_vpd_high, stress_hours_vpd_high, 0)
        + COALESCE(graded_stress_hours_vpd_low, stress_hours_vpd_low, 0)
    )::numeric, 2) AS total_stress_h,
    CASE WHEN energy_ok THEN round(modeled_kwh::numeric, 2) END AS kwh,
    CASE WHEN resource_ok
      THEN round(COALESCE(therms_estimated, gas_used_therms)::numeric, 3)
    END AS therms,
    CASE WHEN water_ok THEN round(quality_filtered_meter_gal::numeric, 0) END AS water_gal,
    CASE WHEN water_ok THEN round(climate_wetting_gal::numeric, 0) END AS mister_water_gal,
    CASE WHEN energy_ok THEN round(cost_electric::numeric, 2) END AS cost_electric,
    CASE WHEN resource_ok THEN round(cost_gas::numeric, 2) END AS cost_gas,
    CASE WHEN water_ok THEN round(cost_water::numeric, 2) END AS cost_water,
    CASE WHEN resource_ok THEN round(cost_total::numeric, 2) END AS cost_total,
    round(temp_min::numeric, 1) AS temp_min,
    round(temp_max::numeric, 1) AS temp_max,
    round(temp_avg::numeric, 1) AS temp_avg,
    round(vpd_min::numeric, 2) AS vpd_min,
    round(vpd_max::numeric, 2) AS vpd_max,
    round(vpd_avg::numeric, 2) AS vpd_avg,
    round(crop_dli_mol_m2_day::numeric, 1) AS dli,
    round(min_dp_margin_f::numeric, 1) AS dp_margin_min_f,
    round(COALESCE(dp_risk_hours, 0)::numeric, 1) AS dp_risk_hours,
    round((CASE
        WHEN resource_ok THEN score_compliance / 100.0 * 80
          + GREATEST(0, 1.0 - LEAST(cost_total / 15.0, 1.0)) * 20
        ELSE score_compliance
    END)::numeric, 1) AS planner_score,
    CASE WHEN resource_ok THEN 20::numeric ELSE 0::numeric END
        AS planner_score_resource_weight_pct,
    resource_ok AS resource_terms_available,
    dli_availability,
    dli_unavailable_reason,
    dli_provenance,
    dli_validity_revision,
    dli_valid_from,
    dli_valid_to
FROM normalized
ORDER BY date;

COMMENT ON VIEW public.v_daily_kpi IS
'Daily planner KPI with provenance-gated resources and availability-bearing crop DLI. Invalid interior-light evidence remains NULL and has zero score influence.';

CREATE OR REPLACE VIEW public.v_iris_planning_context AS
SELECT
    now() AS query_ts,
    (
        SELECT json_build_object(
            'temp_avg', round(avg(c.temp_avg)::numeric, 1),
            'vpd_avg', round(avg(c.vpd_avg)::numeric, 2),
            'rh_avg', round(avg(c.rh_avg)::numeric, 1),
            'outdoor_temp_f', round(avg(c.outdoor_temp_f)::numeric, 1),
            'dli', (
                SELECT json_build_object(
                    'value_mol_m2_day', dc.crop_dli_mol_m2_day,
                    'availability', dc.availability,
                    'unavailable_reason', dc.unavailable_reason,
                    'provenance', dc.provenance,
                    'validity_revision', dc.validity_revision,
                    'valid_from', dc.valid_from,
                    'valid_to', dc.valid_to
                )
                FROM public.v_dli_current dc
                WHERE dc.greenhouse_id = 'vallery'
                LIMIT 1
            ),
            'co2_ppm', round(avg(c.co2_ppm)::numeric, 0)
        )
        FROM public.climate c
        WHERE c.ts >= now() - interval '1 hour'
          AND c.temp_avg IS NOT NULL
    ) AS current_conditions,
    (
        SELECT json_build_object(
            'north', round(avg(c.temp_north)::numeric, 1),
            'south', round(avg(c.temp_south)::numeric, 1),
            'east', round(avg(c.temp_east)::numeric, 1),
            'west', round(avg(c.temp_west)::numeric, 1)
        )
        FROM public.climate c
        WHERE c.ts >= now() - interval '1 hour'
          AND c.temp_avg IS NOT NULL
    ) AS zone_context,
    (
        SELECT json_build_object(
            'date', ds.date,
            'cost_total', ds.cost_total,
            'dli', json_build_object(
                'value_mol_m2_day', d.crop_dli_mol_m2_day,
                'availability', d.availability,
                'unavailable_reason', d.unavailable_reason,
                'provenance', d.provenance,
                'validity_revision', d.validity_revision,
                'valid_from', d.valid_from,
                'valid_to', d.valid_to
            ),
            'stress_hours_vpd_high', ds.stress_hours_vpd_high,
            'water_used_gal', ds.water_used_gal
        )
        FROM public.daily_summary ds
        LEFT JOIN public.v_dli_daily d
          ON d.date = ds.date
         AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery')
        ORDER BY ds.date DESC
        LIMIT 1
    ) AS yesterday_summary,
    json_build_object(
        'value_mol_m2_day', NULL,
        'availability', 'unavailable',
        'unavailable_reason', 'no_valid_interior_light_sensor',
        'provenance', 'outdoor_forecast_is_not_interior_crop_dli',
        'validity_revision', 'dli-validity-v1',
        'valid_from', '2024-01-01T00:00:00Z',
        'valid_to', NULL
    ) AS dli_forecast,
    (
        SELECT json_object_agg(sub.parameter, sub.value)
        FROM (
            SELECT DISTINCT ON (s.parameter) s.parameter, s.value
            FROM public.setpoint_changes s
            ORDER BY s.parameter, s.ts DESC
        ) sub
    ) AS current_setpoints,
    (
        SELECT json_agg(row_to_json(sub.*) ORDER BY sub.ts)
        FROM (
            SELECT p.ts, p.parameter, p.value, p.reason
            FROM public.setpoint_plan p
            WHERE p.ts > now()
              AND p.is_active
              AND p.parameter <> 'plan_metadata'
            ORDER BY p.ts
        ) sub
    ) AS active_plan,
    (
        SELECT json_build_object(
            'composite_score', public.fn_system_health(),
            'components', (
                SELECT json_agg(json_build_object(
                    'component', h.component,
                    'score', h.score_pct
                ))
                FROM public.v_system_health_score h
            )
        )
    ) AS system_health,
    json_build_object(
        'electric_per_kwh', 0.111,
        'gas_per_therm', 0.83,
        'water_per_gal', 0.00484
    ) AS cost_rates;

COMMENT ON VIEW public.v_iris_planning_context IS
'Single-query Iris context with availability-bearing DLI. No outdoor forecast or legacy proxy is presented as measured interior crop light.';

CREATE OR REPLACE VIEW public.v_water_efficiency AS
SELECT
    ds.date,
    ds.water_used_gal,
    d.crop_dli_mol_m2_day AS dli_final,
    CASE
        WHEN d.crop_dli_mol_m2_day > 0
        THEN round((ds.water_used_gal / d.crop_dli_mol_m2_day)::numeric, 3)
    END AS gal_per_mol_dli,
    d.availability AS dli_availability,
    d.unavailable_reason AS dli_unavailable_reason,
    d.provenance AS dli_provenance,
    d.validity_revision AS dli_validity_revision,
    d.valid_from AS dli_valid_from,
    d.valid_to AS dli_valid_to
FROM public.daily_summary ds
LEFT JOIN public.v_dli_daily d
  ON d.date = ds.date
 AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery')
WHERE ds.water_used_gal IS NOT NULL
ORDER BY ds.date;

COMMENT ON VIEW public.v_water_efficiency IS
'Water/DLI efficiency remains unavailable while crop DLI is unavailable; water evidence stays independently visible.';

-- The firmware's qualified-minute/photoperiod policy remains authoritative.
-- These compatibility views keep their established columns and decisions, but
-- route DLI through the availability-bearing product view.
CREATE OR REPLACE VIEW public.v_lighting_minutes_status_now AS
WITH policy AS (
    SELECT * FROM fn_lighting_minutes_policy(now(), 'vallery')
),
today_window AS (
    SELECT
        p.light_key,
        p.equipment,
        p.target_light_minutes,
        p.start_hour,
        p.cutoff_hour,
        p.lux_on_threshold,
        p.lux_hysteresis,
        p.lux_off_threshold,
        ((now() AT TIME ZONE 'America/Denver')::date + make_interval(hours => p.start_hour)) AT TIME ZONE 'America/Denver' AS start_ts,
        LEAST(
            ((now() AT TIME ZONE 'America/Denver')::date + make_interval(hours => p.cutoff_hour)) AT TIME ZONE 'America/Denver',
            now()
        ) AS end_ts
    FROM policy p
),
minute_grid AS (
    SELECT
        w.*,
        gs.minute_ts
    FROM today_window w
    LEFT JOIN LATERAL generate_series(
        w.start_ts,
        w.end_ts - interval '1 minute',
        interval '1 minute'
    ) AS gs(minute_ts) ON w.end_ts > w.start_ts
),
lux_min AS (
    SELECT
        time_bucket('1 minute', c.ts) AS minute_ts,
        avg(COALESCE(c.outdoor_lux, c.lux)) AS natural_lux
    FROM climate c
    WHERE c.greenhouse_id = 'vallery'
      AND c.ts >= (SELECT min(start_ts) FROM today_window)
      AND c.ts <= (SELECT max(end_ts) FROM today_window)
      AND COALESCE(c.outdoor_lux, c.lux) IS NOT NULL
    GROUP BY 1
),
state_seed AS (
    SELECT
        w.light_key,
        w.equipment,
        w.start_ts AS ts,
        COALESCE((
            SELECT e.state
            FROM equipment_state e
            WHERE e.greenhouse_id = 'vallery'
              AND e.equipment = w.equipment
              AND e.ts <= w.start_ts
            ORDER BY e.ts DESC
            LIMIT 1
        ), false) AS state
    FROM today_window w
),
state_events AS (
    SELECT w.light_key, w.equipment, e.ts, e.state
    FROM today_window w
    JOIN equipment_state e
      ON e.greenhouse_id = 'vallery'
     AND e.equipment = w.equipment
     AND e.ts >= w.start_ts
     AND e.ts <= w.end_ts
),
state_timeline AS (
    SELECT
        x.light_key,
        x.equipment,
        x.ts,
        x.state,
        lead(x.ts, 1, w.end_ts) OVER (
            PARTITION BY x.light_key, x.equipment
            ORDER BY x.ts
        ) AS next_ts
    FROM (
        SELECT * FROM state_seed
        UNION ALL
        SELECT * FROM state_events
    ) x
    JOIN today_window w
      ON w.light_key = x.light_key
     AND w.equipment = x.equipment
),
state_segments AS (
    SELECT
        st.light_key,
        st.equipment,
        GREATEST(st.ts, w.start_ts) AS start_ts,
        LEAST(st.next_ts, w.end_ts) AS end_ts
    FROM state_timeline st
    JOIN today_window w
      ON w.light_key = st.light_key
     AND w.equipment = st.equipment
    WHERE st.state IS TRUE
      AND st.ts < w.end_ts
      AND st.next_ts > w.start_ts
),
minute_eval AS (
    SELECT
        mg.light_key,
        mg.equipment,
        mg.minute_ts,
        COALESCE(lm.natural_lux, 0.0) >= mg.lux_on_threshold AS natural_qualified,
        EXISTS (
            SELECT 1
            FROM state_segments s
            WHERE s.light_key = mg.light_key
              AND s.equipment = mg.equipment
              AND s.start_ts < mg.minute_ts + interval '1 minute'
              AND s.end_ts > mg.minute_ts
        ) AS switch_on
    FROM minute_grid mg
    LEFT JOIN lux_min lm
      ON lm.minute_ts = mg.minute_ts
),
today AS (
    SELECT
        w.light_key,
        w.equipment,
        count(me.minute_ts)::integer AS observed_minutes,
        count(me.minute_ts) FILTER (WHERE me.natural_qualified)::integer AS natural_qualified_minutes,
        count(me.minute_ts) FILTER (WHERE me.switch_on)::integer AS switch_on_minutes,
        count(me.minute_ts) FILTER (WHERE me.natural_qualified AND me.switch_on)::integer AS overlap_minutes,
        count(me.minute_ts) FILTER (WHERE me.natural_qualified OR me.switch_on)::integer AS qualified_light_minutes,
        count(me.minute_ts) FILTER (WHERE NOT me.natural_qualified AND NOT me.switch_on)::integer AS below_threshold_off_minutes
    FROM today_window w
    LEFT JOIN minute_eval me
      ON me.light_key = w.light_key
     AND me.equipment = w.equipment
    GROUP BY w.light_key, w.equipment
),
latest_climate AS (
    SELECT
        c.ts,
        d.crop_dli_mol_m2_day AS dli_today,
        c.lux,
        c.outdoor_lux
    FROM climate c
    LEFT JOIN public.v_dli_current d
      ON d.greenhouse_id = COALESCE(c.greenhouse_id, 'vallery')
    WHERE c.greenhouse_id = 'vallery'
    ORDER BY c.ts DESC
    LIMIT 1
),
latest_equipment AS (
    SELECT DISTINCT ON (equipment) equipment, state, ts
    FROM equipment_state
    WHERE greenhouse_id = 'vallery'
      AND equipment IN ('grow_light_main', 'grow_light_grow')
    ORDER BY equipment, ts DESC
),
current_firmware_start AS (
    WITH firmware_ordered AS (
        SELECT
            ts,
            firmware_version,
            lag(firmware_version) OVER (ORDER BY ts) AS previous_firmware_version
        FROM diagnostics
        WHERE firmware_version IS NOT NULL
          AND firmware_version <> ''
          AND ts > now() - interval '30 days'
    ),
    current_firmware AS (
        SELECT firmware_version
        FROM diagnostics
        WHERE firmware_version IS NOT NULL
          AND firmware_version <> ''
        ORDER BY ts DESC
        LIMIT 1
    )
    SELECT max(fo.ts) AS ts
    FROM firmware_ordered fo
    CROSS JOIN current_firmware cf
    WHERE fo.firmware_version = cf.firmware_version
      AND fo.previous_firmware_version IS DISTINCT FROM fo.firmware_version
),
latest_reason AS (
    SELECT DISTINCT ON (entity) entity, value, ts
    FROM system_state
    WHERE entity IN ('gl_main_state', 'gl_main_reason', 'gl_grow_state', 'gl_grow_reason')
    ORDER BY entity, ts DESC
),
latest_occupancy AS (
    SELECT DISTINCT ON (entity) entity, value, ts
    FROM system_state
    WHERE entity IN ('occupancy', 'occupancy_until')
    ORDER BY entity, ts DESC
),
occupancy AS (
    SELECT
        COALESCE(state.value = 'occupied', false)
        AND COALESCE(
            CASE
                WHEN until_row.value ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T' THEN until_row.value::timestamptz > now()
                ELSE false
            END,
            false
        ) AS occupancy_active
    FROM (SELECT 1) seed
    LEFT JOIN latest_occupancy state ON state.entity = 'occupancy'
    LEFT JOIN latest_occupancy until_row ON until_row.entity = 'occupancy_until'
),
outdoor_staleness AS (
    SELECT COALESCE((
        SELECT greatest(120, least(1800, round(value)::integer))
        FROM setpoint_snapshot
        WHERE COALESCE(greenhouse_id, 'vallery') = 'vallery'
          AND parameter = 'outdoor_staleness_max_s'
        ORDER BY ts DESC
        LIMIT 1
    ), 600) AS max_age_s
),
joined AS (
    SELECT
        p.*,
        COALESCE(t.qualified_light_minutes, 0) AS qualified_light_minutes,
        COALESCE(t.natural_qualified_minutes, 0) AS natural_qualified_minutes,
        COALESCE(t.switch_on_minutes, 0) AS switch_on_minutes,
        COALESCE(t.overlap_minutes, 0) AS overlap_minutes,
        greatest(0, p.target_light_minutes - COALESCE(t.qualified_light_minutes, 0)) AS remaining_light_minutes,
        c.ts AS climate_ts,
        c.dli_today,
        c.lux AS indoor_lux,
        c.outdoor_lux,
        c.outdoor_lux AS exterior_lux,
        COALESCE(c.outdoor_lux, c.lux, 0.0) AS natural_lux,
        COALESCE(c.outdoor_lux, c.lux, 0.0) >= p.lux_on_threshold AS natural_qualified_now,
        EXTRACT(hour FROM now() AT TIME ZONE 'America/Denver')::integer AS local_hour,
        CASE
            WHEN p.start_hour <= p.cutoff_hour THEN
                EXTRACT(hour FROM now() AT TIME ZONE 'America/Denver')::integer >= p.start_hour
                AND EXTRACT(hour FROM now() AT TIME ZONE 'America/Denver')::integer < p.cutoff_hour
            ELSE
                EXTRACT(hour FROM now() AT TIME ZONE 'America/Denver')::integer >= p.start_hour
                OR EXTRACT(hour FROM now() AT TIME ZONE 'America/Denver')::integer < p.cutoff_hour
        END AS in_light_window,
        COALESCE(t.qualified_light_minutes, 0) < p.target_light_minutes AS minutes_below_target,
        COALESCE(c.outdoor_lux, c.lux, 0.0) < p.lux_on_threshold AS lux_below_on_threshold,
        COALESCE(c.outdoor_lux, c.lux, 0.0) < p.lux_off_threshold AS lux_below_off_threshold,
        c.outdoor_lux IS NOT NULL
            AND c.ts > now() - make_interval(secs => os.max_age_s) AS exterior_lux_fresh,
        c.outdoor_lux IS NOT NULL
            AND c.ts > now() - make_interval(secs => os.max_age_s)
            AND c.outdoor_lux < p.lux_on_threshold AS exterior_lux_below_on_threshold,
        c.outdoor_lux IS NOT NULL
            AND c.ts > now() - make_interval(secs => os.max_age_s)
            AND c.outdoor_lux < p.lux_off_threshold AS exterior_lux_below_off_threshold,
        o.occupancy_active,
        COALESCE(e.state, false) AS actual_on,
        state_row.value AS firmware_state,
        reason_row.value AS firmware_reason,
        (
            state_row.ts >= COALESCE((SELECT ts FROM current_firmware_start), now() - interval '24 hours')
            AND reason_row.ts >= COALESCE((SELECT ts FROM current_firmware_start), now() - interval '24 hours')
            AND state_row.ts > now() - interval '15 minutes'
            AND reason_row.ts > now() - interval '15 minutes'
        ) AS firmware_telemetry_fresh,
        e.ts AS equipment_ts
    FROM policy p
    LEFT JOIN today t
      ON t.light_key = p.light_key
     AND t.equipment = p.equipment
    LEFT JOIN latest_climate c ON true
    LEFT JOIN latest_equipment e ON e.equipment = p.equipment
    LEFT JOIN latest_reason state_row ON state_row.entity = 'gl_' || p.light_key || '_state'
    LEFT JOIN latest_reason reason_row ON reason_row.entity = 'gl_' || p.light_key || '_reason'
    CROSS JOIN occupancy o
    CROSS JOIN outdoor_staleness os
)
SELECT
    j.*,
    (
        j.auto_enabled
        AND j.in_light_window
        AND j.minutes_below_target
        AND (
            j.lux_below_on_threshold
            OR (
                j.actual_on
                OR (j.firmware_telemetry_fresh AND upper(COALESCE(j.firmware_state, '')) = 'ON')
            ) AND j.lux_below_off_threshold
        )
    ) AS plant_supplement_demand,
    (
        j.auto_enabled
        AND j.occupancy_active
        AND j.exterior_lux_fresh
        AND (
            j.exterior_lux_below_on_threshold
            OR (
                j.actual_on
                OR (j.firmware_telemetry_fresh AND upper(COALESCE(j.firmware_state, '')) = 'ON')
            ) AND j.exterior_lux_below_off_threshold
        )
    ) AS occupancy_lux_demand,
    (
        (
            j.auto_enabled
            AND j.in_light_window
            AND j.minutes_below_target
            AND (
                j.lux_below_on_threshold
                OR (
                    j.actual_on
                    OR (j.firmware_telemetry_fresh AND upper(COALESCE(j.firmware_state, '')) = 'ON')
                ) AND j.lux_below_off_threshold
            )
        )
        OR (
            j.auto_enabled
            AND j.occupancy_active
            AND j.exterior_lux_fresh
            AND (
                j.exterior_lux_below_on_threshold
                OR (
                    j.actual_on
                    OR (j.firmware_telemetry_fresh AND upper(COALESCE(j.firmware_state, '')) = 'ON')
                ) AND j.exterior_lux_below_off_threshold
            )
        )
    ) AS expected_on,
    dc.availability AS dli_availability,
    dc.unavailable_reason AS dli_unavailable_reason,
    dc.provenance AS dli_provenance,
    dc.validity_revision AS dli_validity_revision,
    dc.valid_from AS dli_valid_from,
    dc.valid_to AS dli_valid_to
FROM joined j
LEFT JOIN public.v_dli_current dc
  ON dc.greenhouse_id = j.greenhouse_id;

COMMENT ON VIEW public.v_lighting_minutes_status_now IS
    'Current per-circuit qualified-light-minutes policy and DLI-independent demand. dli_today is nullable product evidence with explicit availability/provenance; no zero sentinel or forensic proxy is exposed.';

CREATE OR REPLACE VIEW public.v_lighting_circuit_status_now AS
WITH status AS (
    SELECT * FROM public.v_lighting_minutes_status_now
), latest_reason AS (
    SELECT DISTINCT ON (ss.entity)
        ss.entity,
        ss.value,
        ss.ts
    FROM public.system_state ss
    WHERE ss.entity IN (
        'gl_main_state',
        'gl_main_reason',
        'gl_grow_state',
        'gl_grow_reason'
    )
    ORDER BY ss.entity, ss.ts DESC
)
SELECT
    s.greenhouse_id,
    s.ts,
    s.light_key,
    s.equipment,
    s.legacy_dli_target AS dli_target,
    s.start_hour,
    s.cutoff_hour,
    s.lux_on_threshold,
    s.lux_hysteresis,
    s.lux_off_threshold,
    s.min_on_s,
    s.min_off_s,
    s.auto_enabled,
    s.source_chain,
    s.controller_contract,
    s.climate_ts,
    s.dli_today,
    s.indoor_lux,
    s.outdoor_lux,
    s.natural_lux,
    s.local_hour,
    s.in_light_window,
    NULL::boolean AS dli_below_target,
    s.lux_below_on_threshold,
    s.lux_below_off_threshold,
    s.expected_on,
    s.actual_on,
    CASE WHEN s.firmware_telemetry_fresh THEN state_row.value END
        AS firmware_state,
    CASE WHEN s.firmware_telemetry_fresh THEN reason_row.value END
        AS firmware_reason,
    s.equipment_ts,
    state_row.value AS firmware_state_raw,
    reason_row.value AS firmware_reason_raw,
    state_row.ts AS firmware_state_ts,
    reason_row.ts AS firmware_reason_ts,
    s.firmware_telemetry_fresh,
    s.dli_availability,
    s.dli_unavailable_reason,
    s.dli_provenance,
    s.dli_validity_revision,
    s.dli_valid_from,
    s.dli_valid_to
FROM status s
LEFT JOIN latest_reason state_row
  ON state_row.entity = 'gl_' || s.light_key || '_state'
LEFT JOIN latest_reason reason_row
  ON reason_row.entity = 'gl_' || s.light_key || '_reason';

COMMENT ON VIEW public.v_lighting_circuit_status_now IS
'Current per-circuit qualified-minute lighting status. dli_today and dli_below_target are NULL when unavailable; expected_on remains driven by qualified minutes/photoperiod and lux, with explicit DLI provenance appended.';

CREATE OR REPLACE VIEW public.v_lighting_status_now AS
WITH policy AS (
    SELECT * FROM public.fn_lighting_policy(now(), 'vallery')
), circuits AS (
    SELECT * FROM public.v_lighting_circuit_status_now
), main AS (
    SELECT * FROM circuits WHERE light_key = 'main'
), grow AS (
    SELECT * FROM circuits WHERE light_key = 'grow'
)
SELECT
    policy.greenhouse_id,
    policy.ts,
    policy.local_date,
    policy.target_dli,
    policy.target_ppfd_umol_m2_s,
    policy.target_light_hours,
    policy.sunrise_hour,
    policy.natural_sunset_hour,
    policy.cutoff_hour,
    policy.max_crop_name,
    policy.max_crop_stage,
    policy.source_chain,
    policy.controller_contract,
    main.climate_ts,
    main.dli_today,
    main.indoor_lux AS lux,
    main.outdoor_lux,
    main.lux_on_threshold AS gl_lux_threshold,
    main.lux_hysteresis AS gl_lux_hysteresis,
    main.actual_on AS grow_light_main_on,
    grow.actual_on AS grow_light_grow_on,
    main.local_hour,
    main.in_light_window,
    main.dli_below_target,
    main.lux_below_on_threshold AS lux_below_threshold,
    (main.expected_on OR grow.expected_on) AS expected_lights_on,
    main.dli_target AS main_dli_target,
    main.start_hour AS main_start_hour,
    main.cutoff_hour AS main_cutoff_hour,
    main.lux_on_threshold AS main_lux_on_threshold,
    main.lux_off_threshold AS main_lux_off_threshold,
    main.lux_hysteresis AS main_lux_hysteresis,
    main.expected_on AS main_expected_on,
    main.firmware_state AS main_firmware_state,
    main.firmware_reason AS main_firmware_reason,
    grow.dli_target AS grow_dli_target,
    grow.start_hour AS grow_start_hour,
    grow.cutoff_hour AS grow_cutoff_hour,
    grow.lux_on_threshold AS grow_lux_on_threshold,
    grow.lux_off_threshold AS grow_lux_off_threshold,
    grow.lux_hysteresis AS grow_lux_hysteresis,
    grow.expected_on AS grow_expected_on,
    grow.firmware_state AS grow_firmware_state,
    grow.firmware_reason AS grow_firmware_reason,
    main.firmware_state_ts AS main_firmware_state_ts,
    main.firmware_reason_ts AS main_firmware_reason_ts,
    main.firmware_telemetry_fresh AS main_firmware_telemetry_fresh,
    grow.firmware_state_ts AS grow_firmware_state_ts,
    grow.firmware_reason_ts AS grow_firmware_reason_ts,
    grow.firmware_telemetry_fresh AS grow_firmware_telemetry_fresh,
    main.dli_availability,
    main.dli_unavailable_reason,
    main.dli_provenance,
    main.dli_validity_revision,
    main.dli_valid_from,
    main.dli_valid_to
FROM policy
CROSS JOIN main
CROSS JOIN grow;

COMMENT ON VIEW public.v_lighting_status_now IS
'Compatibility one-row lighting status. DLI evidence is nullable with explicit availability/provenance; qualified-minute and photoperiod expected-state behavior is unchanged.';

CREATE OR REPLACE VIEW public.v_lighting_traceability_now AS
WITH status AS (
    SELECT * FROM v_lighting_minutes_status_now
),
latest_desired AS (
    SELECT DISTINCT ON (parameter)
        parameter,
        value,
        delivery_status,
        ts
    FROM setpoint_changes
    WHERE COALESCE(greenhouse_id, 'vallery') = 'vallery'
      AND COALESCE(source, '') <> 'esp32'
    ORDER BY parameter, ts DESC
),
latest_cfg AS (
    SELECT DISTINCT ON (parameter)
        parameter,
        value,
        ts
    FROM setpoint_snapshot
    WHERE COALESCE(greenhouse_id, 'vallery') = 'vallery'
    ORDER BY parameter, ts DESC
),
latest_decision AS (
    SELECT DISTINCT ON (entity)
        entity,
        value,
        ts
    FROM system_state
    WHERE entity IN ('gl_main_decision_epoch', 'gl_grow_decision_epoch')
    ORDER BY entity, ts DESC
)
SELECT
    s.greenhouse_id,
    s.ts,
    s.light_key,
    s.equipment,
    s.target_light_minutes,
    s.start_hour,
    s.cutoff_hour,
    s.lux_on_threshold,
    s.lux_hysteresis,
    s.lux_off_threshold,
    s.min_on_s,
    s.min_off_s,
    s.auto_enabled,
    s.legacy_dli_target,
    s.source_chain,
    s.controller_contract,
    s.qualified_light_minutes,
    s.natural_qualified_minutes,
    s.switch_on_minutes,
    s.overlap_minutes,
    s.remaining_light_minutes,
    s.climate_ts,
    s.dli_today,
    s.indoor_lux,
    s.outdoor_lux,
    s.exterior_lux,
    s.natural_lux,
    s.natural_qualified_now,
    s.local_hour,
    s.in_light_window,
    s.minutes_below_target,
    s.lux_below_on_threshold,
    s.lux_below_off_threshold,
    s.exterior_lux_fresh,
    s.exterior_lux_below_on_threshold,
    s.exterior_lux_below_off_threshold,
    s.occupancy_active,
    s.actual_on,
    s.firmware_state,
    s.firmware_reason,
    s.firmware_telemetry_fresh,
    s.equipment_ts,
    s.plant_supplement_demand,
    s.occupancy_lux_demand,
    s.expected_on,
    cfg_target.value AS cfg_target_light_minutes,
    cfg_lux.value AS cfg_lux_on_threshold,
    cfg_hyst.value AS cfg_lux_hysteresis,
    cfg_auto.value >= 0.5 AS cfg_auto_enabled,
    cfg_auto.ts AS cfg_auto_ts,
    desired_target.value AS desired_target_light_minutes,
    desired_lux.value AS desired_lux_on_threshold,
    desired_hyst.value AS desired_lux_hysteresis,
    desired_auto.value >= 0.5 AS desired_auto_enabled,
    desired_auto.delivery_status AS desired_auto_delivery_status,
    desired_auto.ts AS desired_auto_ts,
    CASE
        WHEN decision.value ~ '^[0-9]+([.]0+)?$' THEN round(decision.value::numeric)::bigint
        ELSE NULL
    END AS firmware_decision_epoch,
    decision.ts AS firmware_decision_ts,
    decision.ts > now() - interval '15 minutes' AS firmware_decision_fresh,
    (
        s.auto_enabled IS NOT DISTINCT FROM (cfg_auto.value >= 0.5)
        AND s.target_light_minutes IS NOT DISTINCT FROM round(cfg_target.value)::integer
        AND COALESCE(abs(s.lux_on_threshold - cfg_lux.value) < 0.5, false)
        AND COALESCE(abs(s.lux_hysteresis - cfg_hyst.value) < 0.5, false)
    ) AS policy_matches_cfg,
    s.dli_availability,
    s.dli_unavailable_reason,
    s.dli_provenance,
    s.dli_validity_revision,
    s.dli_valid_from,
    s.dli_valid_to
FROM status s
LEFT JOIN latest_cfg cfg_target ON cfg_target.parameter = 'gl_' || s.light_key || '_target_light_minutes'
LEFT JOIN latest_cfg cfg_lux ON cfg_lux.parameter = 'gl_' || s.light_key || '_lux_threshold'
LEFT JOIN latest_cfg cfg_hyst ON cfg_hyst.parameter = 'gl_' || s.light_key || '_lux_hysteresis'
LEFT JOIN latest_cfg cfg_auto ON cfg_auto.parameter = 'sw_gl_' || s.light_key || '_auto_mode'
LEFT JOIN latest_desired desired_target ON desired_target.parameter = 'gl_' || s.light_key || '_target_light_minutes'
LEFT JOIN latest_desired desired_lux ON desired_lux.parameter = 'gl_' || s.light_key || '_lux_threshold'
LEFT JOIN latest_desired desired_hyst ON desired_hyst.parameter = 'gl_' || s.light_key || '_lux_hysteresis'
LEFT JOIN latest_desired desired_auto ON desired_auto.parameter = 'sw_gl_' || s.light_key || '_auto_mode'
LEFT JOIN latest_decision decision ON decision.entity = 'gl_' || s.light_key || '_decision_epoch';

COMMENT ON VIEW public.v_lighting_traceability_now IS
    'Lighting policy traceability with qualified-minute demand, cfg readbacks, firmware decisions, physical state, and appended nullable DLI availability/provenance. No forensic DLI scalar or zero sentinel is exposed.';
