-- 195-dli-availability-provenance.sql
--
-- Issue #435: interior crop DLI is unavailable while the interior light
-- sensor is broken.  Preserve legacy proxy values for forensic inspection,
-- but never promote them to measured crop evidence.
--
-- Non-self-transactional: safe for an outer rollback proof.

CREATE TABLE IF NOT EXISTS public.dli_validity_intervals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    greenhouse_id text NOT NULL DEFAULT 'vallery',
    valid_from timestamptz NOT NULL,
    valid_to timestamptz,
    availability text NOT NULL,
    unavailable_reason text,
    provenance text NOT NULL,
    validity_revision text NOT NULL,
    operator_validated boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    created_by text NOT NULL DEFAULT 'migration_195',
    CONSTRAINT dli_validity_interval_order CHECK (
        valid_to IS NULL OR valid_to > valid_from
    ),
    CONSTRAINT dli_validity_availability CHECK (
        availability IN ('available', 'unavailable')
    ),
    CONSTRAINT dli_validity_evidence_shape CHECK (
        (
            availability = 'available'
            AND operator_validated
            AND unavailable_reason IS NULL
        ) OR (
            availability = 'unavailable'
            AND NOT operator_validated
            AND unavailable_reason IS NOT NULL
            AND btrim(unavailable_reason) <> ''
        )
    ),
    CONSTRAINT dli_validity_revision_unique UNIQUE (
        greenhouse_id, validity_revision
    )
);

COMMENT ON TABLE public.dli_validity_intervals IS
'Operator-controlled validity ledger for interior crop DLI. Available intervals require explicit operator validation; unavailable intervals carry reason, provenance, revision, and half-open validity bounds.';

CREATE OR REPLACE FUNCTION public.enforce_dli_validity_nonoverlap()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM public.dli_validity_intervals existing
        WHERE existing.greenhouse_id = NEW.greenhouse_id
          AND existing.id <> COALESCE(NEW.id, -1)
          AND tstzrange(
                existing.valid_from,
                COALESCE(existing.valid_to, 'infinity'::timestamptz),
                '[)'
              ) && tstzrange(
                NEW.valid_from,
                COALESCE(NEW.valid_to, 'infinity'::timestamptz),
                '[)'
              )
    ) THEN
        RAISE EXCEPTION
            'DLI validity interval overlaps an existing interval for greenhouse %',
            NEW.greenhouse_id;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_dli_validity_nonoverlap
    ON public.dli_validity_intervals;
CREATE TRIGGER trg_dli_validity_nonoverlap
BEFORE INSERT OR UPDATE ON public.dli_validity_intervals
FOR EACH ROW EXECUTE FUNCTION public.enforce_dli_validity_nonoverlap();

-- The legacy accumulator has never been backed by an operator-validated
-- interior sensor.  Start before recorded production history so every legacy
-- row is classified without rewriting or deleting its numeric proxy value.
INSERT INTO public.dli_validity_intervals (
    greenhouse_id,
    valid_from,
    valid_to,
    availability,
    unavailable_reason,
    provenance,
    validity_revision,
    operator_validated,
    created_by
) SELECT
    'vallery',
    '2024-01-01 00:00:00+00',
    NULL,
    'unavailable',
    'interior_light_sensor_broken',
    'legacy_invalid_exterior_proxy_plus_fixture_estimate',
    'dli-validity-v1',
    false,
    'migration_195'
WHERE NOT EXISTS (
    SELECT 1
    FROM public.dli_validity_intervals existing
    WHERE existing.greenhouse_id = 'vallery'
      AND existing.validity_revision = 'dli-validity-v1'
);

CREATE OR REPLACE FUNCTION public.fn_dli_validity(
    p_ts timestamptz DEFAULT now(),
    p_greenhouse_id text DEFAULT 'vallery'
)
RETURNS TABLE (
    availability text,
    unavailable_reason text,
    provenance text,
    validity_revision text,
    valid_from timestamptz,
    valid_to timestamptz,
    operator_validated boolean
)
LANGUAGE sql
STABLE
AS $$
    SELECT
        v.availability,
        v.unavailable_reason,
        v.provenance,
        v.validity_revision,
        v.valid_from,
        v.valid_to,
        v.operator_validated
    FROM public.dli_validity_intervals v
    WHERE v.greenhouse_id = p_greenhouse_id
      AND p_ts >= v.valid_from
      AND (v.valid_to IS NULL OR p_ts < v.valid_to)
    ORDER BY v.valid_from DESC
    LIMIT 1
$$;

COMMENT ON FUNCTION public.fn_dli_validity(timestamptz, text) IS
'Returns the one half-open validity interval governing interior crop DLI at a timestamp. No row means no validated DLI contract exists.';

-- This is the only view allowed to expose the old numeric proxy.  Its name and
-- evidence_class make the invalidity explicit; product consumers use
-- v_dli_current/v_dli_daily instead.
CREATE OR REPLACE VIEW public.v_dli_forensic_history AS
SELECT
    c.ts,
    COALESCE(c.greenhouse_id, 'vallery') AS greenhouse_id,
    c.dli_today AS forensic_proxy_dli_mol_m2_day,
    'forensic_invalid_proxy'::text AS evidence_class,
    COALESCE(v.availability, 'unavailable') AS availability,
    COALESCE(v.unavailable_reason, 'validity_contract_missing') AS unavailable_reason,
    COALESCE(v.provenance, 'unknown_unvalidated_source') AS provenance,
    COALESCE(v.validity_revision, 'missing') AS validity_revision,
    v.valid_from,
    v.valid_to
FROM public.climate c
LEFT JOIN LATERAL public.fn_dli_validity(
    c.ts,
    COALESCE(c.greenhouse_id, 'vallery')
) v ON true
WHERE c.dli_today IS NOT NULL;

COMMENT ON VIEW public.v_dli_forensic_history IS
'Forensic-only legacy DLI proxy history. Numeric values came from an invalid interior sensor/exterior proxy/fixture estimate and must never be used as measured crop DLI.';

CREATE OR REPLACE VIEW public.v_dli_current AS
WITH latest AS (
    SELECT DISTINCT ON (COALESCE(c.greenhouse_id, 'vallery'))
        c.ts,
        COALESCE(c.greenhouse_id, 'vallery') AS greenhouse_id,
        c.dli_today AS forensic_proxy_dli_mol_m2_day
    FROM public.climate c
    ORDER BY COALESCE(c.greenhouse_id, 'vallery'), c.ts DESC
)
SELECT
    l.ts,
    l.greenhouse_id,
    CASE
        WHEN v.availability = 'available' AND v.operator_validated
        THEN l.forensic_proxy_dli_mol_m2_day
        ELSE NULL
    END::double precision AS crop_dli_mol_m2_day,
    COALESCE(v.availability, 'unavailable') AS availability,
    COALESCE(v.unavailable_reason, 'validity_contract_missing') AS unavailable_reason,
    COALESCE(v.provenance, 'unknown_unvalidated_source') AS provenance,
    COALESCE(v.validity_revision, 'missing') AS validity_revision,
    v.valid_from,
    v.valid_to,
    (l.forensic_proxy_dli_mol_m2_day IS NOT NULL) AS forensic_proxy_present
FROM latest l
LEFT JOIN LATERAL public.fn_dli_validity(l.ts, l.greenhouse_id) v ON true;

COMMENT ON VIEW public.v_dli_current IS
'Current interior crop DLI product contract. Numeric value is NULL unless an operator-validated interval governs the source; invalid legacy proxy presence is diagnostic-only.';

CREATE OR REPLACE VIEW public.v_dli_daily AS
WITH day_bounds AS (
    SELECT
        ds.date,
        COALESCE(ds.greenhouse_id, 'vallery') AS greenhouse_id,
        ds.dli_final AS forensic_proxy_dli_mol_m2_day,
        ds.date::timestamp AT TIME ZONE 'America/Denver' AS day_start,
        (ds.date + 1)::timestamp AT TIME ZONE 'America/Denver' AS day_end
    FROM public.daily_summary ds
    WHERE ds.date IS NOT NULL
)
SELECT
    d.date,
    d.greenhouse_id,
    CASE
        WHEN v.availability = 'available'
         AND v.operator_validated
         AND v.valid_from <= d.day_start
         AND (v.valid_to IS NULL OR v.valid_to >= d.day_end)
        THEN d.forensic_proxy_dli_mol_m2_day
        ELSE NULL
    END::double precision AS crop_dli_mol_m2_day,
    CASE
        WHEN v.availability = 'available'
         AND v.operator_validated
         AND v.valid_from <= d.day_start
         AND (v.valid_to IS NULL OR v.valid_to >= d.day_end)
        THEN 'available'
        ELSE 'unavailable'
    END::text AS availability,
    CASE
        WHEN v.availability = 'available'
         AND v.operator_validated
         AND v.valid_from <= d.day_start
         AND (v.valid_to IS NULL OR v.valid_to >= d.day_end)
        THEN NULL
        WHEN v.availability = 'available'
        THEN 'validity_interval_does_not_cover_full_local_day'
        ELSE COALESCE(v.unavailable_reason, 'validity_contract_missing')
    END::text AS unavailable_reason,
    COALESCE(v.provenance, 'unknown_unvalidated_source') AS provenance,
    COALESCE(v.validity_revision, 'missing') AS validity_revision,
    v.valid_from,
    v.valid_to,
    (d.forensic_proxy_dli_mol_m2_day IS NOT NULL) AS forensic_proxy_present
FROM day_bounds d
LEFT JOIN LATERAL public.fn_dli_validity(
    d.day_start + interval '12 hours',
    d.greenhouse_id
) v ON true;

COMMENT ON VIEW public.v_dli_daily IS
'Daily interior crop DLI product contract. A numeric value requires one operator-validated interval to cover the entire Denver-local day; partial/boundary days remain unavailable.';

COMMENT ON COLUMN public.climate.dli_today IS
'LEGACY FORENSIC PROXY ONLY while dli-validity-v1 is unavailable. Built from a broken interior sensor/exterior proxy plus fixture estimate; use v_dli_current or v_dli_daily for product truth.';
COMMENT ON COLUMN public.daily_summary.dli_final IS
'LEGACY FORENSIC DAILY PROXY ONLY while dli-validity-v1 is unavailable. Preserved for audit; use v_dli_daily.crop_dli_mol_m2_day for product truth.';

COMMENT ON VIEW public.v_climate_latest IS
'Raw/latest climate transport view. dli_today is the explicitly invalid legacy proxy described by the source-column comment; product consumers must use v_dli_current.';
COMMENT ON MATERIALIZED VIEW public.v_climate_merged IS
'Raw merged climate transport history. dli_today is the explicitly invalid legacy proxy described by the source-column comment; product consumers must use v_dli_daily.';
COMMENT ON VIEW public.v_greenhouse_state IS
'Replay/raw control-state history. dli_today is preserved as forensic legacy proxy only; it is not product DLI. Product consumers must use v_dli_current/v_dli_daily.';

CREATE OR REPLACE VIEW public.v_greenhouse_now AS
SELECT
    c.ts,
    round(c.temp_avg::numeric, 1) AS temp_avg,
    round(c.temp_north::numeric, 1) AS temp_north,
    round(c.temp_south::numeric, 1) AS temp_south,
    round(c.temp_east::numeric, 1) AS temp_east,
    round(c.temp_west::numeric, 1) AS temp_west,
    round(c.rh_avg::numeric, 1) AS rh_avg,
    round(c.vpd_avg::numeric, 2) AS vpd_avg,
    round(c.co2_ppm::numeric, 0) AS co2_ppm,
    round(c.lux::numeric, 0) AS lux,
    round(dc.crop_dli_mol_m2_day::numeric, 2) AS dli_today,
    o.outdoor_temp_f,
    o.outdoor_rh_pct,
    o.wind_mph,
    o.pressure_hpa,
    round(c.mister_water_today::numeric, 1) AS mister_water_today,
    h.hydro_ph,
    h.hydro_ec_us_cm,
    h.hydro_tds_ppm,
    h.hydro_water_temp_f,
    d.wifi_rssi,
    round(d.heap_bytes::numeric, 0) AS heap_kb,
    round(d.uptime_s::numeric, 0) AS uptime_s,
    (
        SELECT s.value
        FROM public.system_state s
        WHERE s.entity = 'greenhouse_state'
        ORDER BY s.ts DESC
        LIMIT 1
    ) AS state,
    (
        SELECT s.value
        FROM public.system_state s
        WHERE s.entity = 'lead_fan'
        ORDER BY s.ts DESC
        LIMIT 1
    ) AS lead_fan,
    public.fn_system_health() AS health_score,
    (
        SELECT count(*)
        FROM public.alert_log a
        WHERE a.disposition = 'open'
    ) AS open_alerts,
    cost.cost_electric,
    cost.cost_gas,
    cost.cost_water,
    cost.cost_total,
    dc.availability AS dli_availability,
    dc.unavailable_reason AS dli_unavailable_reason,
    dc.provenance AS dli_provenance,
    dc.validity_revision AS dli_validity_revision,
    dc.valid_from AS dli_valid_from,
    dc.valid_to AS dli_valid_to
FROM public.climate c
LEFT JOIN LATERAL (
    SELECT d0.wifi_rssi, d0.heap_bytes, d0.uptime_s
    FROM public.diagnostics d0
    ORDER BY d0.ts DESC
    LIMIT 1
) d ON true
LEFT JOIN LATERAL (
    SELECT
        round(c0.outdoor_temp_f::numeric, 1) AS outdoor_temp_f,
        round(c0.outdoor_rh_pct::numeric, 0) AS outdoor_rh_pct,
        round(c0.wind_speed_mph::numeric, 1) AS wind_mph,
        round(c0.pressure_hpa::numeric, 1) AS pressure_hpa
    FROM public.climate c0
    WHERE c0.outdoor_temp_f IS NOT NULL
      AND c0.ts > now() - interval '30 minutes'
    ORDER BY c0.ts DESC
    LIMIT 1
) o ON true
LEFT JOIN LATERAL (
    SELECT
        round(c1.hydro_ph::numeric, 1) AS hydro_ph,
        round(c1.hydro_ec_us_cm::numeric, 0) AS hydro_ec_us_cm,
        round(c1.hydro_tds_ppm::numeric, 0) AS hydro_tds_ppm,
        round(c1.hydro_water_temp_f::numeric, 1) AS hydro_water_temp_f
    FROM public.climate c1
    WHERE c1.hydro_ph IS NOT NULL
      AND c1.ts > now() - interval '30 minutes'
    ORDER BY c1.ts DESC
    LIMIT 1
) h ON true
CROSS JOIN public.v_cost_today cost
LEFT JOIN public.v_dli_current dc
  ON dc.greenhouse_id = COALESCE(c.greenhouse_id, 'vallery')
WHERE c.temp_avg IS NOT NULL
ORDER BY c.ts DESC
LIMIT 1;

COMMENT ON VIEW public.v_greenhouse_now IS
'Current greenhouse product view. dli_today is nullable and unavailable metadata is explicit while the interior sensor is invalid.';

CREATE OR REPLACE VIEW public.v_estimated_plant_dli AS
SELECT
    ds.date,
    NULL::numeric AS sensor_dli,
    NULL::numeric AS corrected_solar_dli,
    round((COALESCE(ds.runtime_grow_light_min, 0) / 60.0)::numeric, 1)
        AS grow_light_hours,
    NULL::numeric AS grow_light_dli,
    NULL::numeric AS estimated_plant_dli,
    'UNAVAILABLE'::text AS dli_status,
    d.availability,
    d.unavailable_reason,
    d.provenance,
    d.validity_revision,
    d.valid_from,
    d.valid_to
FROM public.daily_summary ds
LEFT JOIN public.v_dli_daily d
  ON d.date = ds.date
 AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery')
ORDER BY ds.date DESC;

COMMENT ON VIEW public.v_estimated_plant_dli IS
'Compatibility view for legacy consumers. All DLI scalars are NULL while the interior sensor is invalid; grow-light runtime remains separately observable and availability provenance is explicit.';

CREATE OR REPLACE VIEW public.v_lighting_daily AS
WITH runtime AS (
    SELECT day, equipment, on_minutes, cycles
    FROM public.v_equipment_runtime_daily
    WHERE equipment IN ('grow_light_main', 'grow_light_grow')
)
SELECT
    ds.date,
    (ds.date + time '12:00')::timestamptz AS ts,
    d.crop_dli_mol_m2_day AS sensor_dli,
    ds.runtime_grow_light_min / 60.0 AS grow_light_hours,
    COALESCE(main_rt.on_minutes, 0.0) / 60.0 AS main_light_hours,
    COALESCE(grow_rt.on_minutes, 0.0) / 60.0 AS grow_light_circuit_hours,
    COALESCE(main_rt.cycles, 0) AS main_light_cycles,
    COALESCE(grow_rt.cycles, 0) AS grow_light_circuit_cycles,
    p.target_dli,
    p.target_light_hours,
    p.sunrise_hour,
    p.natural_sunset_hour,
    p.cutoff_hour,
    p.max_crop_name,
    d.availability AS dli_availability,
    d.unavailable_reason AS dli_unavailable_reason,
    d.provenance AS dli_provenance,
    d.validity_revision AS dli_validity_revision,
    d.valid_from AS dli_valid_from,
    d.valid_to AS dli_valid_to
FROM public.daily_summary ds
CROSS JOIN LATERAL public.fn_lighting_policy(
    (ds.date + time '12:00')::timestamptz,
    COALESCE(ds.greenhouse_id, 'vallery')
) p
LEFT JOIN runtime main_rt
  ON main_rt.day = ds.date AND main_rt.equipment = 'grow_light_main'
LEFT JOIN runtime grow_rt
  ON grow_rt.day = ds.date AND grow_rt.equipment = 'grow_light_grow'
LEFT JOIN public.v_dli_daily d
  ON d.date = ds.date
 AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery');

COMMENT ON VIEW public.v_lighting_daily IS
'DLI-independent lighting runtime and crop target context. Measured sensor_dli is NULL with explicit validity metadata while the interior sensor is invalid.';

-- Product KPI retains its established column order and score semantics.  The
-- old dli column remains for compatibility but is NULL; appended fields carry
-- the reason/provenance/valid interval.
CREATE OR REPLACE VIEW public.v_daily_kpi AS
WITH evidence AS (
    SELECT
        d.*,
        w.quality_filtered_meter_gal,
        w.climate_wetting_gal,
        COALESCE(w.available_for_scoring, false) AS water_ok,
        e.modeled_kwh,
        COALESCE(e.available_for_scoring, false) AS energy_ok,
        dl.crop_dli_mol_m2_day,
        dl.availability AS dli_availability,
        dl.unavailable_reason AS dli_unavailable_reason,
        dl.provenance AS dli_provenance,
        dl.validity_revision AS dli_validity_revision,
        dl.valid_from AS dli_valid_from,
        dl.valid_to AS dli_valid_to
    FROM public.daily_summary d
    LEFT JOIN public.v_water_attribution_daily w
      ON w.date = d.date AND w.greenhouse_id = d.greenhouse_id
    LEFT JOIN public.v_runtime_energy_daily e
      ON e.date = d.date AND e.greenhouse_id = d.greenhouse_id
    LEFT JOIN public.v_dli_daily dl
      ON dl.date = d.date
     AND dl.greenhouse_id = COALESCE(d.greenhouse_id, 'vallery')
    WHERE d.date IS NOT NULL
), normalized AS (
    SELECT
        e.*,
        COALESCE(e.compliance_v2_attributable_pct, e.compliance_pct, 0)
            AS score_compliance,
        e.water_ok AND e.energy_ok AND e.cost_total IS NOT NULL AS resource_ok
    FROM evidence e
)
SELECT
    date,
    round(score_compliance::numeric, 1) AS compliance_pct,
    round(COALESCE(graded_temp_compliance_pct, temp_compliance_pct, 0)::numeric, 1)
        AS temp_compliance_pct,
    round(COALESCE(graded_vpd_compliance_pct, vpd_compliance_pct, 0)::numeric, 1)
        AS vpd_compliance_pct,
    round(COALESCE(graded_stress_hours_heat, stress_hours_heat, 0)::numeric, 2)
        AS heat_stress_h,
    round(COALESCE(graded_stress_hours_cold, stress_hours_cold, 0)::numeric, 2)
        AS cold_stress_h,
    round(COALESCE(graded_stress_hours_vpd_high, stress_hours_vpd_high, 0)::numeric, 2)
        AS vpd_high_stress_h,
    round(COALESCE(graded_stress_hours_vpd_low, stress_hours_vpd_low, 0)::numeric, 2)
        AS vpd_low_stress_h,
    round((
        COALESCE(graded_stress_hours_heat, stress_hours_heat, 0)
        + COALESCE(graded_stress_hours_cold, stress_hours_cold, 0)
        + COALESCE(graded_stress_hours_vpd_high, stress_hours_vpd_high, 0)
        + COALESCE(graded_stress_hours_vpd_low, stress_hours_vpd_low, 0)
    )::numeric, 2) AS total_stress_h,
    CASE WHEN energy_ok THEN round(modeled_kwh::numeric, 2) END AS kwh,
    CASE WHEN resource_ok
      THEN round(COALESCE(therms_estimated, gas_used_therms)::numeric, 3)
    END AS therms,
    CASE WHEN water_ok THEN round(quality_filtered_meter_gal::numeric, 0) END AS water_gal,
    CASE WHEN water_ok THEN round(climate_wetting_gal::numeric, 0) END AS mister_water_gal,
    CASE WHEN energy_ok THEN round(cost_electric::numeric, 2) END AS cost_electric,
    CASE WHEN resource_ok THEN round(cost_gas::numeric, 2) END AS cost_gas,
    CASE WHEN water_ok THEN round(cost_water::numeric, 2) END AS cost_water,
    CASE WHEN resource_ok THEN round(cost_total::numeric, 2) END AS cost_total,
    round(temp_min::numeric, 1) AS temp_min,
    round(temp_max::numeric, 1) AS temp_max,
    round(temp_avg::numeric, 1) AS temp_avg,
    round(vpd_min::numeric, 2) AS vpd_min,
    round(vpd_max::numeric, 2) AS vpd_max,
    round(vpd_avg::numeric, 2) AS vpd_avg,
    round(crop_dli_mol_m2_day::numeric, 1) AS dli,
    round(min_dp_margin_f::numeric, 1) AS dp_margin_min_f,
    round(COALESCE(dp_risk_hours, 0)::numeric, 1) AS dp_risk_hours,
    round((CASE
        WHEN resource_ok THEN score_compliance / 100.0 * 80
          + GREATEST(0, 1.0 - LEAST(cost_total / 15.0, 1.0)) * 20
        ELSE score_compliance
    END)::numeric, 1) AS planner_score,
    CASE WHEN resource_ok THEN 20::numeric ELSE 0::numeric END
        AS planner_score_resource_weight_pct,
    resource_ok AS resource_terms_available,
    dli_availability,
    dli_unavailable_reason,
    dli_provenance,
    dli_validity_revision,
    dli_valid_from,
    dli_valid_to
FROM normalized
ORDER BY date;

COMMENT ON VIEW public.v_daily_kpi IS
'Daily planner KPI with provenance-gated resources and availability-bearing crop DLI. Invalid interior-light evidence remains NULL and has zero score influence.';

CREATE OR REPLACE VIEW public.v_iris_planning_context AS
SELECT
    now() AS query_ts,
    (
        SELECT json_build_object(
            'temp_avg', round(avg(c.temp_avg)::numeric, 1),
            'vpd_avg', round(avg(c.vpd_avg)::numeric, 2),
            'rh_avg', round(avg(c.rh_avg)::numeric, 1),
            'outdoor_temp_f', round(avg(c.outdoor_temp_f)::numeric, 1),
            'dli', (
                SELECT json_build_object(
                    'value_mol_m2_day', dc.crop_dli_mol_m2_day,
                    'availability', dc.availability,
                    'unavailable_reason', dc.unavailable_reason,
                    'provenance', dc.provenance,
                    'validity_revision', dc.validity_revision,
                    'valid_from', dc.valid_from,
                    'valid_to', dc.valid_to
                )
                FROM public.v_dli_current dc
                WHERE dc.greenhouse_id = 'vallery'
                LIMIT 1
            ),
            'co2_ppm', round(avg(c.co2_ppm)::numeric, 0)
        )
        FROM public.climate c
        WHERE c.ts >= now() - interval '1 hour'
          AND c.temp_avg IS NOT NULL
    ) AS current_conditions,
    (
        SELECT json_build_object(
            'north', round(avg(c.temp_north)::numeric, 1),
            'south', round(avg(c.temp_south)::numeric, 1),
            'east', round(avg(c.temp_east)::numeric, 1),
            'west', round(avg(c.temp_west)::numeric, 1)
        )
        FROM public.climate c
        WHERE c.ts >= now() - interval '1 hour'
          AND c.temp_avg IS NOT NULL
    ) AS zone_context,
    (
        SELECT json_build_object(
            'date', ds.date,
            'cost_total', ds.cost_total,
            'dli', json_build_object(
                'value_mol_m2_day', d.crop_dli_mol_m2_day,
                'availability', d.availability,
                'unavailable_reason', d.unavailable_reason,
                'provenance', d.provenance,
                'validity_revision', d.validity_revision,
                'valid_from', d.valid_from,
                'valid_to', d.valid_to
            ),
            'stress_hours_vpd_high', ds.stress_hours_vpd_high,
            'water_used_gal', ds.water_used_gal
        )
        FROM public.daily_summary ds
        LEFT JOIN public.v_dli_daily d
          ON d.date = ds.date
         AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery')
        ORDER BY ds.date DESC
        LIMIT 1
    ) AS yesterday_summary,
    json_build_object(
        'value_mol_m2_day', NULL,
        'availability', 'unavailable',
        'unavailable_reason', 'no_valid_interior_light_sensor',
        'provenance', 'outdoor_forecast_is_not_interior_crop_dli',
        'validity_revision', 'dli-validity-v1',
        'valid_from', '2024-01-01T00:00:00Z',
        'valid_to', NULL
    ) AS dli_forecast,
    (
        SELECT json_object_agg(sub.parameter, sub.value)
        FROM (
            SELECT DISTINCT ON (s.parameter) s.parameter, s.value
            FROM public.setpoint_changes s
            ORDER BY s.parameter, s.ts DESC
        ) sub
    ) AS current_setpoints,
    (
        SELECT json_agg(row_to_json(sub.*) ORDER BY sub.ts)
        FROM (
            SELECT p.ts, p.parameter, p.value, p.reason
            FROM public.setpoint_plan p
            WHERE p.ts > now()
              AND p.is_active
              AND p.parameter <> 'plan_metadata'
            ORDER BY p.ts
        ) sub
    ) AS active_plan,
    (
        SELECT json_build_object(
            'composite_score', public.fn_system_health(),
            'components', (
                SELECT json_agg(json_build_object(
                    'component', h.component,
                    'score', h.score_pct
                ))
                FROM public.v_system_health_score h
            )
        )
    ) AS system_health,
    json_build_object(
        'electric_per_kwh', 0.111,
        'gas_per_therm', 0.83,
        'water_per_gal', 0.00484
    ) AS cost_rates;

COMMENT ON VIEW public.v_iris_planning_context IS
'Single-query Iris context with availability-bearing DLI. No outdoor forecast or legacy proxy is presented as measured interior crop light.';

CREATE OR REPLACE VIEW public.v_water_efficiency AS
SELECT
    ds.date,
    ds.water_used_gal,
    d.crop_dli_mol_m2_day AS dli_final,
    CASE
        WHEN d.crop_dli_mol_m2_day > 0
        THEN round((ds.water_used_gal / d.crop_dli_mol_m2_day)::numeric, 3)
    END AS gal_per_mol_dli,
    d.availability AS dli_availability,
    d.unavailable_reason AS dli_unavailable_reason,
    d.provenance AS dli_provenance,
    d.validity_revision AS dli_validity_revision,
    d.valid_from AS dli_valid_from,
    d.valid_to AS dli_valid_to
FROM public.daily_summary ds
LEFT JOIN public.v_dli_daily d
  ON d.date = ds.date
 AND d.greenhouse_id = COALESCE(ds.greenhouse_id, 'vallery')
WHERE ds.water_used_gal IS NOT NULL
ORDER BY ds.date;

COMMENT ON VIEW public.v_water_efficiency IS
'Water/DLI efficiency remains unavailable while crop DLI is unavailable; water evidence stays independently visible.';
