from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

from verdify_public import output_policy as policy

REPO_ROOT = Path(__file__).resolve().parents[1]
GUARD = REPO_ROOT / "scripts" / "check-public-output.py"
REMEDIATE = REPO_ROOT / "scripts" / "remediate-public-output.py"
GENERATED_MARKER = "[//]: # (auto-generated by scripts/generate-daily-plan.py; fixture)"


def _run(*args: object) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, *map(str, args)],
        capture_output=True,
        text=True,
        check=False,
    )


def _root_identity(root: Path) -> str:
    metadata = root.stat()
    material = f"public-output-root-v1:{metadata.st_dev}:{metadata.st_ino}".encode()
    return hashlib.sha256(material).hexdigest()


def _write_scanner_report(path: Path, root: Path, findings: list[dict[str, str]]) -> None:
    label = policy.redact_non_public_crop_references(root.name)
    identity = _root_identity(root)
    normalized = [
        {
            "root": label,
            "root_identity": identity,
            "path": finding["path"],
            "route": finding["route"],
            "reason": finding["reason"],
        }
        for finding in findings
    ]
    path.write_text(
        json.dumps(
            {
                "schema_version": 2,
                "roots": [{"label": label, "identity": identity}],
                "missing_roots": [],
                "routes": sorted({finding["route"] for finding in normalized}),
                "findings": normalized,
            }
        ),
        encoding="utf-8",
    )


def test_remediation_manifest_targets_only_marker_verified_historical_plans(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    root = tmp_path / "content"
    plans = root / "plans"
    plans.mkdir(parents=True)
    generated = plans / "2026-07-03.md"
    generated.write_text(f"{GENERATED_MARKER}\nGenerated {excluded} note.\n", encoding="utf-8")
    handwritten = plans / "2026-07-04.md"
    handwritten.write_text(f"Handwritten {excluded} note.\n", encoding="utf-8")
    invalid = plans / "2026-07-05.md"
    invalid.write_text(f"{GENERATED_MARKER}\nCost: USD NaN\n", encoding="utf-8")
    report = tmp_path / "report.json"
    manifest = tmp_path / "manifest.json"

    guard = _run(GUARD, "--root", root, "--json-report", report)
    assert guard.returncode == 1
    dry_run = _run(REMEDIATE, "--report", report, "--root", root, "--manifest", manifest)

    assert dry_run.returncode == 0, dry_run.stderr
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    by_date = {item["date"]: item for item in payload["items"]}
    assert by_date["2026-07-03"]["automatic_redaction_eligible"] is True
    assert by_date["2026-07-03"]["reason_classes"] == ["protected-reference"]
    assert by_date["2026-07-03"]["regenerate_command"] == [
        "python3",
        "scripts/generate-daily-plan.py",
        "--date",
        "2026-07-03",
    ]
    assert by_date["2026-07-04"]["action"] == "resolve_source_content"
    assert by_date["2026-07-05"]["action"] == "regenerate_generated_plan"
    assert excluded in generated.read_text(encoding="utf-8").casefold()


def test_explicit_offline_redaction_changes_only_eligible_generated_plan(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    root = tmp_path / "content"
    plans = root / "plans"
    plans.mkdir(parents=True)
    generated = plans / "2026-07-03.md"
    generated.write_text(f"{GENERATED_MARKER}\nGenerated {excluded} note.\n", encoding="utf-8")
    handwritten = plans / "2026-07-04.md"
    handwritten.write_text(f"Handwritten {excluded} note.\n", encoding="utf-8")
    report = tmp_path / "report.json"
    manifest = tmp_path / "manifest.json"
    assert _run(GUARD, "--root", root, "--json-report", report).returncode == 1

    applied = _run(
        REMEDIATE,
        "--report",
        report,
        "--root",
        root,
        "--manifest",
        manifest,
        "--apply-redaction",
    )

    assert applied.returncode == 0, applied.stderr
    assert excluded not in generated.read_text(encoding="utf-8").casefold()
    assert excluded in handwritten.read_text(encoding="utf-8").casefold()
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    by_date = {item["date"]: item for item in payload["items"]}
    assert by_date["2026-07-03"]["redaction_applied"] is True
    assert by_date["2026-07-04"]["redaction_applied"] is False


def test_remediation_rejects_same_root_final_and_intermediate_symlinks(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    for link_kind, date in (("final", "2026-07-06"), ("intermediate", "2026-07-07")):
        case = tmp_path / link_kind
        root = case / "content"
        real_plans = root / "real-plans"
        real_plans.mkdir(parents=True)
        target = real_plans / f"{date}.md"
        original = f"{GENERATED_MARKER}\nGenerated {excluded} note.\n"
        target.write_text(original, encoding="utf-8")
        if link_kind == "final":
            plans = root / "plans"
            plans.mkdir()
            (plans / f"{date}.md").symlink_to(target)
        else:
            (root / "plans").symlink_to(real_plans, target_is_directory=True)
        report = case / "report.json"
        manifest = case / "manifest.json"
        _write_scanner_report(
            report,
            root,
            [{"path": f"plans/{date}.md", "route": f"/plans/{date}", "reason": "content"}],
        )

        applied = _run(
            REMEDIATE,
            "--report",
            report,
            "--root",
            root,
            "--manifest",
            manifest,
            "--apply-redaction",
        )

        assert applied.returncode == 0, applied.stderr
        assert target.read_text(encoding="utf-8") == original
        item = json.loads(manifest.read_text(encoding="utf-8"))["items"][0]
        assert item["action"] == "resolve_source_content"
        assert item["route"] == f"/plans/{date}"
        assert item["reason_classes"] == ["protected-reference"]
        assert item["automatic_redaction_eligible"] is False
        assert item["redaction_applied"] is False


def test_remediation_rejects_symlinked_source_root(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    real_root = tmp_path / "real-content"
    plans = real_root / "plans"
    plans.mkdir(parents=True)
    target = plans / "2026-07-08.md"
    original = f"{GENERATED_MARKER}\nGenerated {excluded} note.\n"
    target.write_text(original, encoding="utf-8")
    linked_root = tmp_path / "linked-content"
    linked_root.symlink_to(real_root, target_is_directory=True)
    report = tmp_path / "report.json"
    manifest = tmp_path / "manifest.json"
    report.write_text('{"findings": []}\n', encoding="utf-8")

    applied = _run(
        REMEDIATE,
        "--report",
        report,
        "--root",
        linked_root,
        "--manifest",
        manifest,
        "--apply-redaction",
    )

    assert applied.returncode == 2
    assert "source root is missing" in applied.stderr
    assert not manifest.exists()
    assert target.read_text(encoding="utf-8") == original


def test_remediation_rejects_untrusted_report_fields_without_echoing_them(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    encoded = "".join(f"%{byte:02X}" for byte in excluded.encode())
    root = tmp_path / "content"
    root.mkdir()
    report = tmp_path / "report.json"
    manifest = tmp_path / "manifest.json"
    _write_scanner_report(
        report,
        root,
        [{"path": f"plans/{encoded}.md", "route": f"/plans/{encoded}", "reason": f"unknown-{encoded}"}],
    )

    proc = _run(REMEDIATE, "--report", report, "--root", root, "--manifest", manifest)

    output = proc.stdout + proc.stderr
    assert proc.returncode == 2
    assert not manifest.exists()
    assert excluded not in output.casefold()
    assert encoded.casefold() not in output.casefold()
    assert "unknown-" not in output


def test_remediation_rejects_encoded_traversal_and_overlong_fields(tmp_path):
    root = tmp_path / "content"
    root.mkdir()
    for name, path, reason in (
        ("traversal", "plans/%2E%2E/private.md", "content"),
        ("overlong", "plans/2026-07-09.md", "x" * 5000),
    ):
        report = tmp_path / f"{name}.json"
        manifest = tmp_path / f"{name}-manifest.json"
        _write_scanner_report(
            report,
            root,
            [{"path": path, "route": "/plans/private", "reason": reason}],
        )

        proc = _run(REMEDIATE, "--report", report, "--root", root, "--manifest", manifest)

        assert proc.returncode == 2
        assert not manifest.exists()
        assert path not in proc.stderr
        assert reason not in proc.stderr


def test_remediation_binds_report_to_root_and_validates_declared_routes(tmp_path):
    first = tmp_path / "first"
    second = tmp_path / "second"
    first.mkdir()
    second.mkdir()
    report = tmp_path / "report.json"
    manifest = tmp_path / "manifest.json"
    _write_scanner_report(
        report,
        first,
        [{"path": "plans/2026-07-10.md", "route": "/plans/2026-07-10", "reason": "content"}],
    )

    cross_root = _run(REMEDIATE, "--report", report, "--root", second, "--manifest", manifest)
    assert cross_root.returncode == 2
    assert not manifest.exists()

    payload = json.loads(report.read_text(encoding="utf-8"))
    payload["findings"][0]["route"] = "/tampered"
    payload["routes"] = ["/tampered"]
    report.write_text(json.dumps(payload), encoding="utf-8")
    tampered = _run(REMEDIATE, "--report", report, "--root", first, "--manifest", manifest)
    assert tampered.returncode == 2
    assert not manifest.exists()


def test_remediation_rejects_duplicate_nonfinite_oversized_and_hardlinked_reports(tmp_path):
    root = tmp_path / "content"
    root.mkdir()
    manifest = tmp_path / "manifest.json"
    cases = {
        "duplicate.json": '{"schema_version":2,"schema_version":2}\n',
        "nonfinite.json": '{"schema_version":NaN}\n',
    }
    for name, content in cases.items():
        report = tmp_path / name
        report.write_text(content, encoding="utf-8")
        proc = _run(REMEDIATE, "--report", report, "--root", root, "--manifest", manifest)
        assert proc.returncode == 2
        assert proc.stderr.strip() == "public-output remediation: invalid scanner report"
        assert not manifest.exists()

    oversized = tmp_path / "oversized.json"
    with oversized.open("wb") as report_file:
        report_file.truncate(8 * 1024 * 1024 + 1)
    proc = _run(REMEDIATE, "--report", oversized, "--root", root, "--manifest", manifest)
    assert proc.returncode == 2
    assert not manifest.exists()

    original = tmp_path / "report-original.json"
    original.write_text("{}", encoding="utf-8")
    linked = tmp_path / "report-linked.json"
    os.link(original, linked)
    proc = _run(REMEDIATE, "--report", linked, "--root", root, "--manifest", manifest)
    assert proc.returncode == 2
    assert not manifest.exists()


def test_remediation_rejects_hardlinked_source_and_reports_manifest_write_failure_generically(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    root = tmp_path / "content"
    plans = root / "plans"
    plans.mkdir(parents=True)
    source = plans / "2026-07-11.md"
    original = f"{GENERATED_MARKER}\nGenerated {excluded} note.\n"
    source.write_text(original, encoding="utf-8")
    os.link(source, plans / "alias.md")
    report = tmp_path / "report.json"
    assert _run(GUARD, "--root", root, "--json-report", report).returncode == 1
    manifest = tmp_path / "manifest.json"

    proc = _run(
        REMEDIATE,
        "--report",
        report,
        "--root",
        root,
        "--manifest",
        manifest,
        "--apply-redaction",
    )

    assert proc.returncode == 0
    assert source.read_text(encoding="utf-8") == original
    assert all(not item["redaction_applied"] for item in json.loads(manifest.read_text())["items"])

    manifest_directory = tmp_path / "private-manifest-name"
    manifest_directory.mkdir()
    write_failure = _run(
        REMEDIATE,
        "--report",
        report,
        "--root",
        root,
        "--manifest",
        manifest_directory,
    )
    assert write_failure.returncode == 2
    assert write_failure.stderr.strip() == "public-output remediation: manifest write failed"
    assert manifest_directory.name not in write_failure.stderr


def test_remediation_does_not_open_source_files_over_the_fixed_size_limit(tmp_path):
    excluded = next(iter(policy.PUBLIC_CROP_EXCLUDE_SLUGS))
    root = tmp_path / "content"
    plans = root / "plans"
    plans.mkdir(parents=True)
    source = plans / "2026-07-12.md"
    prefix = f"{GENERATED_MARKER}\nGenerated {excluded} note.\n".encode()
    source.write_bytes(prefix)
    with source.open("r+b") as source_file:
        source_file.truncate(16 * 1024 * 1024 + 1)
    report = tmp_path / "report.json"
    manifest = tmp_path / "manifest.json"
    assert _run(GUARD, "--root", root, "--json-report", report).returncode == 1

    proc = _run(
        REMEDIATE,
        "--report",
        report,
        "--root",
        root,
        "--manifest",
        manifest,
        "--apply-redaction",
    )

    assert proc.returncode == 0
    assert source.read_bytes()[: len(prefix)] == prefix
    item = json.loads(manifest.read_text(encoding="utf-8"))["items"][0]
    assert item["automatic_redaction_eligible"] is False
    assert item["redaction_applied"] is False
