"""#436: the vision CronJob mounts ConfigMap verdify-vision-src, generated by
deploy/k8s/vision/kustomization.yaml from COPIES under deploy/k8s/vision/src/
(kustomize's RootOnly load restrictor + ArgoCD forbid referencing files outside
the kustomization dir — same pattern as the firmware-twin shadow, see
test_19_firmware_twin_shadow_src_sync.py). This test enforces byte-identity so
the rendered ConfigMap can never silently drift from the canonical scripts/
config/templates sources — the exact drift that left the live CM carrying
k3s-portability fixes Git did not have.

It also fences the ADR-0021 pull-credential regression: the vision pod pulls
its zot-pinned digest with zot-origin-cluster-pull ONLY; reintroducing a GHCR
pull secret (the original #436 private-GHCR-401 failure mode) fails CI.
"""

from __future__ import annotations

from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
VISION = REPO / "deploy/k8s/vision"

# src/ copy  ->  canonical source
PAIRS = {
    "frigate-snapshot.py": "scripts/frigate-snapshot.py",
    "analyze-greenhouse-snapshot.py": "scripts/analyze-greenhouse-snapshot.py",
    "ai.yaml": "config/ai.yaml",
    "zones.yaml": "config/zones.yaml",
    "vision-analysis.j2": "templates/vision-analysis.j2",
}


@pytest.mark.parametrize("copy_name,canonical_rel", PAIRS.items())
def test_vision_src_is_byte_identical_to_canonical(copy_name: str, canonical_rel: str) -> None:
    copy = VISION / "src" / copy_name
    canonical = REPO / canonical_rel
    assert copy.exists(), f"vision src copy missing: {copy}"
    assert canonical.exists(), f"canonical source missing: {canonical}"
    assert copy.read_bytes() == canonical.read_bytes(), (
        f"{copy} has DRIFTED from {canonical}. The verdify-vision-src ConfigMap "
        f"must ship the exact canonical sources. Re-copy: cp {canonical_rel} "
        f"deploy/k8s/vision/src/{copy_name}"
    )


def test_vision_src_files_are_all_generated() -> None:
    """Every src/ file feeds the generator and vice versa — no orphan copies,
    no ConfigMap key that this suite does not fence."""
    kustomization = (VISION / "kustomization.yaml").read_text()
    on_disk = {p.name for p in (VISION / "src").iterdir()}
    assert on_disk == set(PAIRS), f"src/ contents {sorted(on_disk)} != fenced set {sorted(PAIRS)}"
    for name in PAIRS:
        assert f"src/{name}" in kustomization, f"src/{name} missing from configMapGenerator files"


def test_vision_cronjob_pull_credential_is_zot_only() -> None:
    """ADR-0021: GHCR is retired. The overlay pins the image to the zot origin,
    so zot-origin-cluster-pull is the only pull secret the pod may reference."""
    manifest = (VISION / "verdify-vision-cronjob.yaml").read_text()
    assert "zot-origin-cluster-pull" in manifest
    assert "ghcr-jvallery-readonly" not in manifest, (
        "the transitional GHCR pull secret was removed with #436 — a GHCR "
        "credential on this pod is the original private-GHCR-401 failure mode"
    )
