#!/bin/sh
# db/apply-migrations.sh — ledgered numbered-migration runner (#583 Lane B).
#
# Promotes the db/ledger/schema_migrations.sql design into a real populated-DB
# delivery path (audit §8.7): bootstraps the schema_migrations ledger if
# absent, optionally seeds the audited baseline (db/ledger/backfill_ledger.sql,
# generated by scripts/gen-ledger-backfill.sh), then applies every
# db/migrations/NNN-*.sql not present in the ledger, in filename order.
#
# Per pending file:
#   * ONE advisory lock (per-run key 'verdify-schema-migrations'):
#       - wrap-safe files: pg_advisory_xact_lock inside the psql
#         --single-transaction that also applies the file and stamps the row;
#       - self-committing files (own top-level BEGIN/COMMIT or commit-forcing
#         DDL): pg_advisory_lock held for the whole psql session (released at
#         session exit) — the file is NEVER wrapped (2026-05-30 incident /
#         scripts/check_migration_rollback_safety.py).
#   * verify filename+SHA-256 not already applied. The ledger keys on
#     (source, filename) + sha — NEVER on the leading number: the history has
#     duplicate numbers (031, 060, 070-074, 078) and gaps (001, 019, 067).
#   * psql -X -v ON_ERROR_STOP=1 with statement_timeout / lock_timeout /
#     idle_in_transaction_session_timeout bounded via PGOPTIONS.
#   * stamp the ledger row (sha256, duration_ms, applied_by) only on success.
#
# GUARD RAILS
#   * A populated DB (public.climate exists) with an EMPTY ledger refuses to
#     run unless VERDIFY_MIGRATE_ALLOW_BASELINE=1, which seeds the audited
#     baseline stamp first. This prevents blindly replaying 000-206 against a
#     production database that already carries them.
#   * A ledger row whose sha256 differs from the repo file is FATAL
#     (edited-in-place after apply).
#   * --plan prints the dry-run plan (bootstrap/baseline/pending files + shas)
#     and applies nothing.
#
# ENVIRONMENT
#   DB_HOST DB_NAME DB_USER DB_PASS   required (DB_PORT default 5432)
#   VERDIFY_MIGRATE_ALLOW_BASELINE=1  permit baseline seeding (see above)
#   VERDIFY_MIGRATIONS_DIR            default <script dir>/migrations
#   VERDIFY_LEDGER_DIR                default <script dir>/ledger
#   VERDIFY_SAFETY_CLASSIFIER         default <repo>/scripts/check_migration_rollback_safety.py
#   VERDIFY_MIGRATE_STATEMENT_TIMEOUT default 15min
#   VERDIFY_MIGRATE_LOCK_TIMEOUT      default 30s
#   VERDIFY_MIGRATE_IDLE_TX_TIMEOUT   default 5min
#
# This script authors NOTHING by itself at build time; it only ever runs
# inside the migrate image / an operator shell against the target DB.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
MIGRATIONS_DIR="${VERDIFY_MIGRATIONS_DIR:-${SCRIPT_DIR}/migrations}"
LEDGER_DIR="${VERDIFY_LEDGER_DIR:-${SCRIPT_DIR}/ledger}"
LEDGER_BOOTSTRAP="${LEDGER_DIR}/schema_migrations.sql"
LEDGER_BACKFILL="${LEDGER_DIR}/backfill_ledger.sql"
CLASSIFIER="${VERDIFY_SAFETY_CLASSIFIER:-${SCRIPT_DIR}/../scripts/check_migration_rollback_safety.py}"

PLAN=0
[ "${1:-}" = "--plan" ] && PLAN=1

: "${DB_HOST:?DB_HOST required}" "${DB_NAME:?DB_NAME required}" \
  "${DB_USER:?DB_USER required}" "${DB_PASS:?DB_PASS required}"
export PGPASSWORD="$DB_PASS"
export PGOPTIONS="-c statement_timeout=${VERDIFY_MIGRATE_STATEMENT_TIMEOUT:-15min} -c lock_timeout=${VERDIFY_MIGRATE_LOCK_TIMEOUT:-30s} -c idle_in_transaction_session_timeout=${VERDIFY_MIGRATE_IDLE_TX_TIMEOUT:-5min}"

PSQL="psql -X -h ${DB_HOST} -p ${DB_PORT:-5432} -U ${DB_USER} -d ${DB_NAME} -q -v ON_ERROR_STOP=1"

log() { echo "[apply-migrations] $*"; }
die() { echo "[apply-migrations] FATAL: $*" >&2; exit 1; }

q() { $PSQL -tA -c "$1"; }

[ -d "$MIGRATIONS_DIR" ] || die "migrations dir not found: $MIGRATIONS_DIR"
[ -f "$LEDGER_BOOTSTRAP" ] || die "ledger bootstrap SQL not found: $LEDGER_BOOTSTRAP"

# C0 ordinary-login transition must precede ANY bootstrap or per-file writes.
# Dispatch by source inventory, not presence of an attestor that could be missing
# or altered. Include the unqualified resource successor: a narrowed 248-only
# inventory must fail exact-profile admission, not escape into legacy delivery.
# Detection is not expansion of the immutable seven-file transition.
# No environment flag can opt back into the old C0 apply behavior.
for c0_candidate in "$MIGRATIONS_DIR"/24[1-8]*.sql; do
  [ -f "$c0_candidate" ] || continue
  C0_DELIVERY="${SCRIPT_DIR}/../scripts/c0-migration-delivery.py"
  [ -f "$C0_DELIVERY" ] || C0_DELIVERY="/scripts/c0-migration-delivery.py"
  [ -f "$C0_DELIVERY" ] || die "C0 delivery implementation missing; no per-file fallback"
  exec python3 "$C0_DELIVERY" --migrations-dir "$MIGRATIONS_DIR" "$@"
done

q "SELECT 1" >/dev/null || die "cannot reach ${DB_HOST}:${DB_PORT:-5432}/${DB_NAME}"

# ── 1. Ledger bootstrap ─────────────────────────────────────────────────────
HAVE_LEDGER=$(q "SELECT to_regclass('public.schema_migrations') IS NOT NULL")
if [ "$HAVE_LEDGER" != "t" ]; then
  if [ "$PLAN" = "1" ]; then
    log "PLAN: would bootstrap schema_migrations ledger from ${LEDGER_BOOTSTRAP}"
  else
    log "bootstrapping schema_migrations ledger ..."
    # schema_migrations.sql is self-transactional (own BEGIN/COMMIT): run as-is.
    $PSQL -f "$LEDGER_BOOTSTRAP"
    HAVE_LEDGER="t"
  fi
else
  # Re-run the bootstrap DDL: idempotent, and it carries the stamp_migration
  # signature / audit-column upgrades for pre-existing ledgers.
  if [ "$PLAN" = "1" ]; then
    log "PLAN: ledger present; would re-apply idempotent bootstrap DDL (upgrades)"
  else
    $PSQL -f "$LEDGER_BOOTSTRAP"
  fi
fi

# ── 2. Baseline guard / audited baseline seed ───────────────────────────────
POPULATED=$(q "SELECT to_regclass('public.climate') IS NOT NULL")
if [ "$HAVE_LEDGER" = "t" ]; then
  LEDGER_COUNT=$(q "SELECT count(*) FROM schema_migrations WHERE source = 'db/migrations'")
else
  LEDGER_COUNT=0
fi

NEED_BASELINE=0
if [ "$POPULATED" = "t" ] && [ "$LEDGER_COUNT" = "0" ]; then
  NEED_BASELINE=1
fi

if [ "$NEED_BASELINE" = "1" ]; then
  [ -f "$LEDGER_BACKFILL" ] || die "baseline needed but ${LEDGER_BACKFILL} is missing (run scripts/gen-ledger-backfill.sh)"
  if [ "${VERDIFY_MIGRATE_ALLOW_BASELINE:-0}" != "1" ]; then
    if [ "$PLAN" = "1" ]; then
      log "PLAN: populated DB with EMPTY ledger — a real run REQUIRES VERDIFY_MIGRATE_ALLOW_BASELINE=1 to seed the audited baseline (${LEDGER_BACKFILL})"
    else
      die "populated DB with EMPTY ledger. Refusing to apply numbered migrations blind. Set VERDIFY_MIGRATE_ALLOW_BASELINE=1 to seed the audited baseline (${LEDGER_BACKFILL}) first."
    fi
  else
    if [ "$PLAN" = "1" ]; then
      log "PLAN: would seed audited baseline from ${LEDGER_BACKFILL} (stamp_method=baseline)"
    else
      log "seeding audited baseline ledger (stamp_method=baseline) ..."
      # backfill_ledger.sql is self-transactional (own BEGIN/COMMIT): run as-is.
      $PSQL -f "$LEDGER_BACKFILL"
    fi
  fi
fi

# ── 3. Plan: diff repo files against the ledger ─────────────────────────────
# Filename order (LC_ALL=C sort): the '-' after the number sorts before the
# 'a' of suffixed duplicates (095-... < 095a-...), matching historical order.
# Duplicate NUMBERS are fine — identity is the full filename + sha.
PENDING=""
PENDING_COUNT=0
SKIPPED_COUNT=0

ledger_sha_of() {
  # $1 = full relative filename. Repo migration basenames are [0-9a-zA-Z._-]
  # only, so plain quoting is safe here.
  q "SELECT COALESCE(sha256, '<null>') FROM schema_migrations WHERE source = 'db/migrations' AND filename = '$1'"
}

FILES=$(cd "$MIGRATIONS_DIR" && LC_ALL=C ls -1 -- *.sql 2>/dev/null | LC_ALL=C sort) \
  || die "no *.sql files under ${MIGRATIONS_DIR}"

for base in $FILES; do
  rel="db/migrations/${base}"
  sha=$(sha256sum "${MIGRATIONS_DIR}/${base}" | cut -d' ' -f1)
  if [ "$HAVE_LEDGER" = "t" ]; then
    have=$(ledger_sha_of "$rel")
  else
    # plan mode before the ledger exists: everything is pending
    have=""
  fi
  case "$have" in
    "")
      PENDING="${PENDING} ${base}"
      PENDING_COUNT=$((PENDING_COUNT + 1))
      log "pending: ${base} sha256=${sha}"
      ;;
    "<null>")
      log "skip (ledgered, no sha recorded — baseline stamp): ${base}"
      SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
      ;;
    "$sha")
      SKIPPED_COUNT=$((SKIPPED_COUNT + 1))
      ;;
    *)
      die "${base}: ledger sha ${have} != repo sha ${sha} — migration file was edited after it was applied. Resolve by hand (never silently re-apply)."
      ;;
  esac
done

log "plan: ${PENDING_COUNT} pending, ${SKIPPED_COUNT} already ledgered"

if [ "$PLAN" = "1" ]; then
  log "PLAN complete — nothing applied."
  exit 0
fi
if [ "$PENDING_COUNT" = "0" ]; then
  log "ledger is current — nothing to apply."
  exit 0
fi

# ── 4. Apply each pending file ──────────────────────────────────────────────
seq_of() {
  # leading NNN (095a -> 95) or NULL
  n=$(printf '%s' "$1" | sed -E 's/^([0-9]+)[a-zA-Z]?-.*/\1/')
  case "$n" in
    ''|*[!0-9]*) printf 'NULL' ;;
    *)
      # POSIX sh has no base#number arithmetic (dash rejects even 10#241).
      # Strip zero padding before printf so 008/095 are not treated as octal.
      n=$(printf '%s' "$n" | sed 's/^0*//')
      printf '%d' "${n:-0}"
      ;;
  esac
}

is_wrap_safe() {
  # Exit 0 = safe to wrap in one transaction; 1 = self-committing.
  if command -v python3 >/dev/null 2>&1 && [ -f "$CLASSIFIER" ]; then
    python3 "$CLASSIFIER" --rollback-wrap "$1" >/dev/null 2>&1
    return $?
  fi
  # Conservative fallback (no python3): a top-level COMMIT at line start marks
  # the file self-committing. The image installs python3 so the exact
  # classifier is the normal path.
  if grep -Eqi '^[[:space:]]*COMMIT([[:space:]]+(WORK|TRANSACTION))?[[:space:]]*;' "$1"; then
    return 1
  fi
  return 0
}

TMPDIR_RUN=$(mktemp -d)
trap 'rm -rf "$TMPDIR_RUN"' EXIT

for base in $PENDING; do
  file="${MIGRATIONS_DIR}/${base}"
  rel="db/migrations/${base}"
  sha=$(sha256sum "$file" | cut -d' ' -f1)
  seq=$(seq_of "$base")
  script="${TMPDIR_RUN}/apply-${base}.psql"

  if is_wrap_safe "$file"; then
    LOCK_SQL="SELECT pg_advisory_xact_lock(hashtext('verdify-schema-migrations'));"
    WRAP_FLAG="--single-transaction"
    mode="wrap-safe (single transaction)"
  else
    LOCK_SQL="SELECT pg_advisory_lock(hashtext('verdify-schema-migrations'));"
    WRAP_FLAG=""
    mode="SELF-COMMITTING (applied unwrapped; session advisory lock)"
  fi

  cat > "$script" <<EOF
\\set ON_ERROR_STOP on
${LOCK_SQL}
SELECT clock_timestamp() AS verdify_t0 \\gset
DO \$guard\$
BEGIN
    IF EXISTS (SELECT 1 FROM schema_migrations
                WHERE source = 'db/migrations' AND filename = '${rel}') THEN
        RAISE EXCEPTION 'ledger race: ${rel} was applied concurrently';
    END IF;
END
\$guard\$;
\\i ${file}
SELECT stamp_migration(
    '${rel}', 'db/migrations', ${seq}, '${sha}', 'runner',
    (extract(epoch from clock_timestamp() - :'verdify_t0'::timestamptz) * 1000)::int,
    current_user);
EOF

  log "applying ${base} [${mode}] ..."
  $PSQL $WRAP_FLAG -f "$script" || die "${base} FAILED — ledger NOT stamped; fix and re-run (files are idempotent by convention)."

  # Post-apply assertion: the ledger row exists with the exact repo sha.
  stamped=$(ledger_sha_of "$rel")
  [ "$stamped" = "$sha" ] || die "${base}: post-apply ledger assertion failed (ledger='${stamped}', want '${sha}')"
  log "applied + stamped: ${base}"
done

log "done: applied ${PENDING_COUNT} migration(s); ledger is current."
