// AUTOGENERATED by scripts/gen-policy-vector-header.py — DO NOT EDIT.
// Source of truth: verdify_schemas/tunable_registry.py wire metadata
// (Lane A, #582; audit §8.9). Regenerate with:
//   python3 scripts/gen-policy-vector-header.py
// A pytest drift gate (verdify_schemas/tests/test_policy_vector.py) fails if
// this checked-in file differs from regenerated output.
//
// Canonical policy-vector wire codec, plain C++17, host-compilable, no
// ESPHome dependencies. All integers big-endian; i16 is two's complement;
// bool is one byte 0x00/0x01. See verdify_schemas/policy_vector.py for the
// authoritative format description.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>

#include "policy_sha256.h"

namespace verdify_policy {

constexpr uint8_t kWireSchemaVersion = 1;
constexpr uint8_t kPolicyFieldCount = 49;
constexpr size_t kPolicyVectorHeaderSize = 14;
constexpr size_t kPolicyVectorSize = 181;
constexpr uint8_t kPolicyVectorMagic[4] = {'V', 'P', 'V', '1'};

// Full SHA-256 of the RFC-8785-style canonical JSON serialization of the
// ordered wire manifest (2b1798fa811c03ecb91090c9d0f08c584bd34224ad26133db6d5535e9ddf6421).
constexpr uint8_t kWireManifestDigest[32] = {
    0x2b, 0x17, 0x98, 0xfa, 0x81, 0x1c, 0x03, 0xec, 0xb9, 0x10, 0x90, 0xc9,
    0xd0, 0xf0, 0x8c, 0x58, 0x4b, 0xd3, 0x42, 0x24, 0xad, 0x26, 0x13, 0x3d,
    0xb6, 0xd5, 0x53, 0x5e, 0x9d, 0xdf, 0x64, 0x21,
};

constexpr char kContentDomainTag[] = "verdify-policy-content-v1";
constexpr char kActivationDomainTag[] = "verdify-policy-activation-v1";

enum class WireKind : uint8_t { kU8, kU16, kI16, kU32, kBool };

struct PolicyFieldDef {
  uint16_t wire_id;
  WireKind kind;
  uint32_t scale;
  int64_t min_raw;
  int64_t max_raw;
  const char* name;
};

// Ordered by ascending permanent wire_id. Retired ids are never reused.
constexpr PolicyFieldDef kPolicyFields[kPolicyFieldCount] = {
    {1, WireKind::kU8, 20, 0, 20, "band_track_fraction"},
    {2, WireKind::kU8, 2, 0, 30, "cold_vent_guard_delta_f"},
    {3, WireKind::kU8, 10, 3, 30, "cool_exit_hysteresis_f"},
    {4, WireKind::kU8, 10, 3, 30, "cool_stage2_exit_hysteresis_f"},
    {5, WireKind::kU8, 10, 0, 30, "cool_stage2_over_high_f"},
    {6, WireKind::kU8, 1, 17, 24, "direct_wet_stress_latest_hour"},
    {7, WireKind::kU8, 2, 6, 30, "direct_wet_stress_min_dew_margin_f"},
    {8, WireKind::kU8, 20, 0, 10, "direct_wet_stress_vpd_margin_kpa"},
    {9, WireKind::kU32, 1, 60000, 1800000, "dwell_gate_ms"},
    {10, WireKind::kI16, 2, -10, 40, "enthalpy_close"},
    {11, WireKind::kI16, 2, -10, 0, "enthalpy_open"},
    {12, WireKind::kU8, 10, 1, 5, "fog_escalation_kpa"},
    {13, WireKind::kU8, 10, 0, 30, "heat_hysteresis"},
    {14, WireKind::kU16, 1, 30, 300, "min_fan_off_s"},
    {15, WireKind::kU16, 1, 30, 300, "min_fan_on_s"},
    {16, WireKind::kU16, 1, 15, 300, "min_fog_off_s"},
    {17, WireKind::kU16, 1, 15, 300, "min_fog_on_s"},
    {18, WireKind::kU16, 1, 60, 600, "min_heat_off_s"},
    {19, WireKind::kU16, 1, 30, 300, "min_heat_on_s"},
    {20, WireKind::kU16, 1, 10, 300, "min_vent_off_s"},
    {21, WireKind::kU16, 1, 10, 300, "min_vent_on_s"},
    {22, WireKind::kU16, 1, 60, 3600, "mist_backoff_s"},
    {23, WireKind::kU16, 1, 120, 900, "mist_max_closed_vent_s"},
    {24, WireKind::kU16, 1, 30, 300, "mist_thermal_relief_s"},
    {25, WireKind::kU16, 1, 60, 600, "mister_all_delay_s"},
    {26, WireKind::kU8, 20, 20, 50, "mister_all_kpa"},
    {27, WireKind::kU8, 10, 0, 10, "mister_center_penalty"},
    {28, WireKind::kU16, 1, 30, 300, "mister_engage_delay_s"},
    {29, WireKind::kU8, 20, 10, 50, "mister_engage_kpa"},
    {30, WireKind::kU8, 1, 30, 120, "mister_min_off_s"},
    {31, WireKind::kU8, 1, 10, 60, "mister_pulse_gap_s"},
    {32, WireKind::kU8, 1, 30, 90, "mister_pulse_on_s"},
    {33, WireKind::kU8, 2, 1, 6, "mister_vpd_weight"},
    {34, WireKind::kU16, 10, 1000, 3000, "mister_water_budget_gal"},
    {35, WireKind::kU8, 100, 0, 25, "night_vpd_bias_kpa"},
    {36, WireKind::kU16, 1, 120, 1800, "outdoor_staleness_max_s"},
    {37, WireKind::kBool, 1, 0, 1, "sw_cool_all_fans_at_high_enabled"},
    {38, WireKind::kBool, 1, 0, 1, "sw_direct_wet_gate_enabled"},
    {39, WireKind::kBool, 1, 0, 1, "sw_direct_wet_stress_override_enabled"},
    {40, WireKind::kBool, 1, 0, 1, "sw_dwell_gate_enabled"},
    {41, WireKind::kBool, 1, 0, 1, "sw_fog_closes_vent"},
    {42, WireKind::kBool, 1, 0, 1, "sw_mister_closes_vent"},
    {43, WireKind::kBool, 1, 0, 1, "sw_summer_vent_enabled"},
    {44, WireKind::kU8, 10, 5, 30, "temp_hysteresis"},
    {45, WireKind::kU8, 20, 2, 12, "vent_exchange_fraction"},
    {46, WireKind::kU8, 2, 4, 30, "vent_prefer_dp_delta_f"},
    {47, WireKind::kU8, 2, 4, 30, "vent_prefer_temp_delta_f"},
    {48, WireKind::kU8, 20, 1, 10, "vpd_hysteresis"},
    {49, WireKind::kU8, 1, 15, 120, "vpd_watch_dwell_s"},
};

inline size_t wire_kind_width(WireKind kind) {
  switch (kind) {
    case WireKind::kU8:
    case WireKind::kBool:
      return 1;
    case WireKind::kU16:
    case WireKind::kI16:
      return 2;
    case WireKind::kU32:
      return 4;
  }
  return 0;
}

inline double raw_to_value(const PolicyFieldDef& field, int64_t raw) {
  return static_cast<double>(raw) / static_cast<double>(field.scale);
}

// Encode 49 raw (scaled-integer) values, ordered like kPolicyFields, into the
// canonical byte vector. Returns false on out-of-bounds raws or a small
// output buffer; on success *out_len == kPolicyVectorSize.
inline bool encode_policy_vector(const int64_t raws[kPolicyFieldCount], uint8_t* out, size_t out_cap,
                                 size_t* out_len) {
  if (out == nullptr || out_cap < kPolicyVectorSize) return false;
  size_t offset = 0;
  std::memcpy(out + offset, kPolicyVectorMagic, sizeof(kPolicyVectorMagic));
  offset += sizeof(kPolicyVectorMagic);
  out[offset++] = kWireSchemaVersion;
  std::memcpy(out + offset, kWireManifestDigest, 8);
  offset += 8;
  out[offset++] = kPolicyFieldCount;
  for (size_t i = 0; i < kPolicyFieldCount; ++i) {
    const PolicyFieldDef& field = kPolicyFields[i];
    const int64_t raw = raws[i];
    if (raw < field.min_raw || raw > field.max_raw) return false;
    out[offset++] = static_cast<uint8_t>(field.wire_id >> 8);
    out[offset++] = static_cast<uint8_t>(field.wire_id);
    const size_t width = wire_kind_width(field.kind);
    const uint64_t bits = static_cast<uint64_t>(raw);  // two's complement for i16
    for (size_t b = 0; b < width; ++b) {
      out[offset++] = static_cast<uint8_t>(bits >> (8 * (width - 1 - b)));
    }
  }
  if (offset != kPolicyVectorSize) return false;
  if (out_len != nullptr) *out_len = offset;
  return true;
}

// Strict inverse of encode_policy_vector. Rejects bad magic/version/digest/
// count, unknown/duplicate/out-of-order wire_ids, out-of-bounds raw values,
// and trailing bytes.
inline bool decode_policy_vector(const uint8_t* data, size_t len, int64_t raws_out[kPolicyFieldCount]) {
  if (data == nullptr || len != kPolicyVectorSize) return false;
  if (std::memcmp(data, kPolicyVectorMagic, sizeof(kPolicyVectorMagic)) != 0) return false;
  size_t offset = sizeof(kPolicyVectorMagic);
  if (data[offset++] != kWireSchemaVersion) return false;
  if (std::memcmp(data + offset, kWireManifestDigest, 8) != 0) return false;
  offset += 8;
  if (data[offset++] != kPolicyFieldCount) return false;
  for (size_t i = 0; i < kPolicyFieldCount; ++i) {
    const PolicyFieldDef& field = kPolicyFields[i];
    const uint16_t wire_id = static_cast<uint16_t>((static_cast<uint16_t>(data[offset]) << 8) | data[offset + 1]);
    offset += 2;
    if (wire_id != field.wire_id) return false;  // unknown, duplicate, or out of order
    const size_t width = wire_kind_width(field.kind);
    uint64_t bits = 0;
    for (size_t b = 0; b < width; ++b) bits = (bits << 8) | data[offset++];
    int64_t raw = static_cast<int64_t>(bits);
    if (field.kind == WireKind::kI16 && (bits & 0x8000u) != 0) {
      raw = static_cast<int64_t>(bits) - 0x10000;
    }
    if (raw < field.min_raw || raw > field.max_raw) return false;
    if (raws_out != nullptr) raws_out[i] = raw;
  }
  return offset == len;
}

// content_sha256 = SHA-256(domain tag || 0x00 || schema version byte ||
// 32-byte manifest digest || canonical vector bytes || canonical JSON of the
// policy revision ids). The revision-id serialization is produced by
// verdify_schemas.policy_vector.canonical_revision_ids_bytes and passed here
// verbatim. Returns false unless the vector decodes canonically and
// schema_version matches its header byte.
inline bool content_sha256(const uint8_t* vector_bytes, size_t vector_len, uint8_t schema_version,
                           const uint8_t* revision_ids_json, size_t revision_ids_len, uint8_t out[32]) {
  int64_t raws[kPolicyFieldCount];
  if (!decode_policy_vector(vector_bytes, vector_len, raws)) return false;
  if (schema_version == 0 || schema_version != vector_bytes[4]) return false;
  if (revision_ids_json == nullptr || revision_ids_len == 0) return false;
  Sha256 ctx;
  ctx.update(kContentDomainTag, sizeof(kContentDomainTag) - 1);
  const uint8_t zero = 0x00;
  ctx.update(&zero, 1);
  ctx.update(&schema_version, 1);
  ctx.update(kWireManifestDigest, sizeof(kWireManifestDigest));
  ctx.update(vector_bytes, vector_len);
  ctx.update(revision_ids_json, revision_ids_len);
  ctx.finish(out);
  return true;
}

// §8.9 version-1 treatment octets. Off/shadow emits no activation hash, so
// empty treatment bytes are invalid — never a null sentinel.
inline bool validate_treatment_bytes(const uint8_t* treatment, size_t len) {
  if (treatment == nullptr || len == 0) return false;
  switch (treatment[0]) {
    case 0x01:  // randomized: 0x01 || 'X'/'Y'
      return len == 2 && (treatment[1] == 0x58 || treatment[1] == 0x59);
    case 0x02:  // qualification: 0x02 || op || src uuid(16) || dst uuid(16) || regime
      return len == 35 && treatment[1] >= 0x01 && treatment[1] <= 0x04 && treatment[34] <= 0x03;
    case 0x03:  // A/A: 0x03 || lane
      return len == 2 && treatment[1] <= 0x01;
    default:
      return false;
  }
}

// activation_sha256 = SHA-256(domain tag || 0x00 || content hash ||
// experiment uuid(16) || assignment uuid(16) || treatment length u8 ||
// treatment octets || generation u64 || valid_from_us u64 || valid_to_us u64).
inline bool activation_sha256(const uint8_t content_hash[32], const uint8_t experiment_id[16],
                              const uint8_t assignment_id[16], const uint8_t* treatment, size_t treatment_len,
                              uint64_t generation, uint64_t valid_from_us, uint64_t valid_to_us, uint8_t out[32]) {
  if (content_hash == nullptr || experiment_id == nullptr || assignment_id == nullptr) return false;
  if (!validate_treatment_bytes(treatment, treatment_len)) return false;
  if (valid_from_us >= valid_to_us) return false;
  Sha256 ctx;
  ctx.update(kActivationDomainTag, sizeof(kActivationDomainTag) - 1);
  const uint8_t zero = 0x00;
  ctx.update(&zero, 1);
  ctx.update(content_hash, 32);
  ctx.update(experiment_id, 16);
  ctx.update(assignment_id, 16);
  const uint8_t tlen = static_cast<uint8_t>(treatment_len);
  ctx.update(&tlen, 1);
  ctx.update(treatment, treatment_len);
  uint8_t u64_be[8];
  const uint64_t words[3] = {generation, valid_from_us, valid_to_us};
  for (const uint64_t word : words) {
    for (int b = 0; b < 8; ++b) u64_be[b] = static_cast<uint8_t>(word >> (56 - 8 * b));
    ctx.update(u64_be, 8);
  }
  ctx.finish(out);
  return true;
}

}  // namespace verdify_policy
