apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - activation-configmap.yaml
  - direct-proof-configmap.yaml
  - direct-proof-job.yaml

patches:
  - path: ingestor-activation.patch.yaml

images:
  - name: ghcr.io/verdifyconsultancy/verdify-api
