#!/usr/bin/env python3
"""Render the public source-owned Iris persona and required skill references."""

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FILES = {
    "SOUL.md": "hermes/iris/SOUL.md",
    "SKILL.md": "hermes/iris/SKILL.md",
    "seed-inventory.py": "hermes/iris/seed-inventory.py",
    "full-plan-payload-preflight.md": "hermes/iris/references/full-plan-payload-preflight.md",
    "greenhouse-playbook.md": "docs/planner/greenhouse-playbook.md",
}


def render():
    data = {name: (ROOT / path).read_text() for name, path in FILES.items()}
    # Hash the complete inventory, not just the unchanged model profile, so any
    # required reference update rolls/reseeds the singleton gateway.
    revision = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()[:12]
    lines = [
        "# Generated by scripts/gen-iris-inventory-cm.py; edit the source files.",
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        "  name: verdify-iris-inventory",
        "  labels:",
        "    app.kubernetes.io/part-of: verdify",
        "data:",
    ]
    for name, content in data.items():
        lines.append(f"  {name}: |")
        lines.extend("    " + line if line else "" for line in content.splitlines())
    return "\n".join(lines) + "\n", revision


if __name__ == "__main__":
    import re

    content, revision = render()
    (ROOT / "deploy/k8s/components/hermes-iris/iris-inventory.yaml").write_text(content)
    path = ROOT / "deploy/k8s/components/hermes-iris/hermes-iris.yaml"
    text = path.read_text()
    annotation = f'        verdify.io/iris-inventory-revision: "{revision}"'
    if "verdify.io/iris-inventory-revision:" in text:
        text = re.sub(r"        verdify.io/iris-inventory-revision:.*", annotation, text)
    else:
        text = text.replace(
            "        verdify.io/hermes-profile-revision:", annotation + "\n        verdify.io/hermes-profile-revision:"
        )
    path.write_text(text)
