#!/usr/bin/env bash
# scripts/gen-ledger-backfill.sh — generate the applied-migrations baseline
# backfill SQL from the actual repo contents. READ-ONLY: it reads migration
# files, computes sha256s, and writes db/ledger/backfill_ledger.sql. It applies
# nothing to any database.
#
# The output stamps every db/migrations/*.sql (full filename identity, so the
# duplicate/gapped numbers are preserved) plus the externally-tracked
# planner_graph/migrations/001_planner_memory.sql, all with stamp_method
# 'baseline'. Run db/ledger/schema_migrations.sql first to create the ledger;
# this backfill is the one-time provenance stamp for an existing prod DB.
#
# Usage:
#   scripts/gen-ledger-backfill.sh                # write db/ledger/backfill_ledger.sql
#   scripts/gen-ledger-backfill.sh --stdout       # print to stdout instead
#   PLANNER_MIGRATION=<path> scripts/gen-ledger-backfill.sh
#       (point at planner_graph/migrations/001_planner_memory.sql if present in
#        a sibling checkout; otherwise it is stamped sha256-less as a reference)

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/db/ledger/backfill_ledger.sql"
TO_STDOUT=0
[ "${1:-}" = "--stdout" ] && TO_STDOUT=1

# External planner-repo migration (lives in the verdify planner repo, not here).
PLANNER_MIGRATION="${PLANNER_MIGRATION:-planner_graph/migrations/001_planner_memory.sql}"

# Parse a leading "NNN" or "NNNa" prefix into an integer seq (95a -> 95).
seq_of() {
  local base num
  base="$(basename "$1")"
  num="$(printf '%s' "$base" | sed -E 's/^([0-9]+)[a-z]?-.*/\1/')"
  [[ "$num" =~ ^[0-9]+$ ]] && printf '%d' "$((10#$num))" || printf 'NULL'
}

emit() {
  echo "-- db/ledger/backfill_ledger.sql — GENERATED by scripts/gen-ledger-backfill.sh"
  echo "-- One-time baseline stamp of the existing applied migration set."
  echo "-- Identity = (source, filename). Re-running is idempotent (stamp_migration upserts)."
  echo "-- DO NOT hand-edit; regenerate after adding migrations."
  echo
  echo "BEGIN;"

  local f rel sha seq cnt=0
  for f in "${REPO_ROOT}"/db/migrations/*.sql; do
    rel="db/migrations/$(basename "$f")"
    sha="$(sha256sum "$f" | cut -d' ' -f1)"
    seq="$(seq_of "$f")"
    printf "SELECT stamp_migration('%s', 'db/migrations', %s, '%s', 'baseline');\n" \
      "$rel" "$seq" "$sha"
    cnt=$((cnt + 1))
  done

  # planner_graph migration: stamp with sha256 if the file is reachable in this
  # checkout, otherwise stamp as a reference (sha256 NULL) so the row exists.
  if [ -f "${REPO_ROOT}/${PLANNER_MIGRATION}" ]; then
    sha="$(sha256sum "${REPO_ROOT}/${PLANNER_MIGRATION}" | cut -d' ' -f1)"
    printf "SELECT stamp_migration('%s', 'planner_graph/migrations', 1, '%s', 'baseline');\n" \
      "$PLANNER_MIGRATION" "$sha"
  else
    printf "SELECT stamp_migration('%s', 'planner_graph/migrations', 1, NULL, 'baseline');\n" \
      "$PLANNER_MIGRATION"
  fi

  echo "COMMIT;"
  echo
  echo "-- stamped: ${cnt} db/migrations + 1 planner_graph migration"
}

if [ "$TO_STDOUT" = "1" ]; then
  emit
else
  emit > "$OUT"
  echo "wrote $OUT ($(grep -c stamp_migration "$OUT") stamp statements)"
fi
