#!/usr/bin/env python3
"""Generate the C++ policy-vector codec artifacts from the tunable registry.

Lane A of #582 (audit §8.9). Emits, deterministically:

- ``firmware/lib/policy_vector_generated.h`` — constexpr wire-schema table
  (wire_id, kind, scale, raw bounds, name), the embedded wire-manifest
  digest, and host-compilable C++17 encode/decode/content-hash/
  activation-hash helpers (no ESPHome dependencies).
- ``firmware/test/policy_vector_goldens_generated.inc`` — the golden
  fixtures from ``verdify_schemas/tests/fixtures/policy_vector_goldens.json``
  embedded as C arrays for ``firmware/test/test_policy_vector.cpp``.
- ``firmware/lib/policy_rom_baseline_generated.h`` — the immutable ROM
  baseline (Lane E, #586): registry-default raws, canonical vector bytes,
  revision-ids JSON, and content hash. Generation FAILS unless the computed
  content hash equals the ``registry_defaults`` golden's Python-computed
  hash, so the compiled-in fallback can never drift from the goldens.

Both files are checked in; ``verdify_schemas/tests/test_policy_vector.py``
regenerates them and fails on any byte drift. Run with ``--check`` to verify
without writing.
"""

from __future__ import annotations

import argparse
import json
import sys
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from verdify_schemas import policy_vector as pv  # noqa: E402
from verdify_schemas.tunable_registry import POLICY_WIRE_FIELD_COUNT, WIRE_SCHEMA_VERSION  # noqa: E402

HEADER_PATH = REPO_ROOT / "firmware" / "lib" / "policy_vector_generated.h"
GOLDENS_INC_PATH = REPO_ROOT / "firmware" / "test" / "policy_vector_goldens_generated.inc"
ROM_BASELINE_PATH = REPO_ROOT / "firmware" / "lib" / "policy_rom_baseline_generated.h"
FIXTURE_PATH = REPO_ROOT / "verdify_schemas" / "tests" / "fixtures" / "policy_vector_goldens.json"

_KIND_ENUM = {"u8": "kU8", "u16": "kU16", "i16": "kI16", "u32": "kU32", "bool": "kBool"}


def _byte_lines(data: bytes, indent: str, per_line: int = 12) -> str:
    lines = []
    for start in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02x}" for b in data[start : start + per_line])
        lines.append(f"{indent}{chunk},")
    return "\n".join(lines)


def _c_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate_header() -> str:
    digest = pv.wire_manifest_digest()
    rows = []
    for defn in pv.wire_fields():
        raw_lo, raw_hi = pv.wire_raw_bounds(defn)
        rows.append(
            f"    {{{defn.wire_id}, WireKind::{_KIND_ENUM[defn.wire_kind]}, {defn.wire_scale}, "
            f'{raw_lo}, {raw_hi}, "{defn.name}"}},'
        )
    table = "\n".join(rows)
    return f"""\
// AUTOGENERATED by scripts/gen-policy-vector-header.py — DO NOT EDIT.
// Source of truth: verdify_schemas/tunable_registry.py wire metadata
// (Lane A, #582; audit §8.9). Regenerate with:
//   python3 scripts/gen-policy-vector-header.py
// A pytest drift gate (verdify_schemas/tests/test_policy_vector.py) fails if
// this checked-in file differs from regenerated output.
//
// Canonical policy-vector wire codec, plain C++17, host-compilable, no
// ESPHome dependencies. All integers big-endian; i16 is two's complement;
// bool is one byte 0x00/0x01. See verdify_schemas/policy_vector.py for the
// authoritative format description.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>

#include "policy_sha256.h"

namespace verdify_policy {{

constexpr uint8_t kWireSchemaVersion = {WIRE_SCHEMA_VERSION};
constexpr uint8_t kPolicyFieldCount = {POLICY_WIRE_FIELD_COUNT};
constexpr size_t kPolicyVectorHeaderSize = {pv.POLICY_VECTOR_HEADER_SIZE};
constexpr size_t kPolicyVectorSize = {pv.POLICY_VECTOR_SIZE};
constexpr uint8_t kPolicyVectorMagic[4] = {{'V', 'P', 'V', '1'}};

// Full SHA-256 of the RFC-8785-style canonical JSON serialization of the
// ordered wire manifest ({digest.hex()}).
constexpr uint8_t kWireManifestDigest[32] = {{
{_byte_lines(digest, "    ")}
}};

constexpr char kContentDomainTag[] = "verdify-policy-content-v1";
constexpr char kActivationDomainTag[] = "verdify-policy-activation-v1";

enum class WireKind : uint8_t {{ kU8, kU16, kI16, kU32, kBool }};

struct PolicyFieldDef {{
  uint16_t wire_id;
  WireKind kind;
  uint32_t scale;
  int64_t min_raw;
  int64_t max_raw;
  const char* name;
}};

// Ordered by ascending permanent wire_id. Retired ids are never reused.
constexpr PolicyFieldDef kPolicyFields[kPolicyFieldCount] = {{
{table}
}};

inline size_t wire_kind_width(WireKind kind) {{
  switch (kind) {{
    case WireKind::kU8:
    case WireKind::kBool:
      return 1;
    case WireKind::kU16:
    case WireKind::kI16:
      return 2;
    case WireKind::kU32:
      return 4;
  }}
  return 0;
}}

inline double raw_to_value(const PolicyFieldDef& field, int64_t raw) {{
  return static_cast<double>(raw) / static_cast<double>(field.scale);
}}

// Encode kPolicyFieldCount raw (scaled-integer) values, ordered like kPolicyFields, into the
// canonical byte vector. Returns false on out-of-bounds raws or a small
// output buffer; on success *out_len == kPolicyVectorSize.
inline bool encode_policy_vector(const int64_t raws[kPolicyFieldCount], uint8_t* out, size_t out_cap,
                                 size_t* out_len) {{
  if (out == nullptr || out_cap < kPolicyVectorSize) return false;
  size_t offset = 0;
  std::memcpy(out + offset, kPolicyVectorMagic, sizeof(kPolicyVectorMagic));
  offset += sizeof(kPolicyVectorMagic);
  out[offset++] = kWireSchemaVersion;
  std::memcpy(out + offset, kWireManifestDigest, 8);
  offset += 8;
  out[offset++] = kPolicyFieldCount;
  for (size_t i = 0; i < kPolicyFieldCount; ++i) {{
    const PolicyFieldDef& field = kPolicyFields[i];
    const int64_t raw = raws[i];
    if (raw < field.min_raw || raw > field.max_raw) return false;
    out[offset++] = static_cast<uint8_t>(field.wire_id >> 8);
    out[offset++] = static_cast<uint8_t>(field.wire_id);
    const size_t width = wire_kind_width(field.kind);
    const uint64_t bits = static_cast<uint64_t>(raw);  // two's complement for i16
    for (size_t b = 0; b < width; ++b) {{
      out[offset++] = static_cast<uint8_t>(bits >> (8 * (width - 1 - b)));
    }}
  }}
  if (offset != kPolicyVectorSize) return false;
  if (out_len != nullptr) *out_len = offset;
  return true;
}}

// Strict inverse of encode_policy_vector. Rejects bad magic/version/digest/
// count, unknown/duplicate/out-of-order wire_ids, out-of-bounds raw values,
// and trailing bytes.
inline bool decode_policy_vector(const uint8_t* data, size_t len, int64_t raws_out[kPolicyFieldCount]) {{
  if (data == nullptr || len != kPolicyVectorSize) return false;
  if (std::memcmp(data, kPolicyVectorMagic, sizeof(kPolicyVectorMagic)) != 0) return false;
  size_t offset = sizeof(kPolicyVectorMagic);
  if (data[offset++] != kWireSchemaVersion) return false;
  if (std::memcmp(data + offset, kWireManifestDigest, 8) != 0) return false;
  offset += 8;
  if (data[offset++] != kPolicyFieldCount) return false;
  for (size_t i = 0; i < kPolicyFieldCount; ++i) {{
    const PolicyFieldDef& field = kPolicyFields[i];
    const uint16_t wire_id = static_cast<uint16_t>((static_cast<uint16_t>(data[offset]) << 8) | data[offset + 1]);
    offset += 2;
    if (wire_id != field.wire_id) return false;  // unknown, duplicate, or out of order
    const size_t width = wire_kind_width(field.kind);
    uint64_t bits = 0;
    for (size_t b = 0; b < width; ++b) bits = (bits << 8) | data[offset++];
    int64_t raw = static_cast<int64_t>(bits);
    if (field.kind == WireKind::kI16 && (bits & 0x8000u) != 0) {{
      raw = static_cast<int64_t>(bits) - 0x10000;
    }}
    if (raw < field.min_raw || raw > field.max_raw) return false;
    if (raws_out != nullptr) raws_out[i] = raw;
  }}
  return offset == len;
}}

// content_sha256 = SHA-256(domain tag || 0x00 || schema version byte ||
// 32-byte manifest digest || canonical vector bytes || canonical JSON of the
// policy revision ids). The revision-id serialization is produced by
// verdify_schemas.policy_vector.canonical_revision_ids_bytes and passed here
// verbatim. Returns false unless the vector decodes canonically and
// schema_version matches its header byte.
inline bool content_sha256(const uint8_t* vector_bytes, size_t vector_len, uint8_t schema_version,
                           const uint8_t* revision_ids_json, size_t revision_ids_len, uint8_t out[32]) {{
  int64_t raws[kPolicyFieldCount];
  if (!decode_policy_vector(vector_bytes, vector_len, raws)) return false;
  if (schema_version == 0 || schema_version != vector_bytes[4]) return false;
  if (revision_ids_json == nullptr || revision_ids_len == 0) return false;
  Sha256 ctx;
  ctx.update(kContentDomainTag, sizeof(kContentDomainTag) - 1);
  const uint8_t zero = 0x00;
  ctx.update(&zero, 1);
  ctx.update(&schema_version, 1);
  ctx.update(kWireManifestDigest, sizeof(kWireManifestDigest));
  ctx.update(vector_bytes, vector_len);
  ctx.update(revision_ids_json, revision_ids_len);
  ctx.finish(out);
  return true;
}}

// §8.9 version-1 treatment octets. Off/shadow emits no activation hash, so
// empty treatment bytes are invalid — never a null sentinel.
inline bool validate_treatment_bytes(const uint8_t* treatment, size_t len) {{
  if (treatment == nullptr || len == 0) return false;
  switch (treatment[0]) {{
    case 0x01:  // randomized: 0x01 || 'X'/'Y'
      return len == 2 && (treatment[1] == 0x58 || treatment[1] == 0x59);
    case 0x02:  // qualification: 0x02 || op || src uuid(16) || dst uuid(16) || regime
      return len == 35 && treatment[1] >= 0x01 && treatment[1] <= 0x04 && treatment[34] <= 0x03;
    case 0x03:  // A/A: 0x03 || lane
      return len == 2 && treatment[1] <= 0x01;
    default:
      return false;
  }}
}}

// activation_sha256 = SHA-256(domain tag || 0x00 || content hash ||
// experiment uuid(16) || assignment uuid(16) || treatment length u8 ||
// treatment octets || generation u64 || valid_from_us u64 || valid_to_us u64).
inline bool activation_sha256(const uint8_t content_hash[32], const uint8_t experiment_id[16],
                              const uint8_t assignment_id[16], const uint8_t* treatment, size_t treatment_len,
                              uint64_t generation, uint64_t valid_from_us, uint64_t valid_to_us, uint8_t out[32]) {{
  if (content_hash == nullptr || experiment_id == nullptr || assignment_id == nullptr) return false;
  if (!validate_treatment_bytes(treatment, treatment_len)) return false;
  if (valid_from_us >= valid_to_us) return false;
  Sha256 ctx;
  ctx.update(kActivationDomainTag, sizeof(kActivationDomainTag) - 1);
  const uint8_t zero = 0x00;
  ctx.update(&zero, 1);
  ctx.update(content_hash, 32);
  ctx.update(experiment_id, 16);
  ctx.update(assignment_id, 16);
  const uint8_t tlen = static_cast<uint8_t>(treatment_len);
  ctx.update(&tlen, 1);
  ctx.update(treatment, treatment_len);
  uint8_t u64_be[8];
  const uint64_t words[3] = {{generation, valid_from_us, valid_to_us}};
  for (const uint64_t word : words) {{
    for (int b = 0; b < 8; ++b) u64_be[b] = static_cast<uint8_t>(word >> (56 - 8 * b));
    ctx.update(u64_be, 8);
  }}
  ctx.finish(out);
  return true;
}}

}}  // namespace verdify_policy
"""


def generate_goldens_inc() -> str:
    fixture = json.loads(FIXTURE_PATH.read_text())
    vectors = fixture["vectors"]
    treatments = fixture["treatments"]
    ctx = fixture["activation_context"]
    treatment_names = list(treatments)
    max_treatment_len = max(len(bytes.fromhex(h)) for h in treatments.values())

    out: list[str] = []
    out.append("// AUTOGENERATED by scripts/gen-policy-vector-header.py — DO NOT EDIT.")
    out.append("// Embedded from verdify_schemas/tests/fixtures/policy_vector_goldens.json")
    out.append("// for firmware/test/test_policy_vector.cpp (Lane A, #582).")
    out.append(f"static const size_t kGoldenVectorCount = {len(vectors)};")
    out.append(f"static const size_t kGoldenTreatmentCount = {len(treatments)};")
    out.append(f"static const size_t kGoldenMaxTreatmentLen = {max_treatment_len};")
    out.append(f"static const char kGoldenRevisionIdsJson[] = {_c_string(fixture['revision_ids_canonical_json'])};")
    digest = bytes.fromhex(fixture["wire_manifest_digest_sha256"])
    out.append("static const uint8_t kGoldenManifestDigest[32] = {")
    out.append(_byte_lines(digest, "    "))
    out.append("};")
    for label, key in (("ExperimentId", "experiment_id"), ("AssignmentId", "assignment_id")):
        out.append(f"static const uint8_t kGolden{label}[16] = {{")
        out.append(_byte_lines(uuid.UUID(ctx[key]).bytes, "    "))
        out.append("};")
    out.append(f"static const uint64_t kGoldenGeneration = {ctx['generation']}ULL;")
    out.append(f"static const uint64_t kGoldenValidFromUs = {ctx['valid_from_us']}ULL;")
    out.append(f"static const uint64_t kGoldenValidToUs = {ctx['valid_to_us']}ULL;")

    names = ", ".join(_c_string(name) for name in treatment_names)
    out.append(f"static const char* kGoldenTreatmentNames[kGoldenTreatmentCount] = {{{names}}};")
    lens = ", ".join(str(len(bytes.fromhex(treatments[n]))) for n in treatment_names)
    out.append(f"static const size_t kGoldenTreatmentLens[kGoldenTreatmentCount] = {{{lens}}};")
    out.append("static const uint8_t kGoldenTreatmentBytes[kGoldenTreatmentCount][kGoldenMaxTreatmentLen] = {")
    for name in treatment_names:
        raw = bytes.fromhex(treatments[name]).ljust(max_treatment_len, b"\x00")
        out.append(f"    {{  // {name}")
        out.append(_byte_lines(raw, "        "))
        out.append("    },")
    out.append("};")

    vec_names = ", ".join(_c_string(vec["name"]) for vec in vectors)
    out.append(f"static const char* kGoldenVectorNames[kGoldenVectorCount] = {{{vec_names}}};")
    out.append(f"static const int64_t kGoldenRaws[kGoldenVectorCount][{POLICY_WIRE_FIELD_COUNT}] = {{")
    for vec in vectors:
        raws = ", ".join(str(raw) for raw in vec["raws_by_wire_id"])
        out.append(f"    {{{raws}}},  // {vec['name']}")
    out.append("};")
    out.append(f"static const uint8_t kGoldenVectorBytes[kGoldenVectorCount][{fixture['vector_size']}] = {{")
    for vec in vectors:
        out.append(f"    {{  // {vec['name']}")
        out.append(_byte_lines(bytes.fromhex(vec["vector_hex"]), "        "))
        out.append("    },")
    out.append("};")
    out.append("static const uint8_t kGoldenContentSha[kGoldenVectorCount][32] = {")
    for vec in vectors:
        out.append(f"    {{  // {vec['name']}")
        out.append(_byte_lines(bytes.fromhex(vec["content_sha256"]), "        "))
        out.append("    },")
    out.append("};")
    out.append("static const uint8_t kGoldenActivationSha[kGoldenVectorCount][kGoldenTreatmentCount][32] = {")
    for vec in vectors:
        out.append(f"    {{  // {vec['name']}")
        for name in treatment_names:
            out.append(f"        {{  // {name}")
            out.append(_byte_lines(bytes.fromhex(vec["activation_sha256"][name]), "            "))
            out.append("        },")
        out.append("    },")
    out.append("};")
    return "\n".join(out) + "\n"


def generate_rom_baseline() -> str:
    """Immutable ROM-baseline header (Lane E, #586; audit §8.9).

    Values are the registry defaults; the content hash is pinned to the
    Python-computed ``registry_defaults`` golden — generation fails on any
    mismatch, so firmware, Python, and the goldens can never disagree about
    the manifest-independent fallback identity.
    """
    fixture = json.loads(FIXTURE_PATH.read_text())
    defaults = {
        defn.name: (bool(defn.default) if defn.wire_kind == "bool" else float(defn.default))
        for defn in pv.wire_fields()
    }
    raws = pv._raws_from_values(defaults)
    vector_bytes = pv.encode_policy_vector(defaults)
    revision_ids = fixture["revision_ids"]
    revision_json = fixture["revision_ids_canonical_json"]
    assert pv.canonical_revision_ids_bytes(revision_ids).decode() == revision_json
    content = pv.content_sha256(vector_bytes, schema_version=WIRE_SCHEMA_VERSION, policy_revision_ids=revision_ids)
    golden_defaults = next(vec for vec in fixture["vectors"] if vec["name"] == "registry_defaults")
    if content.hex() != golden_defaults["content_sha256"]:
        raise SystemExit(
            "ROM baseline content hash does not match the registry_defaults golden "
            f"({content.hex()} != {golden_defaults['content_sha256']}); regenerate the goldens first"
        )
    if vector_bytes.hex() != golden_defaults["vector_hex"]:
        raise SystemExit("ROM baseline vector bytes do not match the registry_defaults golden")
    raws_str = ", ".join(str(raw) for raw in raws)
    index_lines = "\n".join(
        f"constexpr uint8_t kPF_{defn.name} = {index};" for index, defn in enumerate(pv.wire_fields())
    )
    return f"""\
// AUTOGENERATED by scripts/gen-policy-vector-header.py — DO NOT EDIT.
// Immutable ROM baseline for the firmware policy engine (Lane E, #586;
// audit §8.9). Values are the tunable-registry defaults; the content hash is
// generation-time pinned to the Python-computed "registry_defaults" golden in
// verdify_schemas/tests/fixtures/policy_vector_goldens.json, so the compiled
// fallback identity can never drift from the cross-language goldens.
#pragma once

#include <cstddef>
#include <cstdint>

#include "policy_vector_generated.h"

namespace verdify_policy {{

// Canonical revision ids bound into the ROM baseline content hash.
constexpr char kRomBaselineRevisionIdsJson[] = {_c_string(revision_json)};

// Snapshot/table index (kPolicyFields order == ascending wire_id) per field.
{index_lines}

// Registry-default raw (scaled-integer) values, ordered by ascending wire_id.
constexpr int64_t kRomBaselineRaws[kPolicyFieldCount] = {{{raws_str}}};

// Canonical encoded vector bytes for the registry defaults.
constexpr uint8_t kRomBaselineVectorBytes[kPolicyVectorSize] = {{
{_byte_lines(vector_bytes, "    ")}
}};

// content_sha256 of the ROM baseline (== the registry_defaults golden).
constexpr uint8_t kRomBaselineContentSha256[32] = {{
{_byte_lines(content, "    ")}
}};

}}  // namespace verdify_policy
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify checked-in files match regenerated output")
    args = parser.parse_args()

    outputs = {
        HEADER_PATH: generate_header(),
        GOLDENS_INC_PATH: generate_goldens_inc(),
        ROM_BASELINE_PATH: generate_rom_baseline(),
    }
    drift = []
    for path, content in outputs.items():
        if args.check:
            current = path.read_text() if path.exists() else None
            if current != content:
                drift.append(str(path.relative_to(REPO_ROOT)))
        else:
            path.write_text(content)
            print(f"wrote {path.relative_to(REPO_ROOT)}")
    if drift:
        print("DRIFT: regenerate with python3 scripts/gen-policy-vector-header.py:", ", ".join(drift))
        return 1
    if args.check:
        print("generated policy-vector artifacts are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
