#!/usr/bin/env python3
"""Generate db/migrations/177 from verdify_schemas/band_defaults.yaml.

The band defaults have ONE canonical home (band_defaults.yaml). This generator
emits the forward seed/reconcile migration so the committed SQL is never
hand-typed and can't silently drift from the canonical file. A CI freshness
guard (test_band_defaults_single_source.py) asserts the committed migration ==
this generator's output.

Semantics: INSERT ... ON CONFLICT DO UPDATE ... WHERE the value actually
differs. On prod (where crop_band_anchors already == canonical, i.e. the live
band) this updates ZERO rows — a true no-op. On a fresh DB / CI replay (where
migration 168 left orchid vpd_target at 1.05 etc.) it aligns the rows to the
canonical live band, capturing the ad-hoc prod edits that never had a migration.

Usage:
    python scripts/gen_band_seed_sql.py            # print SQL to stdout
    python scripts/gen_band_seed_sql.py --write    # (re)write the migration file
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parent.parent
_YAML = _REPO / "verdify_schemas" / "band_defaults.yaml"
_MIGRATION = _REPO / "db" / "migrations" / "177-band-defaults-from-canonical-seed.sql"
_ANCHORS = ("sr", "sm", "ss", "mid")


def _fmt(v: float) -> str:
    # Stable, diff-friendly numeric rendering: ints without a trailing .0.
    return str(int(v)) if float(v).is_integer() else repr(float(v))


def _rows_house(defaults: dict) -> list[str]:
    rows: list[str] = []
    for series, vec in defaults["house"].items():
        cells = ", ".join(f"('house','{series}','{a}',{_fmt(v)})" for a, v in zip(_ANCHORS, vec, strict=True))
        rows.append(f"  {cells}")
    return rows


def _rows_zones(defaults: dict) -> list[str]:
    rows: list[str] = []
    for zone in defaults["zones"].values():
        crop, vec = zone["crop"], zone["vpd_target"]
        wb, wa = _fmt(zone["width_below"]), _fmt(zone["width_above"])
        cells = ", ".join(
            f"('{crop}','vpd_target','{a}',{_fmt(v)},{wb},{wa})" for a, v in zip(_ANCHORS, vec, strict=True)
        )
        rows.append(f"  {cells}")
    return rows


def generate() -> str:
    defaults = yaml.safe_load(_YAML.read_text(encoding="utf-8"))
    conflict = "(crop_type, growth_stage, season, series, anchor, greenhouse_id)"
    house = ",\n".join(_rows_house(defaults))
    zones = ",\n".join(_rows_zones(defaults))
    return f"""\
-- 177-band-defaults-from-canonical-seed.sql
-- GENERATED by scripts/gen_band_seed_sql.py from verdify_schemas/band_defaults.yaml.
-- DO NOT hand-edit — change band_defaults.yaml and re-run `--write`.
--
-- Purpose: make crop_band_anchors agree with the ONE canonical band declaration.
-- The migration-replay history diverged from live prod via ad-hoc UPDATEs that
-- never had a migration (e.g. migration 168 left orchid vpd_target at
-- 1.05/1.10/1.05/1.05, but live prod is 0.90/1.10/0.90/0.70). This forward
-- reconcile captures those live edits as committed truth.
--
-- Safety: ON CONFLICT DO UPDATE ... WHERE the value/width actually DIFFERS, so on
-- prod (already == canonical) this updates ZERO rows — a verified no-op. On a
-- fresh DB / CI replay it aligns the rows to the canonical live band. Advisory
-- per-crop temp_target rows are intentionally untouched.
--
-- Non-self-transactional (no top-level BEGIN/COMMIT, no CONCURRENTLY): safe to
-- rollback-validate by wrapping in BEGIN; ... ROLLBACK;.

-- House air band (value-only; widths are NULL on house rows).
INSERT INTO public.crop_band_anchors (crop_type, series, anchor, value) VALUES
{house}
ON CONFLICT {conflict} DO UPDATE SET value = EXCLUDED.value
  WHERE public.crop_band_anchors.value IS DISTINCT FROM EXCLUDED.value;

-- Per-zone VPD-target band (value + half-widths).
INSERT INTO public.crop_band_anchors (crop_type, series, anchor, value, width_below, width_above) VALUES
{zones}
ON CONFLICT {conflict} DO UPDATE SET
    value = EXCLUDED.value,
    width_below = EXCLUDED.width_below,
    width_above = EXCLUDED.width_above
  WHERE public.crop_band_anchors.value IS DISTINCT FROM EXCLUDED.value
     OR public.crop_band_anchors.width_below IS DISTINCT FROM EXCLUDED.width_below
     OR public.crop_band_anchors.width_above IS DISTINCT FROM EXCLUDED.width_above;

-- Post-reconcile assertion: every canonical row now equals the declaration.
DO $assert$
DECLARE
    n_mismatch int;
BEGIN
    SELECT count(*) INTO n_mismatch FROM (VALUES
{_assert_values(defaults)}
    ) AS want(crop_type, series, anchor, value)
    JOIN public.crop_band_anchors a USING (crop_type, series, anchor)
    WHERE a.greenhouse_id = 'vallery' AND a.value IS DISTINCT FROM want.value;
    IF n_mismatch > 0 THEN
        RAISE EXCEPTION '177: % canonical band row(s) failed to reconcile to band_defaults.yaml', n_mismatch;
    END IF;
    RAISE NOTICE '177: crop_band_anchors reconciled to canonical band_defaults.yaml';
END
$assert$;
"""


def _assert_values(defaults: dict) -> str:
    cells: list[str] = []
    for series, vec in defaults["house"].items():
        for a, v in zip(_ANCHORS, vec, strict=True):
            cells.append(f"      ('house','{series}','{a}',{_fmt(v)}::double precision)")
    for zone in defaults["zones"].values():
        crop, vec = zone["crop"], zone["vpd_target"]
        for a, v in zip(_ANCHORS, vec, strict=True):
            cells.append(f"      ('{crop}','vpd_target','{a}',{_fmt(v)}::double precision)")
    return ",\n".join(cells)


def main() -> int:
    sql = generate()
    if "--write" in sys.argv:
        _MIGRATION.write_text(sql, encoding="utf-8")
        sys.stderr.write(f"wrote {_MIGRATION}\n")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
