#!/usr/bin/env bash
# publish-site-content.sh — regenerate all generated lab.verdify.ai content and rebuild.
#
# This is the single production entry point for public site refreshes. Planner
# publishes, forecast refreshes, and manual full refreshes should call this
# script instead of invoking individual page generators directly.
set -euo pipefail

export LAB_LOCAL_TIMEZONE="${LAB_LOCAL_TIMEZONE:-America/Denver}"
export TZ="$LAB_LOCAL_TIMEZONE"

DATE=$(date +%Y-%m-%d)
REASON="manual"
REBUILD=true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --date)
      DATE="$2"
      shift 2
      ;;
    --reason)
      REASON="$2"
      shift 2
      ;;
    --no-rebuild)
      REBUILD=false
      shift
      ;;
    -h|--help)
      cat <<'EOF'
Usage: publish-site-content.sh [--date YYYY-MM-DD] [--reason NAME] [--no-rebuild]

Regenerates generated public content, updates planner static context, and
rebuilds the Quartz site unless --no-rebuild is provided.
EOF
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      exit 2
      ;;
  esac
done

reason_class() {
  case "$1" in
    "") printf 'unspecified' ;;
    manual) printf 'manual' ;;
    k3s-publisher|cron|scheduled*) printf 'scheduled' ;;
    *planner*|plan-*) printf 'planner' ;;
    *forecast*) printf 'forecast' ;;
    *) printf 'custom' ;;
  esac
}

REASON_CLASS="$(reason_class "$REASON")"

SCRIPT_ROOT=${VERDIFY_SCRIPT_ROOT:-/srv/verdify/scripts}
PYTHON=${PYTHON:-python3}
LOG=${VERDIFY_PUBLISH_LOG:-/srv/verdify/state/publish.log}
LOCK=${VERDIFY_PUBLISH_LOCK:-/var/lock/verdify-site-content-publish.lock}
PUBLIC_OUTPUT_REPORT=${VERDIFY_PUBLIC_OUTPUT_REPORT:-/srv/verdify/state/public-output-source-report.json}
PUBLIC_CONTENT_ROOT=${VERDIFY_PUBLIC_CONTENT_ROOT:-/srv/verdify/verdify-site/content}
if ! PREV_DATE=$(date -d "${DATE} -1 day" +%Y-%m-%d 2>/dev/null); then
  PREV_DATE=$(date -j -f "%Y-%m-%d" "$DATE" -v-1d +%Y-%m-%d)
fi

# Bounded retry/timeout guard (issue #59). The generators below make outbound
# HTTPS calls (e.g. update-evidence-snapshots.py hits https://api.verdify.ai).
# A transient egress timeout used to wedge the whole oneshot unit
# (verdify-forecast-page / verdify-plan-publish) into a failed state. Each step
# now runs under a hard wall-clock timeout and is retried a bounded number of
# times; a step that exhausts its retries is logged loudly and recorded as a
# failure but does NOT abort the remaining generators, so one flaky upstream
# does not leave the units failed. The unit exits non-zero at the end iff a
# step ultimately failed, so genuine breakage is still surfaced to systemd.
STEP_TIMEOUT=${VERDIFY_PUBLISH_STEP_TIMEOUT:-120}   # seconds per attempt (0 disables)
REBUILD_TIMEOUT=${VERDIFY_PUBLISH_REBUILD_TIMEOUT:-300} # Quartz cold-cache build (30..600s)
STEP_RETRIES=${VERDIFY_PUBLISH_STEP_RETRIES:-3}     # total attempts per step
STEP_RETRY_DELAY=${VERDIFY_PUBLISH_STEP_RETRY_DELAY:-5} # seconds between attempts
LOCKED_RC=${VERDIFY_PUBLISH_LOCKED_RC:-0}

mkdir -p "$(dirname "$LOG")" "$(dirname "$LOCK")"

FAILED_STEPS=()

cleanup_future_generated_plans() {
  local plans_dir="/srv/verdify/verdify-site/content/plans"
  local page base page_date removed=0
  [[ -d "$plans_dir" ]] || return 0
  while IFS= read -r -d '' page; do
    base="$(basename "$page")"
    page_date="${base%.md}"
    if [[ "$page_date" > "$DATE" ]] \
      && grep -q "auto-generated by scripts/generate-daily-plan.py" "$page"; then
      rm -f "$page"
      removed=$((removed + 1))
      echo "[$(date -Is)] Removed future generated plan page: ${page}" | tee -a "$LOG"
    fi
  done < <(find "$plans_dir" -maxdepth 1 -type f -name '????-??-??.md' -print0)
  if [[ "$removed" -gt 0 ]]; then
    echo "[$(date -Is)] Removed ${removed} generated plan page(s) after local publish date ${DATE}" | tee -a "$LOG"
  fi
}

# run_step COMMAND [ARGS...] — execute one generator with a bounded wall-clock
# timeout and bounded retries. Records (does not abort on) terminal failures.
run_step() {
  local attempt rc
  for ((attempt = 1; attempt <= STEP_RETRIES; attempt++)); do
    echo "[$(date -Is)] step (attempt ${attempt}/${STEP_RETRIES}, timeout=${STEP_TIMEOUT}s): $*" | tee -a "$LOG"
    rc=0
    # Run inside `if` so `set -e`/`pipefail` does not abort the function on a
    # non-zero step; then read PIPESTATUS[0] — the generator's real exit code,
    # not tee's — to classify the failure. (A trailing `|| true` would clobber
    # PIPESTATUS, so we must branch on the pipeline directly.)
    if [[ "$STEP_TIMEOUT" -gt 0 ]]; then
      # --kill-after sends SIGKILL 10s after SIGTERM so a wedged HTTPS read that
      # ignores the term signal cannot hold the unit open indefinitely.
      if timeout --kill-after=10s "${STEP_TIMEOUT}s" "$@" 2>&1 | tee -a "$LOG"; then
        rc=0
      else
        rc=${PIPESTATUS[0]}
      fi
    else
      if "$@" 2>&1 | tee -a "$LOG"; then
        rc=0
      else
        rc=${PIPESTATUS[0]}
      fi
    fi
    if [[ "$rc" -eq 0 ]]; then
      return 0
    fi
    if [[ "$rc" -eq 124 || "$rc" -eq 137 ]]; then
      echo "[$(date -Is)] TIMEOUT after ${STEP_TIMEOUT}s (rc=${rc}) on attempt ${attempt}/${STEP_RETRIES}: $*" | tee -a "$LOG" >&2
    else
      echo "[$(date -Is)] FAILED (rc=${rc}) on attempt ${attempt}/${STEP_RETRIES}: $*" | tee -a "$LOG" >&2
    fi
    if [[ "$attempt" -lt "$STEP_RETRIES" ]]; then
      sleep "$STEP_RETRY_DELAY"
    fi
  done
  echo "[$(date -Is)] GIVING UP after ${STEP_RETRIES} attempts (last rc=${rc}); continuing remaining steps: $*" | tee -a "$LOG" >&2
  FAILED_STEPS+=("$*")
  return 0
}

report_failed_steps() {
  echo "[$(date -Is)] publish finished with ${#FAILED_STEPS[@]} failed step(s) after retries; rebuild/promotion blocked:" | tee -a "$LOG" >&2
  for step in "${FAILED_STEPS[@]}"; do
    echo "[$(date -Is)]   - ${step}" | tee -a "$LOG" >&2
  done
}

{
  flock -n 9 || {
    echo "[$(date -Is)] publish already running; skipping reason_class=${REASON_CLASS}" | tee -a "$LOG"
    exit "$LOCKED_RC"
  }

  echo "[$(date -Is)] Starting site content publish: reason_class=${REASON_CLASS}, date=${DATE}" | tee -a "$LOG"
  cleanup_future_generated_plans

  run_step "$PYTHON" "$SCRIPT_ROOT/generate-daily-plan.py" --date "$PREV_DATE"
  run_step "$PYTHON" "$SCRIPT_ROOT/generate-daily-plan.py" --date "$DATE"
  run_step "$PYTHON" "$SCRIPT_ROOT/generate-forecast-page.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/generate-plans-index.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/generate-lessons-page.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/generate-ai-tunables-page.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/generate-baseline-vs-iris-page.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/update-evidence-snapshots.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/render-equipment-page.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/render-zone-pages.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/render-crop-profiles.py"
  run_step "$PYTHON" "$SCRIPT_ROOT/export-hourly-performance-dataset.py"
  run_step bash "$SCRIPT_ROOT/export-public-sample-dataset.sh"
  run_step bash "$SCRIPT_ROOT/gather-static-context.sh"
  run_step "$PYTHON" "$SCRIPT_ROOT/check-public-output.py" \
    --root "$PUBLIC_CONTENT_ROOT" \
    --json-report "$PUBLIC_OUTPUT_REPORT"

  # Generators and the source guard are candidate prerequisites. Never rebuild
  # or promote a partial/stale tree after one of them fails.
  if [[ ${#FAILED_STEPS[@]} -gt 0 ]]; then
    report_failed_steps
    exit 1
  fi

  if [[ "$REBUILD" == true ]]; then
    # Quartz has a materially different cold-cache runtime from the small
    # generators above. Keep their tighter network/DB timeout, but give the
    # final local build its own bounded window. Assignment-scoping means
    # run_step sees this value only for the rebuild invocation.
    STEP_TIMEOUT="$REBUILD_TIMEOUT" run_step "$SCRIPT_ROOT/rebuild-site.sh"
    if [[ ${#FAILED_STEPS[@]} -eq 0 ]]; then
      echo "[$(date -Is)] Site content publish complete: reason_class=${REASON_CLASS}, date=${DATE}" | tee -a "$LOG"
    fi
  else
    echo "[$(date -Is)] Site content generated without rebuild: reason_class=${REASON_CLASS}, date=${DATE}" | tee -a "$LOG"
  fi

  # Surface terminal failures once, at the end. A step that recovered on retry
  # leaves FAILED_STEPS empty and we exit clean even though a transient timeout
  # occurred — that is the whole point: a flaky egress no longer wedges the unit.
  # A step that exhausted its retries exits the unit non-zero so systemd still
  # records genuine, persistent breakage as a failure.
  if [[ ${#FAILED_STEPS[@]} -gt 0 ]]; then
    report_failed_steps
    exit 1
  fi
} 9>"$LOCK"
