#!/usr/bin/env python3
"""Create or apply a bounded offline remediation plan from a guard report."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import sys
from pathlib import Path, PurePosixPath

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))
from verdify_public.output_policy import (  # noqa: E402
    PUBLIC_CROP_REDACTION,
    decode_public_text,
    redact_non_public_crop_references,
)

GENERATED_PLAN_PATH_RE = re.compile(r"^plans/(?P<date>\d{4}-\d{2}-\d{2})\.md$")
GENERATED_PLAN_MARKER = "auto-generated by scripts/generate-daily-plan.py"
REPORT_SCHEMA_VERSION = 2
REPORT_MAX_FINDINGS = 10_000
REPORT_MAX_ROOTS = 64
REPORT_MAX_TEXT_CHARS = 4096
REPORT_MAX_BYTES = 8 * 1024 * 1024
REMEDIATION_SOURCE_MAX_BYTES = 16 * 1024 * 1024
REPORT_KEYS = frozenset({"schema_version", "roots", "missing_roots", "routes", "findings"})
ROOT_KEYS = frozenset({"label", "identity"})
FINDING_KEYS = frozenset({"root", "root_identity", "path", "route", "reason"})
REASON_CLASS_BY_SCANNER_REASON = {
    "content": "protected-reference",
    "filename": "protected-filename",
    "invalid-rendered-value": "invalid-rendered-value",
    "unreadable-text": "unsafe-artifact",
    "compressed-metadata-limit": "unsafe-artifact",
    "changed-during-scan": "unsafe-artifact",
    "malformed-compressed-metadata": "unsafe-artifact",
    "unsupported-safe-traversal": "unsafe-artifact",
    "path-traversal": "unsafe-artifact",
    "missing-root": "unsafe-artifact",
    "not-directory": "unsafe-artifact",
    "unreadable-directory": "unsafe-artifact",
    "unreadable-entry": "unsafe-artifact",
    "symlink": "unsafe-artifact",
    "special-entry": "unsafe-artifact",
    "unreadable-file": "unsafe-artifact",
    "hardlink": "unsafe-artifact",
    "decode-limit": "unsafe-artifact",
    "compressed-artifact-limit": "unsafe-artifact",
    "malformed-compressed-artifact": "unsafe-artifact",
    "unsupported-compressed-container": "unsafe-artifact",
}


def _bounded_text(value: object) -> str:
    if not isinstance(value, str) or not value or len(value) > REPORT_MAX_TEXT_CHARS:
        raise ValueError("invalid report text")
    return value


def _safe_report_path(value: object) -> str:
    raw = _bounded_text(value)
    if "\\" in raw:
        raise ValueError("invalid report path")
    decoded = decode_public_text(raw)
    if decoded.limit_hit:
        raise ValueError("invalid report path")
    for variant in decoded.variants:
        candidate = PurePosixPath(variant)
        if candidate.is_absolute() or not candidate.parts or any(part in {"", ".", ".."} for part in candidate.parts):
            raise ValueError("invalid report path")
    normalized = PurePosixPath(raw).as_posix()
    return redact_non_public_crop_references(normalized)


def _safe_report_route(value: object) -> str:
    raw = _bounded_text(value)
    if "\\" in raw or not raw.startswith("/"):
        raise ValueError("invalid report route")
    decoded = decode_public_text(raw)
    if decoded.limit_hit:
        raise ValueError("invalid report route")
    for variant in decoded.variants:
        candidate = PurePosixPath(variant)
        if not candidate.is_absolute() or any(part in {"", ".", ".."} for part in candidate.parts):
            raise ValueError("invalid report route")
    normalized = "/" + PurePosixPath(raw).as_posix().lstrip("/")
    return redact_non_public_crop_references(normalized)


def _public_route_from_path(path: str) -> str:
    candidate = PurePosixPath(path)
    if candidate.suffix.casefold() in {".md", ".html"}:
        candidate = candidate.with_suffix("")
        parts = list(candidate.parts)
        if parts and parts[-1] == "index":
            parts.pop()
        route = "/" + "/".join(parts) if parts else "/"
    else:
        route = "/" + candidate.as_posix()
    return redact_non_public_crop_references(route)


def _root_identity(file_descriptor: int) -> str:
    metadata = os.fstat(file_descriptor)
    material = f"public-output-root-v1:{metadata.st_dev}:{metadata.st_ino}".encode()
    return hashlib.sha256(material).hexdigest()


def _validated_findings(report: object, root: Path) -> list[dict[str, str]]:
    if (
        not isinstance(report, dict)
        or set(report) != REPORT_KEYS
        or report.get("schema_version") != REPORT_SCHEMA_VERSION
    ):
        raise ValueError("invalid scanner report")
    roots = report.get("roots")
    missing_roots = report.get("missing_roots")
    findings = report.get("findings")
    if (
        not isinstance(roots, list)
        or len(roots) != 1
        or len(roots) > REPORT_MAX_ROOTS
        or missing_roots != []
        or not isinstance(findings, list)
        or len(findings) > REPORT_MAX_FINDINGS
    ):
        raise ValueError("invalid scanner report")
    declared_root = roots[0]
    if not isinstance(declared_root, dict) or set(declared_root) != ROOT_KEYS:
        raise ValueError("invalid scanner report")
    declared_label = _bounded_text(declared_root.get("label"))
    declared_identity = _bounded_text(declared_root.get("identity"))
    root_fd = _open_directory_nofollow(root)
    if root_fd is None:
        raise ValueError("invalid scanner report")
    try:
        actual_identity = _root_identity(root_fd)
    finally:
        os.close(root_fd)
    actual_label = redact_non_public_crop_references(root.name or str(root))
    if declared_identity != actual_identity or declared_label != actual_label:
        raise ValueError("invalid scanner report")
    routes = report.get("routes")
    if not isinstance(routes, list) or len(routes) > REPORT_MAX_FINDINGS:
        raise ValueError("invalid scanner report")
    validated_routes = [_safe_report_route(route) for route in routes]
    if validated_routes != sorted(set(validated_routes)):
        raise ValueError("invalid scanner report")
    validated: list[dict[str, str]] = []
    for finding in findings:
        if not isinstance(finding, dict) or set(finding) != FINDING_KEYS:
            raise ValueError("invalid scanner finding")
        if (
            _bounded_text(finding.get("root")) != declared_label
            or _bounded_text(finding.get("root_identity")) != declared_identity
        ):
            raise ValueError("invalid scanner finding")
        path = _safe_report_path(finding.get("path"))
        route = _safe_report_route(finding.get("route"))
        derived_route = _public_route_from_path(path)
        if route != derived_route:
            raise ValueError("invalid scanner finding")
        scanner_reason = _bounded_text(finding.get("reason"))
        reason_class = REASON_CLASS_BY_SCANNER_REASON.get(scanner_reason)
        if reason_class is None:
            raise ValueError("invalid scanner finding")
        validated.append(
            {
                "path": path,
                "route": route,
                "scanner_reason": scanner_reason,
                "reason_class": reason_class,
            }
        )
    if validated_routes != sorted({finding["route"] for finding in validated}):
        raise ValueError("invalid scanner report")
    return validated


def _open_directory_nofollow(path: Path) -> int | None:
    """Open a directory path component-by-component without following links."""
    if not hasattr(os, "O_NOFOLLOW") or not hasattr(os, "O_DIRECTORY"):
        return None
    absolute = Path(os.path.abspath(path))
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    try:
        directory_fd = os.open(absolute.anchor, flags)
    except OSError:
        return None
    try:
        for part in absolute.parts[1:]:
            next_fd = os.open(part, flags, dir_fd=directory_fd)
            os.close(directory_fd)
            directory_fd = next_fd
        return directory_fd
    except OSError:
        os.close(directory_fd)
        return None


def _reject_duplicate_keys(pairs: list[tuple[str, object]]) -> dict:
    result: dict = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def _reject_nonfinite_constant(_value: str) -> object:
    raise ValueError("nonfinite JSON constant")


def _read_report(path: Path) -> dict:
    flags = os.O_RDONLY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    file_descriptor = os.open(path, flags)
    try:
        metadata = os.fstat(file_descriptor)
        if not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1 or metadata.st_size > REPORT_MAX_BYTES:
            raise ValueError("invalid report file")
        payload = bytearray()
        while chunk := os.read(file_descriptor, min(1024 * 1024, REPORT_MAX_BYTES + 1 - len(payload))):
            payload.extend(chunk)
            if len(payload) > REPORT_MAX_BYTES:
                raise ValueError("invalid report file")
    finally:
        os.close(file_descriptor)
    return json.loads(
        payload.decode("utf-8"),
        object_pairs_hook=_reject_duplicate_keys,
        parse_constant=_reject_nonfinite_constant,
    )


def _open_confined_source(root: Path, relative: str, *, writable: bool = False) -> int | None:
    """Open a regular source file without following root, intermediate, or final links."""
    candidate = Path(relative)
    if (
        candidate.is_absolute()
        or not candidate.parts
        or any(part in {"", ".", ".."} for part in candidate.parts)
        or PUBLIC_CROP_REDACTION in relative
    ):
        return None
    directory_fd = _open_directory_nofollow(root)
    if directory_fd is None:
        return None
    directory_flags = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    file_flags = (os.O_RDWR if writable else os.O_RDONLY) | os.O_NOFOLLOW | getattr(os, "O_CLOEXEC", 0)
    file_flags |= getattr(os, "O_NONBLOCK", 0)
    source_fd: int | None = None
    try:
        for part in candidate.parts[:-1]:
            next_fd = os.open(part, directory_flags, dir_fd=directory_fd)
            os.close(directory_fd)
            directory_fd = next_fd
        source_fd = os.open(candidate.parts[-1], file_flags, dir_fd=directory_fd)
        metadata = os.fstat(source_fd)
        if (
            not stat.S_ISREG(metadata.st_mode)
            or metadata.st_nlink != 1
            or metadata.st_size > REMEDIATION_SOURCE_MAX_BYTES
        ):
            os.close(source_fd)
            return None
        return source_fd
    except OSError:
        if source_fd is not None:
            os.close(source_fd)
        return None
    finally:
        os.close(directory_fd)


def build_manifest(report: dict, root: Path, *, apply_redaction: bool = False) -> dict:
    grouped: dict[str, dict] = {}
    for finding in _validated_findings(report, root):
        path = finding["path"]
        item = grouped.setdefault(
            path,
            {
                "path": path,
                "route": finding["route"],
                "scanner_reasons": set(),
                "reason_classes": set(),
            },
        )
        item["scanner_reasons"].add(finding["scanner_reason"])
        item["reason_classes"].add(finding["reason_class"])

    items: list[dict] = []
    for path, grouped_item in sorted(grouped.items()):
        scanner_reasons = sorted(grouped_item["scanner_reasons"])
        reason_classes = sorted(grouped_item["reason_classes"])
        match = GENERATED_PLAN_PATH_RE.fullmatch(path)
        generated = False
        applied = False
        source_fd = _open_confined_source(root, path, writable=apply_redaction) if match else None
        if source_fd is not None:
            mode = "r+b" if apply_redaction else "rb"
            with os.fdopen(source_fd, mode) as source:
                try:
                    source_text = source.read().decode("utf-8")
                except (OSError, UnicodeError):
                    generated = False
                else:
                    generated = GENERATED_PLAN_MARKER in source_text
                    can_redact = bool(generated and scanner_reasons == ["content"])
                    if apply_redaction and can_redact:
                        redacted = redact_non_public_crop_references(source_text)
                        if redacted != source_text:
                            source.seek(0)
                            source.write(redacted.encode("utf-8"))
                            source.truncate()
                            source.flush()
                            os.fsync(source.fileno())
                            applied = True

        date = match.group("date") if match else None
        can_redact = bool(generated and scanner_reasons == ["content"])

        if generated:
            action = "redact_generated_plan" if can_redact else "regenerate_generated_plan"
            regenerate_command = ["python3", "scripts/generate-daily-plan.py", "--date", date]
        else:
            action = "manual_review"
            regenerate_command = None

        items.append(
            {
                "path": path,
                "route": grouped_item["route"],
                "date": date,
                "reason_classes": reason_classes,
                "action": action,
                "automatic_redaction_eligible": can_redact,
                "redaction_applied": applied,
                "regenerate_command": regenerate_command,
            }
        )

    return {
        "schema_version": 2,
        "source_root": "<SOURCE_ROOT>",
        "apply_redaction": apply_redaction,
        "items": items,
        "rescan_command": [
            "python3",
            "scripts/check-public-output.py",
            "--root",
            "<SOURCE_ROOT>",
            "--json-report",
            str(Path("public-output-report.json")),
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--report", type=Path, required=True, help="JSON report from check-public-output.py")
    parser.add_argument("--root", type=Path, required=True, help="Offline source root referenced by the report")
    parser.add_argument(
        "--manifest", type=Path, required=True, help="Write the deterministic remediation manifest here"
    )
    parser.add_argument(
        "--apply-redaction",
        action="store_true",
        help="Redact only marker-verified generated daily-plan files with content-only findings",
    )
    args = parser.parse_args()

    try:
        report = _read_report(args.report)
    except (OSError, UnicodeError, ValueError, json.JSONDecodeError):
        print("public-output remediation: invalid scanner report", file=sys.stderr)
        return 2
    root_fd = _open_directory_nofollow(args.root)
    if root_fd is None:
        print("public-output remediation: source root is missing", file=sys.stderr)
        return 2
    os.close(root_fd)

    try:
        manifest = build_manifest(report, args.root, apply_redaction=args.apply_redaction)
    except ValueError:
        print("public-output remediation: invalid scanner report", file=sys.stderr)
        return 2
    try:
        args.manifest.parent.mkdir(parents=True, exist_ok=True)
        args.manifest.write_text(
            json.dumps(manifest, indent=2, sort_keys=True, allow_nan=False) + "\n",
            encoding="utf-8",
        )
    except (OSError, TypeError, ValueError):
        print("public-output remediation: manifest write failed", file=sys.stderr)
        return 2
    print(f"public-output remediation: wrote {len(manifest['items'])} bounded item(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
